Feature/kas 2721 details dossier
kanselarij-vlaanderen/frontend-kaleidos pull request #1021
Opened 2021-07-27 06:23 UTC by TaneeG

2021-07-27 21:49 UTC, erikap requested changes
De `Cases::NewSubcase` component moet ik nog reviewen maar dat zal voor donderdag zijn. Hier kan je al zeker mee starten. En waarschijnlijk zijn enkele van de comments ook van toepassing op de `Cases::NewSubcase` component en kan je die al uitvoeren.

2021-07-27 21:49 UTC, erikap commented on app/pods/cases/case/subcases/overview/template.hbs
> +      />
Hier kan beter de `Auk::EmptyState` component gebruikt worden nu die er is

2021-07-27 21:49 UTC, erikap commented on app/pods/cases/case/subcases/overview/template.hbs
> +  {{#if (gt (await this.model.subcases.length) 0)}}
Dit kan korter geschreven worden door gewoon `this.model.subcases`. Dit gaat als falsy aanzien worden indien het een lege array is. 

De `await` is niet expliciet nodig omdat de Ember template automatisch update als de relation promise resolved.

2021-07-27 21:49 UTC, erikap commented on app/pods/cases/case/subcases/overview/route.js
> +  }
Zoals beschreven in de story kan de model hook beter gerefactored worden zodat het main model de lijst van subcases is en de case nadien ingesteld wordt als `@tracked` property op de controller.

2021-07-27 21:49 UTC, erikap commented on app/pods/cases/case/subcases/overview/route.js
> +export default class CaseSubcasesOverviewRoute extends Route {
Naam stemt niet helemaal overeen met de hierarchy waar deze route zich bevindt.

2021-07-27 21:49 UTC, erikap commented on app/pods/cases/case/subcases/overview/template.hbs
> +        @backLink={{this.backLinkAction}}
Deze 2 argumenten lijken mij overbodig? Ik zie ze alleszins niet gedefinieerd staan op de controller.

2021-07-27 21:49 UTC, erikap commented on app/pods/cases/case/subcases/overview/controller.js
> +export default class CaseSubcasesOverviewController extends Controller {
Naam stemt niet helemaal overeen met de hierarchy waar deze controller zich bevindt.

2021-07-27 21:49 UTC, erikap commented on app/components/subcases/subcases-overview-header.hbs
> +          {{on "click" this.goBackToCases}}
Hier zou ik een `LinkTo` component gebruiken ipv een button met een action. Er is waarschijnlijk ook een variant van de `Auk::Button` die een `@route` param of iets dergelijks ondersteunt.

2021-07-27 21:49 UTC, erikap commented on app/components/subcases/subcases-overview-header.js
> +    return this.args.case.title;
Geleerd uit een andere PR. Dit kan je korter en rechtstreeks in de template doen als:
```
@text={{or @case.shortTitle @case.title}}
```

2021-07-27 21:49 UTC, erikap commented on app/components/subcases/subcases-overview-header.js
>    @tracked shortTitle = null;
Deze properties lijken mij niet gebruikt te worden

2021-07-27 21:49 UTC, erikap commented on app/pods/cases/case/subcases/overview/controller.js
> +  *saveSubcase(subcase) {
Deze zou ik eerder `addSubcase` noemen (en het argument van de component dan `onAddSubcase`). Dat verklaart beter waarom er hier een `reloadModel` nodig is. Wanneer een bestaande subcase gewijzigd wordt (wat `saveSubcase` impliceert) zou het model niet herladen moeten worden.

2021-07-27 21:49 UTC, erikap commented on app/components/subcases/subcases-overview-header.hbs
> +        <Auk::Toolbar::Item>
Deze comment slaat op de `Auk::Toolbar` component waarin deze gewrapped is:  met `@size="large"` ziet die er iets beter uit.

2021-07-27 21:49 UTC, erikap commented on app/pods/cases/case/subcases/overview/controller.js
> +    this.toaster.success(this.intl.t('successfully-saved'));
Volgens de nieuwe "toast-policy" is deze succes toast niet nodig aangezien gebruikers expliciet op een opslaan-button klikken en het geen autosave is. Zelfde bij `saveCase`.

2021-07-27 21:49 UTC, erikap commented on app/components/cases/edit-case-with-confidential.hbs
> +<Auk::Modal>
Ik zie nu pas dat er al een `cases/edit-case` component was. Dan kan beter deze gebruikt en gerefactored worden naar een DDAU-component. Die component heeft geen toggle voor de vertrouwelijkheid van het dossier, maar dat lijkt dan een dataveld dat de gebruikers niet moeten kunnen wijzigen. 

Ik zou de edit-case-with-confidential component dus terug verwijderen uit deze PR en de edit-case component refactoren. Voor de refactor zal je waarschijnlijk wel grote delen van deze edit-case-with-confidential component  kunnen gebruiken.

De edit-case component wordt ook gebruikt in de `cases/overview` route, dus daar moeten mogelijk ook enkele wijzigingen gebeuren als de component gerefactored wordt naar DDAU.

2021-07-27 21:49 UTC, erikap commented on app/components/cases/edit-case-with-confidential.js
> +  }
Hier zou ik wel gewoon rechtstreeks de properties van de case wijzigen (zonder op te slaan) en `this.args.case` meegeven aan de `onSave` action handler.

2021-07-27 21:49 UTC, erikap commented on app/components/cases/edit-case-with-confidential.hbs
> +        </Auk::Toolbar::Item>
Er is een kortere variant van de `Auk::Modal::Footer` zodat je de annuleren-button aan de linkerkant niet zelf moet specifieren maar gewoon een `@onCancel` en `@cancelDisabled` argument kan meegeven.

2021-07-27 21:49 UTC, erikap commented on app/components/cases/edit-case-with-confidential.hbs
> +            <Utils::SimpleSpinner/>
Hier kan beter de loading state van de `Auk::Button` gebruikt worden.

2021-07-29 15:31 UTC, erikap requested changes

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +export default class NewSubcase extends Component {
Classname komt niet overeen met de locatie van deze component

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +    this.caseTypes = yield this.store.query('case-type', {
PAGE_SIZE voor codelists meegeven in de query

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +  @tracked pieces;
Deze lijkt mij niet gebruikt

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.hbs
> +                {{on "click"  (perform this.copyFullSubcase)}}
Double space verwijderen

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.hbs
> +    {{#unless  this.loadTitleData.isRunning}}
Double space verwijderen

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.hbs
> +      {{#unless this.loadCaseTypes.isRunning}}
Ik zou hier de `Utils::LoadableContent` component gebruiken, zoals we doen in de modals van publications, om alle inhoud van de modal te verbergen zolang de case-types en titles laden

2021-07-29 15:31 UTC, erikap commented on app/components/cases/edit-case.hbs
> +    {{#if hasError}}
Scope (`this` of `@`) toevoegen

2021-07-29 15:31 UTC, erikap commented on app/components/cases/edit-case.hbs
> +    <div class="auk-form-group {{getClassForShortTitle}}">
`getClassForShortTitle` lijkt mij ongebruikt

2021-07-29 15:31 UTC, erikap commented on app/components/cases/edit-case.js
> +  @tracked isConfidential = this.args.case.confidential;
Die copy van de attributes van `this.args.case` nemen, lijkt mij niet nodig. Je kan in de template gewoon `@case.title` gebruiken voor het invulveld. Hetzelfde voor `isConfidential`.

De save-action wordt daardoor eenvoudiger omdat de waarden niet terug gekopieerd moeten worden. Enkel bij annuleren moet er dan eerst `this.case.rollbackAttributes()` gebeuren alvorens de `@onClose`-handler te callen.

2021-07-29 15:31 UTC, erikap commented on app/components/cases/edit-case.js
> +    return this.shortTitle === null || this.shortTitle.trim().length === 0;
Hier kan je de `isBlank` util van Ember beter gebruiken

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.hbs
>          {{#if (not isEditing)}}
Scoping (`this` of `@`) toevoegen

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +  @action
Deze wordt enkel als hulp-method gebruikt en heeft geen `@action` annotation nodig.

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +  selectModel(items) {
`selectSubcaseName` is een duidelijkere naam voor deze actie.  En argument in enkelvoud want er wordt maar 1 waarde geselecteerd

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +    this.subcaseName = items.get('label');
`get()` is niet nodig

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +  @tracked pieces;
Deze lijkt mij niet gebruikt

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +    this.caseTypes = yield this.store.query('case-type', {
PAGE_SIZE voor codelists meegeven in de query

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +  @tracked selectedSubcaseName;
`selectedShortcut` is een betere naam aangezien dat blijkbaar het soort record is dat hierin opgeslagen wordt

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.hbs
> +                  @value={{subcaseName}}
Scoping toevoegen

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.hbs
> +      </Auk::Toolbar::Group>
Hier kan je de nieuwe, kortere variant van de footer gebruiken

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.hbs
> +            <Utils::SimpleSpinner/>
Gebruik de loading state van de `Auk::Button`

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.hbs
> +              {{on "click"  (perform this.saveSubcase)}}
Verwijder dubbele space

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +      });
Ik zou hier gewoon de `subcase` meegeven als argument zonder nog eens te wrappen in een object.
Aangezien `Case::NewSubcase` enkel gebruikt wordt in `subcases-overview-header` heeft die wijziging enkel daar impact.

2021-07-29 15:31 UTC, erikap commented on app/components/cases/new-subcase.js
> +      });
Ik zou hier gewoon de `subcase` meegeven als argument zonder nog eens te wrappen in een object.
Aangezien `Case::NewSubcase` enkel gebruikt wordt in `subcases-overview-header` heeft die wijziging enkel daar impact.

2021-07-30 08:16 UTC, TaneeG commented
@erikap Alles zou nu gepushed moeten zijn

2021-08-03 06:22 UTC, erikap approved these changes

2021-08-03 09:07 UTC, merged