Feature/kas 2843 kas2845 grid kolom
kanselarij-vlaanderen/frontend-kaleidos pull request #1070
Opened 2021-09-06 08:40 UTC by TaneeG

Jira
- Proef in
- Vertaling in
PR:

2021-09-06 09:53 UTC, erikap requested changes
Zie ook comment in backend: in lijn met het model van `dossier:Stuk` zou ik voor `receivedDate` gaan als attribute name ipv `dateReceived`

2021-09-06 09:53 UTC, erikap commented on app/pods/publications/publication/proofs/requests/controller.js
> +      proofUpload.receivedAtDate < this.publicationSubcase.dateReceived
Deze conditie moet omgekeerd. De datum op de subcase moet enkel aangepast worden als de nieuwe received-date recenter (dus groter dan) is dan de huidige received-date.

2021-09-06 09:53 UTC, erikap commented on app/pods/publications/publication/translations/requests/controller.js
> +      translationUpload.receivedAtDate < this.translationSubcase.dateReceived
Conditie moet omgekeerd

2021-09-07 21:47 UTC, erikap requested changes
Niet zeker of je hier al klaar mee bent aangezien de PR nog aan jou geassigned is @TaneeG  en er nog comments van de vorige review unresolved zijn.
De backend branch is al gemerged dus er is geen custom Jenkins run meer nodig.

2021-09-07 21:47 UTC, erikap commented on app/config/publications/overview-table-columns.js
> +    sortKey: 'publication-subcase.date-received',
Aanpassen naar `received-date`

2021-09-07 21:47 UTC, erikap commented on app/config/publications/overview-table-columns.js
> +    sortKey: 'translation-subcase.date-received',
Aanpassen naar `received-date`

2021-09-08 06:16 UTC, TaneeG commented
Sorry @erikap Ik was ze vergeten te rsolven

2021-09-08 09:29 UTC, erikap commented
> Sorry @erikap Ik was ze vergeten te rsolven

@TaneeG Nu ben ik in de war. Die issues zijn toch niet resolved? In de laatste versie van deze branch is het sort-field en de vergelijking van de datums toch nog steeds verkeerd?

2021-09-09 06:17 UTC, TaneeG commented
Ah nu zie ik waar. Ik was zelf in de war

2021-09-15 15:01 UTC, ValenberghsSven approved these changes

2021-09-15 15:04 UTC, merged