Feature/kas 2873 volgorde tabs
kanselarij-vlaanderen/frontend-kaleidos pull request #1075
Opened 2021-09-13 12:45 UTC by TaneeG

jira: https://kanselarij.atlassian.net/browse/KAS-2873

2021-09-14 08:39 UTC, ValenberghsSven requested changes
De move van de blokjes is ok, maar de prettier format heeft wat rare dingen gedaan

2021-09-14 08:39 UTC, ValenberghsSven commented on app/components/m-header.hbs
> +            }}</Auk::Tab>
is dit prettier ? Ik zou denken dat die `{{t "cases" }}` op 1 lijn zou staan, zoals `{{t "publications"}}`

2021-09-14 08:39 UTC, ValenberghsSven commented on app/components/m-header.hbs
> +                  }}</span>
deze ook, echt "pretty" is dat toch niet

2021-09-14 08:39 UTC, ValenberghsSven commented on app/components/m-header.hbs
> +                  >{{this.currentSession.group.name}}</p>
```
<p class="auk-u-muted auk-u-text-small">
   {{this.currentSession.group.name}}
</p>
```
ipv wat er nu staat

2021-09-15 07:46 UTC, TaneeG commented on app/components/m-header.hbs
> +                  >{{this.currentSession.group.name}}</p>
Ik weet ook niet waarom maar dat was prettier ervan had gemaakt. Ik fix het

2021-09-15 14:26 UTC, ValenberghsSven approved these changes
Jenkins is gefaald op gekende flaky, geen probleem

2021-09-15 14:27 UTC, merged