Feature/kas 2308 refactor newsletter service
kanselarij-vlaanderen/frontend-kaleidos pull request #1149
Opened 2021-12-20 14:06 UTC by TaneeG

Jira: https://kanselarij.atlassian.net/browse/KAS-2308
Service: https://github.com/kanselarij-vlaanderen/newsletter-service/pull/39

2021-12-21 15:29 UTC, ValenberghsSven requested changes

2021-12-21 15:29 UTC, ValenberghsSven commented on app/services/newsletter-service.js
> +      throw new Error('An exception ocurred: ' + response.error);
Dit zit toch niet helemaal goed.
Ik heb lokaal een mail campagne gemaakt die niet verstuurd zou mogen worden.
(1 kort bestek van een nota zonder een thema geselecteerd)
De campaign aanmaken zal lukken, maar het versturen zal resulteren in een error van mailchimp:
"Error: Your Campaign is not ready to send." in de newsletter-service.
Echter krijgt de frontend wel een 200 binnen
![image](https://user-images.githubusercontent.com/22245223/146954850-71a58c49-3176-4683-98ef-b8b2737e6899.png)
Maar de response is wel degelijk een error.
![image](https://user-images.githubusercontent.com/22245223/146954962-2d748615-a8de-4b8a-812a-1b46b0c736aa.png)

De frontend denkt dus onterecht dat de campagne is verstuurd, en we setten 'isSent' waardoor opnieuw versturen niet mogelijk is.

2021-12-21 15:29 UTC, ValenberghsSven commented on app/services/newsletter-service.js
> +      throw new Error('An exception ocurred: ' + response.error);
Wat er lijkt te gebeuren is dat de fetch call al resolved is voor de response er is.
Want je krijgt tussentijds een andere response binnen (status ok, code 200, type 'basic') als je logt vlak na de fetch call.

2021-12-22 08:13 UTC, ValenberghsSven commented on app/services/newsletter-service.js
> +      throw new Error('An exception ocurred: ' + response.error);
rand info, de reden dat 1 nota zonder thema's faalt is omdat er dan 0 ontvangers zijn en mailchimp is zo slim om dan het verzenden van die nieuwsbrief tegen te houden

2021-12-24 10:51 UTC, ValenberghsSven commented
Er is een fix gebeurd in newsletter-service, maar dekt de lading niet.
Het feit dat de errors niet deftig doorkomen komt door gebruik van `fetch` ipv `ajax`.
Fetch is een promise, dus de teruggestuurde error is nog niet resolved bij opstellen van het error bericht in de frontend.

```
const endpoint = `/newsletter/send-mail-campaign`;
    const body = {
      data: {
        id: id,
      },
    };
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/vnd.api+json',
      },
      body: JSON.stringify(body),
    });
    console.log(response);
    const payload = await response.json();
    console.log(payload);
```

2022-01-21 12:37 UTC, erikap commented
Ik heb deze terug in Draft gezet totdat KAS-3100 gepasseerd is, om dubbel review werk te vermijden.

2022-02-25 11:26 UTC, ValenberghsSven commented
@Annelies-P Mag deze worden gesloten nu dat https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1209 open staat?

2022-02-25 14:36 UTC, Annelies-P commented
@ValenberghsSven Deze mag inderdaad weg

2022-03-07 14:00 UTC, ValenberghsSven commented
Changes in this PR are contained in https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1209. Closing

2022-03-07 14:00 UTC, closed without merging