Feature/kas 1814 confidentialy cascade
kanselarij-vlaanderen/frontend-kaleidos pull request #1153
Opened 2021-12-23 15:54 UTC by ValenberghsSven

2022-02-03 09:58 UTC, MikiDi requested changes
change-requests met betrekking tot octane-refactors toegevoegd. Stel voor om de wijzigingen mbt cascade-gedrag te laten vallen tot design-onderzoek omtrent vertrouwelijkheid afgerond is.

2022-02-03 09:58 UTC, MikiDi commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles-edit.js
> +      this.args.agendaitem.get('hasDirtyAttributes');
Kan zonder getter denk ik. Geldt ook voor andere `.get('hasDirtyAttributes')` in deze file.

2022-02-03 09:58 UTC, MikiDi commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles-edit.js
> +    this.isSaving = true;
een `task` maken van `saveChanges` kan deze tracke proprty elimineren?

2022-02-03 09:58 UTC, MikiDi commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles-edit.js
> +          this.newsletterInfo.set('richtext', trimmedTitle);
Kan zonder setters?

2022-02-03 09:58 UTC, MikiDi commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles-edit.js
>      try {
Zonder een `except` heeft deze `try ... finally`-constructie niet veel waarde meer. Mag weg ...

2022-02-04 08:35 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles-edit.js
>      try {
De try catch was origineel bedoeld om fouten op te vangen in de verwerking in de gebruikte functies, maar daar gooien wij zelf geen errors bij problemen dus catch leek overbodig.
Als er iets zou foutlopen in die verwerking dan handelen we dat alvast niet af (rollback is moeilijk, want je weet niet wat er al is gepersisteerd en wat niet.
In dat opzicht gaat de finally ervoor zorgen dat de save knop terug beschikbaar wordt sluit bij errors (en rode toast vermoedelijk).
Die finally had ik toegevoegd omdat er dubbele code stond in de `try` en in de `catch`, dus een finally leek me logisch.

Lang verhaal kort:
Is het niet beter dat we de save knop terug beschikbaar maken bij errors? (gebeurt niet veel vermoed ik)
De gebruiker kan dan nog een poging doen om te saven, als het hier dan op een korte netwerkonderbreking gaat is hij niet al zijn werk kwijt en kan een tweede save wel werken
Willen we eventuele errors hier toch opvangen ook al zegt de editor dat de catch nutteloos is?

2022-02-04 12:39 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles-edit.js
>      try {
Met de task is de try finally eruit, is wel ok zo.
Bij errors (vb concurrency) blijft de edit component gewoon openstaan

2022-02-04 12:40 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles-edit.js
> +    this.isSaving = true;
done

2022-02-04 17:15 UTC, ValenberghsSven commented
De 2 testen die falen zijn al stuk op DEV dus te negeren.

2022-02-08 11:59 UTC, MikiDi commented
Ik zie dat je regelmatig gebruik maakt van `cancelEdit` (agenda-item utils). Ik kende deze niet en vind het geen fantastische abstractie. Is het niet duidelijker van van gewoon ter plekke terug te rollen wat er effectief veranderd kan zijn? Dat verschilt van case tot case. Die zit er wel al lang in en is breed gebruikt, dus hier is ws niet de plaats om daar aan te tornen. Verder ok.

2022-02-08 11:59 UTC, MikiDi approved these changes

2022-02-08 12:15 UTC, ValenberghsSven commented
> Ik zie dat je regelmatig gebruik maakt van `cancelEdit` (agenda-item utils). Ik kende deze niet en vind het geen fantastische abstractie. Is het niet duidelijker van van gewoon ter plekke terug te rollen wat er effectief veranderd kan zijn? Dat verschilt van case tot case. Die zit er wel al lang in en is breed gebruikt, dus hier is ws niet de plaats om daar aan te tornen. Verder ok.

Mogelijk kan die abstractie er wel uit, dat dateert nog van toen er maar 1 component was voor zowel agendaitem als procedurestap. Ik zal dat in een ticket gieten voor later.

2022-02-08 13:43 UTC, merged