Feature/kas 3026 aanpassen pubstatus
kanselarij-vlaanderen/frontend-kaleidos pull request #1160
Opened 2022-01-06 15:02 UTC by TaneeG

jira: https://kanselarij.atlassian.net/browse/KAS-3026
backend: https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/250
jenkins: http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/154/

2022-01-07 18:01 UTC, erikap requested changes
Bij het (proberen) testen van deze story ben ik wat issues tegengekomen met het opslaan van de relatie tussen publication-flow en publication-status-change. Die is niet geintroduceerd door deze story, maar ik snap niet goed hoe je dit zelf hebt kunnen testen :confused: 

1. Bij het aanmaken van een nieuwe publicatie wordt er wel een publication-status-change resource gemaakt, maar de relatie met de publication-flow wordt niet correct opgeslagen (oorzaak: verkeerde relatienaam in https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/feature/kas-3026_Aanpassen_pubstatus/app/services/publication-service.js#L91). Hierdoor krijg ik een error wanneer ik de status probeer te wijzigen van een nieuwe publicatie.
2. De relatie tussen publication-flow en publication-status-change is one-to-one. Het is dus de bedoeling om enkel voor de laatste wijziging de publication-status-change bij te houden en niet voor alle historische wijzigingen. Op dit moment worden er enkel nieuwe publication-status-change resources toegevoegd zonder de vorige te verwijderen. (de backend zal nu een van die publication-status-change resources kiezen om terug te geven voor de relatie, maar wanneer dit niet de laatste is, wordt een verkeerde datum getoond in de frontend)

2022-01-07 18:01 UTC, erikap commented on app/components/publications/publication-sidebar.hbs
> +        {{#if this.publicationStatus.isStarted}}
Deze aanpassing is volgens mij te kort door de bocht. Overal waar voorheen iets getoond werd bij status `isPending` moet dit volgens mij nu getoond worden in elke status die niet gepauzeerd of finaal is. De vroegere status `isPending` is nu opgesplitst in verschillende andere statussen (proef in, rappel proef, ...)

Ik zou daarom een getter `isPending` (of `isOngoing`) toevoegen op publication-status data model dat `true` geeft bij alle statussen behalve `isPaused`, `isPublished` of `isWithdrawn`.

2022-01-07 18:01 UTC, erikap commented on app/pods/publications/publication/template.hbs
> +            </Auk::ButtonLink>
Kan je de weergave en editeren van de status in een aparte component steken? Dat gaat volgens mij de route/controller vereenvoudigen.

2022-01-10 14:14 UTC, TaneeG commented
@erikap Deze is terug klaar voor review.
Heb die faulty link ook hersteld. 

Design is nog niet klaar voor volgens prototype dit gaat @brenner-company later opnemen

2022-01-10 17:37 UTC, erikap commented
Voornaamste wijziging die ik nog gedaan heb, is het verwijderen van de extra confirmatie bij het annuleren van een publicatie. Die was vroeger toegevoegd omdat in de sidebar het aanpassen van de status automatisch opgeslagen werd. Dat is nu niet meer het geval. De gebruiker zit al in een modal waar hij expliciet op 'Opslaan' moet klikken om de change te bevestigen. Die extra confirmatie is dus overbodig.

2022-01-10 17:43 UTC, erikap approved these changes

2022-01-11 13:40 UTC, merged