Feature/kas 2308 newsletter
kanselarij-vlaanderen/frontend-kaleidos pull request #1209
Opened 2022-02-23 14:44 UTC by Annelies-P

Contains the changes from KAS-2308_Refactor_newsletter_service

2022-03-07 17:24 UTC, ValenberghsSven requested changes
Not done with review yet but wanted to close off the day with found issues.
Error handling is not really what I expected yet. 
note: I am comparing it to what I did in `agenda-actions.js`. Where I included the server message in the toaster message. It might not be the best approach so open for debate.

2022-03-07 17:24 UTC, ValenberghsSven commented on app/services/newsletter-service.js
> +      throw new Error('An exception ocurred: ' + response.error);
Any specific error we throw from the backend should come out of this, so the user has some feedback of what happened.
But the error we throw here with a message is never used again so we lose that extra bit of information of what went wrong, just a vague message "something went wrong while ...."

2022-03-07 17:24 UTC, ValenberghsSven commented on app/services/newsletter-service.js
> +      throw new Error('An exception ocurred: ' + response.error);
Also `response.error` is not correct.
`result` gets the json object with a list of errors
![image](https://user-images.githubusercontent.com/22245223/157084290-34ecfcda-a82d-4bb4-885a-ca63819dff84.png)
while `response` gets the fetch call or something and doesn't contain the proper info
![image](https://user-images.githubusercontent.com/22245223/157084910-c966fca9-d34c-4009-abeb-6313641fda2e.png)

2022-03-14 09:12 UTC, Annelies-P commented on app/services/newsletter-service.js
> +      throw new Error('An exception ocurred: ' + response.error);
I see your point. The problem here is that it is possible the error in the backend is linked to mailchimp. Do we want to bother the user with this? Or is showing a more detailed message like 'Something went wrong creating a mailcampaign' is sufficient?

2022-03-14 09:50 UTC, ValenberghsSven commented on app/services/newsletter-service.js
> +      throw new Error('An exception ocurred: ' + response.error);
My idea about this is that that we receive custom error messages from the backend service in order to identify the exact problem. The user may not really care why something failed but it makes the follow-up communication easier if they can tell us what error they got. 
Vague messages causes speculation and the users tend to get a wrong idea of why something went wrong.
But this is just an opinion, we could start by just logging the correct errors in console (using `response.json`).

Errors from this service should be few or none at all.
Besides connection issues with mailchimp and belga, the only other errors can come from user mistakes:
- trying to send a mailcampaign with no Nota's selected (f.e. EP agenda with 1 announcement)
- trying to send a mailcampaign when there are no themes selected on Nota's
We could translate the errors in the specific cases but maybe not worth the effort.

2022-03-16 09:47 UTC, ValenberghsSven commented on app/components/newsletter/newsletter-header-overview.js
> +            yield this.args.meeting.belongsTo('mailCampaign').reload(); // TODO Why?
Regarding this TODO.
This was probably a fix in some cases, hard to tell what the exact reason/cause was.
I vaguely remember issues where `meeting` did not get updated locally with the `mail-campaign` and in some cases a `meeting.save()` happened later, deleting the relation between mail-campaign and meeting.

2022-03-17 15:38 UTC, ValenberghsSven approved these changes
Errors are logged in console :+1: 

Restored an error message change that was lost in a merge.
Mailchimp fails was showing Belga errors.

Remove the TODO and the reload.
Didn't seem needed in this case.
The fix I mentioned that I once did was the `reload:true` on `findRecord('meeting'`.

2022-03-18 10:24 UTC, merged