KAS-3233 set default size to 50 on pub tables
kanselarij-vlaanderen/frontend-kaleidos pull request #1227
Opened 2022-03-08 14:35 UTC by TaneeG

jira: https://kanselarij.atlassian.net/browse/KAS-3233

2022-03-09 15:03 UTC, erikap requested changes
Er lijkt 1 test te falen die met deze change te maken heeft. Kan je daar eens naar kijken?

2022-03-09 15:43 UTC, ValenberghsSven commented
> Er lijkt 1 test te falen die met deze change te maken heeft. Kan je daar eens naar kijken?

Ik was daar lokaal al even mee bezig
voor die paginatie zit er een test, zal dat snel aanpassen en eens lokaal runnen

2022-03-10 10:49 UTC, erikap approved these changes
De test die nu nog faalt, lijkt mij niets met deze PR te maken te hebben.

2022-03-10 12:27 UTC, ValenberghsSven approved these changes
flakyness op de testsuite ongerelateerd aan deze PR

2022-03-10 12:27 UTC, merged