Feature/kas 3199 regelgevingstype overnemen
kanselarij-vlaanderen/frontend-kaleidos pull request #1232
Opened 2022-03-10 08:14 UTC by TaneeG

jira: https://kanselarij.atlassian.net/browse/KAS-3199

2022-03-10 10:48 UTC, erikap requested changes

2022-03-10 10:48 UTC, erikap commented on app/services/publication-service.js
> +  async setRegulationTypeThroughReferenceDocument(
Aangezien deze method enkel gebruikt wordt in de `Publications::PublicationBatchEditModal` component, zou ik hem daar definiëren ipv op de publication-service. Enkel `referenceDocument` als argument zou ook voldoende moeten zijn. Publication flow kan dan bekomen worden uit `referenceDocument.publicationFlow`, wat een promise is die onmiddellijk zal resolven op dat moment.

2022-03-10 13:41 UTC, ValenberghsSven commented on app/components/publications/batch-documents-publication-modal.js
> +  }
Het mappen van document-type >< regulation-type zou apart kunnen staan van het effectief opslaan van publication-flow.
Je geeft document-type mee als params, en indien die mapt komt er een regulation-type uit.
Die kan je dan meegeven aan de creatie van publicationFlow.

Bij edit check je dan eerst het bestaan van reg-type, method aanroepen indien nodig, en dan een set/save in linkPublicationFlow indien er een reg-type terug kwam.

2022-03-10 13:41 UTC, ValenberghsSven commented on app/components/publications/batch-documents-publication-modal.js
> +
Ben niet echt fan van de PATCH vlak na de POST van publication-flow, we zouden die regulation-type al kunnen weten in de createNewPublication method. De check op het bestaan van regulation-type is overbodig in dat geval.

2022-03-10 14:35 UTC, erikap commented on app/components/publications/batch-documents-publication-modal.js
> +      await publicationFlow.save();
Hier kunnen we nog extra check toevoegen om de save enkel te doen als `getRegulationTypeThroughReferenceDocument` effectief iets teruggeeft.

2022-03-10 15:03 UTC, erikap approved these changes

2022-03-10 22:29 UTC, erikap commented
De test `Decision tests -- should test the decision CRUD` is 2x op rij gefaald. Kan dat iets met deze changes te maken hebben @ValenberghsSven ?

2022-03-11 13:57 UTC, ValenberghsSven commented
> De test `Decision tests -- should test the decision CRUD` is 2x op rij gefaald. Kan dat iets met deze changes te maken hebben @ValenberghsSven ?

Ik kijk ernaar

2022-03-11 15:13 UTC, ValenberghsSven commented
Dit is een nieuwe test, dus vermoed dat die wat flaky is en is ongerelateerd aan deze changes.

2022-03-11 15:14 UTC, ValenberghsSven approved these changes

2022-03-11 15:15 UTC, merged