Feature/kas 3253 wijze pub naar dossier
kanselarij-vlaanderen/frontend-kaleidos pull request #1244
Opened 2022-03-17 09:07 UTC by TaneeG

jira: https://kanselarij.atlassian.net/browse/KAS-3253

2022-03-21 09:14 UTC, erikap requested changes

2022-03-21 09:14 UTC, erikap commented on app/components/publications/publication/publication-activities/publications-info-panel.js
> +      this.args.publicationFlow.save(),
Is deze save nog nodig?

2022-03-21 09:14 UTC, erikap commented on app/components/publications/publication/case/info/publication-case-info-panel.hbs
> +              </div>
De velden kunnen in read- en edit mode best in dezelfde volgorde staan; met 4 op een rij.
Wat mij het meest logische lijkt:
Rij 1: Dringend | Pub nr. | Numac
Rij 2: Datum beslissing | datum ontvangst | Limit pub | Wijze pub

2022-03-22 10:19 UTC, erikap approved these changes

2022-03-22 10:20 UTC, erikap commented
Functioneel is deze PR :+1:  maar linting lijkt nog te falen.

2022-03-22 10:29 UTC, TaneeG commented
> Functioneel is deze PR 👍 maar linting lijkt nog te falen.

Moet nu in orde zijn

2022-03-22 11:49 UTC, ValenberghsSven commented
> > Functioneel is deze PR +1 maar linting lijkt nog te falen.
> 
> Moet nu in orde zijn

https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/development/scripts/pre-commit

2022-03-22 13:31 UTC, erikap approved these changes
Falende test niet gerelateerd aan deze PR

2022-03-22 13:31 UTC, merged