Feature/kas 3309 weergave vertrouwlijkheid
kanselarij-vlaanderen/frontend-kaleidos pull request #1300
Opened 2022-04-20 11:43 UTC by TaneeG

Jira: https://kanselarij.atlassian.net/browse/KAS-3309

2022-04-25 15:30 UTC, MikiDi commented on app/components/agenda/agenda-overview/agenda-overview-item.hbs
> +                    class="{{@agendaitem.formallyOkToShow.classNames}}"
Deze variablen voor klassen hoeven niet tussen quotes. Als het type van `... classNames` `String` is, komt dat vanzelf goed. (Zie idem een paar lijnen hieronder).

2022-04-26 08:03 UTC, ValenberghsSven requested changes

2022-04-26 08:03 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> +                </strong>{{@agendaitem.comment}}
gelijkaardig aan andere PR
een class `auk-u-text-pre-line`  moet op 1 lijn staan, anders komt er extra whitespace bij
Nu start de tekst op een nieuwe lijn
![image](https://user-images.githubusercontent.com/22245223/165250216-0901d969-a5c2-48f5-91f5-741dae621ca7.png)

op usertest ziet het er zo uit:
![image](https://user-images.githubusercontent.com/22245223/165250440-2b5c80ed-7d29-4b32-b7fb-028b087139de.png)

2022-04-26 08:03 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> +                </strong>{{@agendaitem.privateComment}}
zelfde.
Ik vermoed dat dit gaat over prettier formatting, dus ofwel gewoon reverten naar hoe het was of oplossen met `prettier-ignore`.
https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/feature/KAS-3309_Weergave_vertrouwlijkheid/app/components/agenda/printable-agenda/list-section/item-group/item/content.hbs#L11

2022-04-26 08:03 UTC, ValenberghsSven commented on app/pods/agenda/agendaitems/agendaitem/index/template.hbs
> -          data-test-route-agenda---agendaitem-index-confidential
This test selector got removed, but is used in tests.
add this in agendaitem-titles template

2022-04-26 09:58 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> +                </strong>{{@agendaitem.comment}}
terug gezet zoals het was + `{{!prettier-ignore}}`

2022-04-26 09:58 UTC, ValenberghsSven commented on app/pods/agenda/agendaitems/agendaitem/index/template.hbs
> -          data-test-route-agenda---agendaitem-index-confidential
nieuwe selector gemaakt waar nodig

2022-04-26 12:00 UTC, ValenberghsSven commented
Managed to fix tests for now but still waiting on CSS, could we copy some of the needed classes into auk_additions like we did in other PR's?

2022-04-26 16:38 UTC, erikap commented
> Managed to fix tests for now but still waiting on CSS, could we copy some of the needed classes into auk_additions like we did in other PR's?

@brenner-company is going to take over this story in the next sprint

2022-05-03 10:12 UTC, brenner-company commented
Ik geef ook kort even mee dat voor het nieuwe design (vooral qua kleur) ik voor de instances van `Auk::Pill`, die aangepast moesten worden, nu `AuPill` uit Appuniversum gebruik. Qua opmaak en onderhoud leek me dat een pak logischer.

Of we dit ook voor de resterende instances (van `Auk::Pill`) doen zal ik eens later informeren bij de collega devs op het kanselarij-dev kanaal.

2022-05-06 09:21 UTC, brenner-company commented on app/components/agenda/agenda-detail/sidebar-item.hbs
> +              <AuPill @skin="warning" @layout="icon-only" data-test-agenda-detail-sidebar-item-confidential={{true}}>
@erikap Ik ga hier binnen (en in de container) nog een paar kleine aanpassingen doen:
- `vlc-agenda-detail-sidebar__formally-ok-label` (container) een andere (meer duidelijke) classname geven, de padding weg halen en witruimte tussen de pills voorzien.
- `AuPill` heeft geen optie tot `@layout` en binnen Appuniversum componenten lijkt het me nu ook een goed idee om dan ook de iconen binnen Appuniversum te gebruiken.

2022-05-10 12:59 UTC, ValenberghsSven reviewed
@brenner-company Kleine vraag nog op deze.

2022-05-10 12:59 UTC, ValenberghsSven commented on app/components/agenda/agenda-detail/sidebar-item.hbs
> +                      {{t "on-the-website"}}
Dit stond hardcoded "Op de website", ik heb dat aangepast naar een vertaling.
Maar deze tekst staat op het verborgen icoontje.
volgens mij moet dit `{{t "not-visible-in-newsletter"}}` zijn maar ik ken het nieuwe design niet

2022-05-10 20:03 UTC, brenner-company commented on app/components/agenda/agenda-detail/sidebar-item.hbs
> +                      {{t "on-the-website"}}
Klopt, dat zou inderdaad `{{t "not-visible-in-newsletter"}}` moeten zijn. Opgelost binnen onderstaande commit 👍

2022-05-11 06:56 UTC, ValenberghsSven approved these changes
lijkt klaar voor mij

2022-05-11 07:33 UTC, merged