refactor agenda approve API
kanselarij-vlaanderen/frontend-kaleidos pull request #1347
Opened 2022-05-19 11:26 UTC by Annelies-P

2022-05-20 08:24 UTC, erikap commented
Custom Jenkins run http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/230/

2022-05-23 17:47 UTC, erikap approved these changes

2022-06-02 17:01 UTC, ValenberghsSven requested changes
hmmm, gelijkaardig aan de newsletter service toen komen de custom error messages er niet door.
![image](https://user-images.githubusercontent.com/22245223/171682733-218231fd-c1b0-4e07-8f2c-25f3e076bb07.png)

Denk dat dit deels komt door de `catch` portie van de service + verwerking in de frontend `agenda-service.js`


Buiten dat lijkt de est momenteel alles goed te werken na enkele testen.

2022-06-03 14:48 UTC, sergiofenoll commented
Jenkins: http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/245/

Tests were "green", only failing tests were related to outdated backend branch. Started a new pipeline after merging dev into backend branch: http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/246/
but can probably be merged already

2022-06-07 08:13 UTC, erikap commented
Another attempt: http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/247/

2022-06-07 09:43 UTC, ValenberghsSven approved these changes
Errors komen erdoor nu, custom jenkins is wel aant falen op getten van accesslevel ...
ik denk frontend niet helemaal up to date met dev en de backend wel?
Zal zich normaal oplossen met merge

2022-06-07 09:48 UTC, sergiofenoll commented
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/248/

2022-06-07 12:16 UTC, ValenberghsSven commented
jenkins is gefaald, ik vermoed flakyness.
Ik zou de PR er niet voor tegenhouden (lokaal test gerund en ok)

2022-06-07 13:59 UTC, merged