KAS-3342 dynamic mandatee selection based of reference date
kanselarij-vlaanderen/frontend-kaleidos pull request #1356
Opened 2022-05-23 12:28 UTC by MikiDi

successor of https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1323
Gathers shared mandatee-fetching logic in a services and follows a `referenceDate -> governmentBody -> active mandatees`-flow with client-side name-filtering.

Goes with https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/282

2022-05-24 08:46 UTC, erikap approved these changes

2022-05-31 09:58 UTC, ValenberghsSven requested changes
Only 1 place needs changing (the args typo).

The rest are comments and questions.

2022-05-31 09:58 UTC, ValenberghsSven commented on app/components/publications/publication/case/mandatees/mandatees-panel.hbs
> +    @referenceDate={{if @viaCouncilOfMinisters
The correct variable from args is `isViaCouncilOfMinisters`

2022-05-31 09:58 UTC, ValenberghsSven commented on app/components/mandatees/mandatee-selector.js
> + * @argument disabled
Only 1 template uses the `Mandatees::MandateeSelector` and does not pass in `multiple` or `disabled` as args.
So they currently serve no function but I guess we can keep this in for now though. Perhaps we need this later.

But it does mean we can't really test the `multiple` part of the template, so it might not work as expected should we ever need it in the future.

2022-05-31 09:58 UTC, ValenberghsSven commented on app/pods/settings/ministers/controller.js
This was the last piece of actual code in this controller.
Out of scope, but I'm guessing we can just fall back to ember's default empty controller.
We kept most of this code 'in case we enable mandatee editing again'.
I'm pretty sure the current structure of government bodies will be too complex to allow users to do this without extra tooling or help from our part, so just opt the remove the legacy code?
Follow ticket/task is fine so this PR can move.

2022-05-31 09:58 UTC, ValenberghsSven commented on app/services/mandatees.js
> +];
I could argue to have these in config, but they are only used here to this is fine.

2022-05-31 09:58 UTC, ValenberghsSven commented on app/services/mandatees.js
> +    return null;
This one is a bit confusing on a shallow skim of the code.
You would suspect that the filters on `start` and `end` are attributes, but they are relations to `generation` and `invalidation` models that are only defined in backend.

Do we want to document this more clearly? Spent like 10 minutes questioning why this worked ... :sweat_smile: 
Would it make more sense to see `filter[generation]` `filter[invalidation]` `:has-no:invalidation` ?

I was also confused because we do have attributes `mandaat:bindingStart` and `mandaat:bindingEinde` for older `government-bodies` in a migration, but they are never used outside of that migration. I first thought that we are referencing these attributes.

2022-05-31 09:58 UTC, ValenberghsSven commented on app/services/mandatees.js
> +  *fetchMandateesForGovernmentBody(governmentBody, referenceDate=null) {
since we fallback to a `new Date` in `getMandateesActiveOn`, referenceDate would never be null.
Is there a situation where this would be needed? If not, this is just adding dead code?

2022-05-31 10:06 UTC, ValenberghsSven commented
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/239/
New run with testdata zip from backend and fix in cypress commands
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/240/

2022-05-31 12:51 UTC, MikiDi commented on app/services/mandatees.js
> +  *fetchMandateesForGovernmentBody(governmentBody, referenceDate=null) {
> referenceDate would never be null.

Correct. It seemed a valuable addition for the upcoming stories regarding possibilities for more flexible (broader) minister-selection though. `fetchMandateesForGovernmentBody` without specifying a referenceDate can be seen as an "inbetween" compared to "only active ministers"/"áll ministers".

2022-05-31 12:54 UTC, MikiDi commented on app/services/mandatees.js
> +    return null;
It's a naming thing (copied from how it's specified in Themis). Will adapt to `generation` and `invalidation`. :+1:

2022-05-31 12:55 UTC, MikiDi commented on app/pods/settings/ministers/controller.js
I've been thinking this as well. Might as well get it done. Will strip out what's no longer needed/accurate.

2022-05-31 12:56 UTC, MikiDi commented on app/components/mandatees/mandatee-selector.js
> + * @argument disabled
Correct regarding both using and testing. Expect to need them (or at least `multiple`) in the future. Would prefer to keep them for now.

2022-05-31 14:12 UTC, MikiDi commented
added https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1356/commits/34b221570abc84f1602b82e6a78179700b67d29e to avoid race condition where gov bodies attempt loading before visible roles are available

2022-05-31 14:15 UTC, MikiDi commented on app/components/publications/publication/case/mandatees/mandatees-panel.hbs
> +    @referenceDate={{if @viaCouncilOfMinisters
I'm now wondering if the reasoning behind this is even correct to begin with. Don't we always want  `@publicationFlow.agendaItemTreatment.startDate` if it's available, regardless of "via MR" or not? Regardless it's the mandatee in charge on the decision-date that's responsible, no?

2022-05-31 14:27 UTC, MikiDi commented on app/services/mandatees.js
> +    return null;
https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1356/commits/8fd181a7967731418d29b803374e97ceda4d120d

2022-05-31 14:34 UTC, MikiDi commented on app/pods/settings/ministers/controller.js
https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1356/commits/23eb68d6171a259c5f5a8c30b0ba1c5828cd48f7

2022-05-31 14:36 UTC, ValenberghsSven commented on app/services/mandatees.js
> +  *fetchMandateesForGovernmentBody(governmentBody, referenceDate=null) {
So we keep it in, just keep in mind it's untested when implementing it

2022-05-31 16:50 UTC, ValenberghsSven commented on app/components/mandatees/mandatee-selector.js
> + * @argument disabled
:+1:

2022-05-31 18:16 UTC, merged