KAS-3489 add search only on urgent publications option
kanselarij-vlaanderen/frontend-kaleidos pull request #1391
Opened 2022-06-23 10:30 UTC by ValenberghsSven

# :warning: this PR is mutually exclusive with https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1392 :warning: 
Don't merge both

In this PR, Added the option to search on urgent publications only.

Dependent on https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/292

2022-06-24 09:37 UTC, ValenberghsSven commented
Custom jenkins run.
The testdata zip has not been updated yet, so we are still running against the old index.
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/251/

2022-06-24 09:38 UTC, ValenberghsSven commented
clicked the wrong button and closed by accident....

2022-06-24 11:34 UTC, sergiofenoll requested changes

2022-06-24 11:34 UTC, sergiofenoll commented on app/routes/search/publication-flows.js
> +      filter[':terms:urgencyLevelId'] = this.urgencyLevelSpeed.id;
I think the filter here needs to be `:terms:urgencyLevelId.keyword`. Locally, I can't get the search to only return results marked as urgent. After appending `.keyword` to the filter, it does seem to work as expected.

I assume it's related to how Elasticsearch searches string fields. See this conversation in chat for reference: https://chat.semte.ch/channel/mu-semtech?msg=KEHQtfdWyLWEHj7f5

2022-06-24 13:45 UTC, ValenberghsSven commented on app/routes/search/publication-flows.js
> +      filter[':terms:urgencyLevelId'] = this.urgencyLevelSpeed.id;
hmmm, I only changed that near the end, may have missed it.
But then we don't have to use `terms`, `filter['urgencyLevelId'] = this.urgencyLevelSpeed.id;` should work?

2022-06-27 08:28 UTC, sergiofenoll approved these changes

2022-06-27 14:23 UTC, erikap approved these changes

2022-06-27 21:16 UTC, merged