Feature/kas 3667 requested for meeting refactor
kanselarij-vlaanderen/frontend-kaleidos pull request #1498
Opened 2022-10-03 16:36 UTC by ValenberghsSven

Started branch from KAS-3565

Draft for now, checking if anything broke.

http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/309/

2022-10-05 16:09 UTC, erikap requested changes

2022-10-05 16:09 UTC, erikap commented on app/services/agenda-service.js
> +    await subcase.save(); // TODO KAS-3667 do we need to save without requestedForMeeting? maybe for concurrency setting of modified
Can be removed imo

2022-10-05 16:09 UTC, erikap commented on app/services/agenda-service.js
>        await subcase.save();
Can be removed

2022-10-06 14:47 UTC, erikap approved these changes

2022-10-10 08:28 UTC, ValenberghsSven commented
testen falen op een save dat niet gebeurt omdat we die uit de service hebben gehaald.
Ik pas de testen nog even aan

2022-10-11 07:14 UTC, ValenberghsSven commented
3 testen falen omdat de view niet refreshed na indienen van subcase voor een agenda
normaal gefixt in feature/KAS-3612-subcase-views-with-reproposing

2022-10-14 14:20 UTC, merged