KAS-3608: Blocking users, memberships, and organizations
kanselarij-vlaanderen/frontend-kaleidos pull request #1505
Opened 2022-10-13 14:23 UTC by sergiofenoll

https://github.com/kanselarij-vlaanderen/mock-login-service/pull/2
https://github.com/kanselarij-vlaanderen/acmidm-login-service/pull/11
https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/324

2022-10-13 15:15 UTC, sergiofenoll commented on app/styles/addon-overrides/_ember-data-table.scss
> +}
@brenner-company hier de fix om ervoor te zorgen dat de dropdown niet voor een overflow zorgt in een `<DataTable>`.

2022-10-14 12:15 UTC, erikap requested changes

2022-10-14 12:15 UTC, erikap commented on app/controllers/settings/organizations/index.js
> +    await this.organizationBeingBlocked.save();
Should we also unblock all memberships of this organization here?  In that case we probably need a loading state in the modal to inform users system is being busy.

2022-10-14 12:15 UTC, erikap commented on app/templates/settings/users/user.hbs
> +</AuModal>
Can we create a generic/reusable confirmation modal component with `@onCancel` and `@onConfirm` handlers?

2022-10-14 12:15 UTC, erikap commented on app/templates/settings/organizations/index.hbs
> +          <c.body class="hello" as |organization|>
Can be removed? :smiley:

2022-10-14 12:15 UTC, erikap commented on app/templates/settings/organizations/index.hbs
> +            <td class={{if organization.isBlocked "au-u-muted"}}>
Maybe best to include `status` in the model hook?

2022-10-14 12:15 UTC, erikap commented on app/templates/settings/users/index.hbs
> +              <span class="au-u-flex au-u-flex--vertical-center au-u-flex--spaced-small {{if user.isBlocked "au-u-muted"}}">
Maybe best to include `status` in the model hook?

2022-10-14 12:15 UTC, erikap commented on app/templates/settings/users/index.hbs
> +                <div class="au-u-flex au-u-flex--vertical-center au-u-flex--spaced-small {{if membership.isBlocked "au-u-muted"}}">
Maybe best to include `membership.status` in the model hook?

2022-10-14 12:15 UTC, erikap commented on app/templates/settings/users/index.hbs
> +                      {{t "blocked-organization"}}
Wasn't the conclusion of the discussion that organization block results in blocking the membership hence no additional pill required here?

2022-10-14 12:15 UTC, erikap commented on app/templates/settings/users/index.hbs
> +</AuModal>
For maintainability/readability maybe better to extract this modal to a separate component?  Same for the unblock memberships modal.

2022-10-17 10:44 UTC, erikap commented on app/templates/settings/organizations/index.hbs
> +                <AuPill
Indendation not correct

2022-10-17 10:53 UTC, erikap commented on app/controllers/settings/organizations/index.js
> +  }
Maybe easier to use a task with [`maxConcurrency` of ember-concurrency](http://ember-concurrency.com/docs/task-concurrency-advanced) that can be reused for blocking as well as unblocking?

```javascript
@task({ maxConcurrency: 10, enqueue: true }) 
*updateMembershipStatus(membership, status) {
  membership.status = status;
  yield membership.save();
}
```

2022-10-18 10:58 UTC, erikap commented on app/controllers/settings/organizations/index.js
> +    });
Can we reduce duplication here by adding a `*updateOrganizationStatus(organization, status) { ... }` method?

2022-10-18 14:34 UTC, erikap approved these changes

2022-10-19 14:35 UTC, merged