KAS-3607: Filtering users
kanselarij-vlaanderen/frontend-kaleidos pull request #1510
Opened 2022-10-18 14:22 UTC by sergiofenoll

# :warning: This PR merges into #1508 
Either merge this one before merging the parent PR, or change the base branch.

Adds filters for user and organizations overview, as well as the link from the organizations overview to the view with all users for said organization.

2022-10-19 12:48 UTC, erikap requested changes

2022-10-19 12:48 UTC, erikap commented on app/components/organization-filter.js
> +      yield timeout(500);
There is a `LIVE_SEARCH_DEBOUNCE_TIME` defined in `config.js`

2022-10-19 12:48 UTC, erikap commented on app/components/organization-filter.hbs
> +    <PowerSelectMultiple
Why do we use a multiselect if we only handle 1 selected value in `@onChange`?

2022-10-19 12:48 UTC, erikap commented on app/components/user-role-filter.js
> +    this.roles = yield Promise.all([
Why don't we just query all roles with `this.store.query()`? To limit number of requests to the backend? 

Maybe more readable to create a list of roles and map:
```javascript
[ 
  CONSTANTS.USER_ROLES.ADMIN, 
  CONSTANTS.USER_ROLES.SECRETARIE,
  ...
].map((role) => this.store.findRecordByUri('role', role))
```

2022-10-19 12:48 UTC, erikap commented on app/controllers/settings/users/index.js
> +    yield timeout(500);
Will users be able to check multiple checkboxes in this timeframe? If so, use value from `config.js` instead of hardcoded number.

2022-10-19 12:48 UTC, erikap commented on app/routes/settings/organizations/index.js
> +    controller.selectedOrganizations = await Promise.all(organizationIds.map((id) => this.store.findRecord('user-organization', id)));
Page rendering will not be blocked until `setupController` completed. Maybe better to load this in the `afterModel` hook? Or define as a task on the controller that is called from here, such that we can show a loading state in the template for the `OrganizationFilter` component?

2022-10-19 12:48 UTC, erikap commented on app/routes/settings/users/index.js
> +    controller.selectedRoles = await Promise.all(roleIds.map((id) => this.store.findRecord('role', id)));
Page rendering will not be blocked until `setupController` completed. Maybe better to load this in the `afterModel` hook? Or define as a task on the controller that is called from here, such that we can show a loading state in the template for the `OrganizationFilter` and `UserRoleFilter` component?

2022-10-19 12:48 UTC, erikap commented on app/routes/settings/users/index.js
> +    return true;
Nice catch that this was missing :+1: 
Should we use the same loading construct for the organizations table?

2022-10-19 13:10 UTC, sergiofenoll commented on app/components/user-role-filter.js
> +    this.roles = yield Promise.all([
The separate requests are purely to have a set order to the roles. I could also give the roles a `schema:position` in the backend, but I don't know if that holds for all uses.

2022-10-19 13:12 UTC, erikap commented on app/components/user-role-filter.js
> +    this.roles = yield Promise.all([
`schema:position` in backend is fine :+1:

2022-10-19 13:12 UTC, sergiofenoll commented on app/components/organization-filter.hbs
> +    <PowerSelectMultiple
Remnant of the initial implementation where I was just using the Multi PowerSelect (but that looked quite ugly). I'll re-work it to use the single one since that makes the most sense.

2022-10-21 06:33 UTC, erikap approved these changes

2022-10-21 06:33 UTC, merged