KAS-3678: Disable old print routes
kanselarij-vlaanderen/frontend-kaleidos pull request #1522
Opened 2022-10-29 07:36 UTC by sergiofenoll

2022-11-15 11:06 UTC, erikap requested changes
If possible I would like to cleanup the components under `Agenda::PrintableAgenda` a bit in this PR as well. 

Added some comments on specific lines, but in general I would like to simplify the deep nested component structure and only keep components that do have an added value. Imo the components are going to be easier to understand if we just have a flat structure under `Agenda::PrintableAgenda` 

Possible improvements that could not be related to a diff line in this PR:
- `Agenda::PrintableAgenda::ListSection::ItemGroup::Item` is a template-only component that is used in only 1 place hence it can just be embedded
- `Agenda::PrintableAgenda::ListSection::ItemGroup::Item::Content` contains some unnecessary `await`s in the template

2022-11-15 11:06 UTC, erikap commented on app/models/agendaitem.js
>    textPress: attr('string'),
Can we remove these properties. As far is I can see they are currently only used:
- on creation of an agendaitem
- in agendaitem search

Both occurrences can be removed. 

Can you also open a PR on the backend to put the properties in comments there with a note that data is still available in the triplestore.

2022-11-15 11:06 UTC, erikap commented on app/templates/agenda/print.hbs
> +        {{#if (gt this.notaGroups.length 0)}}
Just use `{{#if this.notaGroups}}`

2022-11-15 11:06 UTC, erikap commented on app/templates/agenda/print.hbs
> +          <Agenda::PrintableAgenda::ListSection
I am not so convinced of the usefulness of this template-only component. Can we just embed the HTML here?

2022-11-15 11:06 UTC, erikap commented on app/templates/agenda/print.hbs
> +        {{#if (gt @model.announcements.length 0)}}
Just use `{{#if @model.announcements}}`

2022-11-15 11:06 UTC, erikap commented on app/controllers/agenda/print.js
> +  get notaGroups() {
Can you have a look whether we can use `groupAgendaitemsOnGroupName` of the `agenda-service` here?

2022-11-15 11:06 UTC, erikap commented on app/components/agenda/printable-agenda/list-section/item-group.hbs
> +                <br />&
Remove `&`

2022-11-15 11:06 UTC, erikap commented on app/components/agenda/printable-agenda/list-section/item-group.hbs
> +      {{#let this.items.first.sortedMandatees as |mandatees|}}
Can we replace the `this.items.first` and `this.items.remainder` that is defined on the component with template-helpers like for example [drop](https://github.com/DockYard/ember-composable-helpers#drop)?

2022-11-15 13:54 UTC, ValenberghsSven commented on app/components/agenda/printable-agenda/list-section/item-group.hbs
> +                <br />&
Should we? unsure myself.
![image](https://user-images.githubusercontent.com/22245223/201936588-b29b0011-a2d7-40e7-ad88-5f48ae4c8844.png)

2022-11-15 14:13 UTC, ValenberghsSven commented
> Agenda::PrintableAgenda::ListSection::ItemGroup::Item is a template-only component that is used in only 1 place hence it can just be embedded

It is being used in 2 templates. 
templates/agenda/print.hbs
components/agenda/printable-agenda/list-section/item-group.hbs

2022-11-17 17:02 UTC, sergiofenoll commented on app/controllers/agenda/print.js
> +  get notaGroups() {
That would require a bit fiddling with the rest of the components + given that `groupAgendaitemsOnGroupsName` is an async function, getting that to output correctly through the `notaGroups` getter doesn't really work. You just get a promise and it looks like Ember doesn't pick it up as an array after it resolves (so it doesn't render anything).
Might be that I'm doing something wrong though.

2022-11-18 15:09 UTC, erikap commented on app/controllers/agenda/print.js
> +  get notaGroups() {
Will leave it as it is here, but create a follow up story. Diving deeper in it, it seems there is a lot of overlap in the logic of `agenda.agendaitems` and `agenda.print`. But refactoring the structure of the `agenda` subroutes will lead us to far in this PR.

2022-11-18 15:10 UTC, erikap commented
Failing test not related to this PR. Going to merge.

2022-11-18 15:10 UTC, merged