KAS-3768 Strikethrough en underline niet zichtbaar buiten de editor
kanselarij-vlaanderen/frontend-kaleidos pull request #1592
Opened 2023-01-09 17:18 UTC by brenner-company

**Tickets binnen Jira:** 
- https://kanselarij.atlassian.net/browse/KAS-3768

2023-01-09 17:41 UTC, brenner-company commented
Voor de reviewer van dienst: ik heb wat bijkomende uitleg over de aanpassingen binnen de ze PR binnen onderstaande link geplaatst. https://kanselarij.atlassian.net/browse/KAS-3768?focusedCommentId=17548

2023-01-16 13:01 UTC, ValenberghsSven requested changes
Er zijn nog componenten die niet in orde zijn.
Klad en definitief paginas van KB zijn ok.
De zebra nog niet:
![image](https://user-images.githubusercontent.com/22245223/212684034-7a660ae6-7b59-4550-879f-dbe71ba90565.png)

en ook agendapunt detail
![image](https://user-images.githubusercontent.com/22245223/212684150-0f3d282a-e784-4a9a-8bf2-e66d80cd158b.png)

2023-01-16 13:16 UTC, brenner-company commented
@ValenberghsSven Juist, die komen daar ook voor. Bedankt om het melden!

2023-01-18 16:56 UTC, brenner-company commented
@ValenberghsSven Resterende gevallen zijn nu ook aangepast alsook nog één voorval binnen zoekpagina van Kort bestek.

2023-01-19 19:35 UTC, brenner-company commented
@ValenberghsSven Uit de test komt er nog één die faalt, maar ik denk niet dat die gerelateerd is aan mijn aanpassingen 🤞

2023-01-23 13:38 UTC, ValenberghsSven approved these changes

2023-01-23 13:38 UTC, merged