Feature/kas 3382 capteren weergeven goedkeuringsdatum agenda
kanselarij-vlaanderen/frontend-kaleidos pull request #1704
Opened 2023-04-06 08:57 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-3382

- [ ] merge https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/388
- [ ] merge https://github.com/kanselarij-vlaanderen/agenda-approve-service/pull/37

2023-04-11 15:47 UTC, sergiofenoll requested changes
Voor deze PR moeten we ook Yggdrasil uitbreiden, zodat deze activiteit mee gepropageerd worden. Bespreken we anders morgen tijdens/net na de standup?

2023-04-11 15:47 UTC, sergiofenoll commented on app/components/agenda/side-nav.js
Deze approach is oké, maar je moet het sowieso uitbreiden. Momenteel gebruik je de agenda-status-activity enkel bij het tonen van de status van de laatste agenda versie (lijn 68 in de template), maar het is ook nodig voor alle voorgaande agenda versies (lijn 125 van de template).

Je moet dus per agenda de laatste status activiteit kunnen opvragen. Een mogelijke oplossing is om hier een helper toe te voegen die de logica toepast, bv.

```js
getLatestAgendaStatusActivity = (agenda) => {
  // Logica uit de loadData() task
}
```

Een andere optie is om een change te maken in het model van agenda (`app/models/agenda.js`) en daar een getter toevoegen die de laatste status activiteit returnt, bv.:
```js
get latestAgendaStatusActivity() {
  return this.agendaStatusActivities.sortBy('startDate').firstObject;
}
```
(Merk op dat de `sortBy` functie en de `firstObject` member geen native built-in functies zijn van JS, maar uitbreidingen van het Ember framework https://api.emberjs.com/ember/release/classes/EmberArray)

2023-04-11 15:47 UTC, sergiofenoll commented on app/components/agenda/side-nav.hbs
> +                {{else if this.mostRecentStatusActivityIsApproved}}
Dit moet ook toegepast worden op de andere agenda versies, niet enkel de laatste.

2023-04-20 14:48 UTC, ValenberghsSven approved these changes
Code seems good, need to verify cypress tests are good
Did make some changes (avoid getting/loading relation since it can become stale + it can be saved/overwritten once loaded)

2023-04-21 07:50 UTC, sergiofenoll approved these changes

2023-04-21 13:14 UTC, ValenberghsSven commented
only 1 test failed unrelated to agendas

2023-04-21 13:14 UTC, merged