optimalise highlight in title of searchresult
kanselarij-vlaanderen/frontend-kaleidos pull request #1720
Opened 2023-04-24 14:32 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-3965

2023-04-25 13:46 UTC, tdn requested changes

2023-04-25 13:46 UTC, tdn commented on app/routes/search/agendaitems.js
> +    if (agendaitem.highlight.shortTitle[0]?.split(" ").length < agendaitem.attributes.shortTitle?.split(" ").length) {
This doesn't do the proper check, as the `agendaitem.highlight.shortTitle[0]` will still include the ems. To be discussed

2023-04-25 13:46 UTC, tdn commented on app/routes/search/agendaitems.js
> +    if (agendaitem.highlight.shortTitle[0]?.split(" ").length < agendaitem.attributes.shortTitle?.split(" ").length) {
oh wait, nevermind. It's the length of the split array that's checked here, which will work

2023-04-25 13:46 UTC, tdn commented on app/routes/search/agendaitems.js
> +    if (agendaitem.highlight.shortTitle[0]?.split(" ").length < agendaitem.attributes.shortTitle?.split(" ").length) {
test is likely failing here when `agendaitem.highlight` is `null`, and/or when `agendaitem.highlight.shortTitle` is falsy (undefined or null). 

Pretty sure `agendaitem.highlight.shortTitle` is always an Array when it's not null, but can't hurt to check either.

@StuyckRuben remember to not always go by the happy flow. Always try to break your own code ;-)

2023-05-04 12:21 UTC, ValenberghsSven reviewed
do we want to check all highlights?
Now we only check the first one.
So not all hits are highlighted.


![image](https://user-images.githubusercontent.com/22245223/236202285-db36b5ad-12cc-4c96-a40d-0a45fab6e1a3.png)

The data: 
![image](https://user-images.githubusercontent.com/22245223/236202475-96db9bde-16ec-4e0e-8a8c-df5ef251bc7d.png)

2023-05-04 12:39 UTC, ValenberghsSven commented
Other than the "issue" mentioned above it seems fine.
Searching on other fields (like mandatee) without highlights in titles works (no errors)

2023-05-16 15:39 UTC, tdn requested changes

2023-05-16 15:39 UTC, tdn commented on app/routes/search/agendaitems.js
> +      entry.shortTitle = agendaitem.attributes.shortTitle.replace(highlightShortTitleEmsRemoved, agendaitem.highlight.shortTitle[0]);
change this to `replaceAll` and Sven's comment should be addressed

2023-05-17 12:12 UTC, tdn commented on app/routes/search/agendaitems.js
> +      entry.shortTitle = agendaitem.attributes.shortTitle.replace(highlightShortTitleEmsRemoved, agendaitem.highlight.shortTitle[0]);
correction: this should be in a for loop, since we're replacing the whole highlight snippet

2023-05-17 12:32 UTC, tdn approved these changes

2023-05-17 12:32 UTC, merged