Replace created date from piece when replacing the file
kanselarij-vlaanderen/frontend-kaleidos pull request #1729
Opened 2023-04-28 07:07 UTC by StuyckRuben

2023-05-03 12:48 UTC, ValenberghsSven reviewed
not mentioned in ticket, but there is a replace in document viewer aswell.
https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/development/app/components/documents/document-details-panel.js#L72

2023-05-16 15:32 UTC, tdn commented
@StuyckRuben see Sven's comment. Can you do this for the replace in the document-details-panel as well please?

2023-05-17 13:52 UTC, tdn requested changes

2023-05-17 13:52 UTC, tdn commented on app/components/documents/document-details-panel.js
> +    this.args.piece.created = now;
@StuyckRuben I think these 2 lines belongs inside the `if (this.replacementSourceFile) `, before the `yield this.args.piece.save();` on line 73.

Likely this is also the cause of the failing test

2023-05-24 14:14 UTC, ValenberghsSven approved these changes

2023-05-24 14:14 UTC, merged