Feature/kas 4102 tweak signatures tab
kanselarij-vlaanderen/frontend-kaleidos pull request #1752
Opened 2023-05-17 07:21 UTC by sergiofenoll

https://kanselarij.atlassian.net/browse/KAS-4102

Updates the layout of the signatures overview

2023-05-22 14:31 UTC, ValenberghsSven requested changes
Small points:

1. ongoing.hbs still has `{{page-title (t "ongoing")}}`, needs to be "follow-up"?
2. The name in router.js is still "wordt-verwerkt". Needs changing?
3. the index route has no name. Does that need to be "handtekeningen/op-te-starten" or not? It made sense not to give it a name when there was only 1 subroute.
4. Button that does nothing (but looks the same like the normal one)

2023-05-22 14:31 UTC, ValenberghsSven commented on app/templates/signatures/ongoing.hbs
> +        <td class="au-u-flex au-u-flex--spaced-tiny">
the flex here messes with the rows for me.
![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22245223/559b3e64-5c90-49f3-8837-04600cf45d32)
Longer titles mean a large column size, but lots of whitespace
![Uploading image.png…]()

2023-05-22 14:31 UTC, ValenberghsSven commented on app/templates/signatures/ongoing.hbs
> +              {{t "open"}}
Is this a placeholder?
Avoid buttons that do nothing.
Perhaps a different button icon & tooltip to indicate the link to signinghub is not working (maybe you have no rights or it got removed from signinghub)

2023-05-22 14:31 UTC, ValenberghsSven commented on app/controllers/signatures/ongoing.js
> +    return persons.map((person) => person.fullName);
I think this is right? For agenda it makes sense to show them based on priority.
For signatures, is the `requestBy` more important or not? Leave as-is for now.

2023-05-22 14:34 UTC, ValenberghsSven commented on app/templates/signatures/ongoing.hbs
> +        <td class="au-u-flex au-u-flex--spaced-tiny">
with pill
![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22245223/b15c5402-b06f-4c04-8679-eba7d4121699)

2023-05-24 15:46 UTC, ValenberghsSven commented on app/templates/signatures/ongoing.hbs
> +              {{t "open"}}
I changed the icon to a "broken-link".

2023-05-25 08:23 UTC, ValenberghsSven commented on app/templates/signatures/ongoing.hbs
> +        <td class="au-u-flex au-u-flex--spaced-tiny">
removed the flex from the column, looks better

2023-05-25 08:35 UTC, ValenberghsSven commented
> Small points:
> 
>     1. ongoing.hbs still has `{{page-title (t "ongoing")}}`, needs to be "follow-up"?
> 
>     2. The name in router.js is still "wordt-verwerkt". Needs changing?
> 
>     3. the index route has no name. Does that need to be "handtekeningen/op-te-starten" or not? It made sense not to give it a name when there was only 1 subroute.
> 
>     4. Button that does nothing (but looks the same like the normal one)

1. changed it (checked prototype)
2. changed it
3. added dutch name for index to `router.js`
4. changed the icon so it's different from the actual link

2023-05-25 10:42 UTC, ValenberghsSven approved these changes
Despite my own minor changes the main work is good

2023-05-25 14:21 UTC, merged

2023-05-25 14:21 UTC, tdn approved these changes
Approving this, since we'll have to elaborate on this view in the future anyway