Feature/kas 4124 abbreviated reviewer address
kanselarij-vlaanderen/frontend-kaleidos pull request #1776
Opened 2023-06-14 14:03 UTC by sergiofenoll

Uses the `Auk::AbbreviatedText` component as recommended by Sven to cut off long email addresses of reviewers and notifications. Also changes the validation to no longer take into account length, or rather only check for the true max length of emails as defined in the pretinent RFCs: https://www.rfc-editor.org/errata/eid1690

Validation no longer uses inputmask because adapting the mask is really annoying and does not work as expected (it looks regex-y, but it doesn't really work as expected and you seemingly can't escape characters as you would in a normal regex engine).

Cfr. inputmask's default email mask: https://robinherbots.github.io/Inputmask/#/documentation#dynamic-masks
```
//email mask
  $(selector).inputmask({
    mask: "*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,2}]",
    greedy: false,
    onBeforePaste: function (pastedValue, opts) {
      pastedValue = pastedValue.toLowerCase();
      return pastedValue.replace("mailto:", "");
    },
    definitions: {
      '*': {
        validator: "[0-9A-Za-z!#$%&'*+/=?^_`{|}~\-]",
        casing: "lower"
      }
    }
  });
```

2023-06-16 14:29 UTC, ValenberghsSven requested changes

2023-06-16 14:29 UTC, ValenberghsSven commented on app/components/signatures/email-modal.js
> +      && /.+\@.+\..+/.test(this.emailBuffer);
Unnecessary escape character: \@.eslint[no-useless-escape](https://eslint.org/docs/rules/no-useless-escape) op deze lijn

2023-06-16 14:30 UTC, sergiofenoll commented on app/components/signatures/email-modal.js
> +      && /.+\@.+\..+/.test(this.emailBuffer);
Ah shit, ik heb de pre-commit git hook niet geënabled op mijn laptop, sorry :disappointed:

2023-06-19 15:10 UTC, ValenberghsSven approved these changes

2023-06-19 15:11 UTC, merged