added archiveLink in file model and changed download link in agenda-a…
kanselarij-vlaanderen/frontend-kaleidos pull request #1799
Opened 2023-06-30 07:08 UTC by StuyckRuben

…ctions
https://kanselarij.atlassian.net/browse/KAS-3939

2023-07-04 14:00 UTC, sergiofenoll requested changes
Undo these changes. Given the backend changes, the archive will still come from the regular file service and thus doesn't need a different download link.

2023-07-04 14:00 UTC, sergiofenoll commented on app/components/agenda/agenda-header/agenda-actions.js
> +          fileDownloadToast.options.archiveLink = url;
These changes won't work. This here is using the `Utils::Toaster::DownloadFileToast` component, which expects the field to be called `downloadLink`.

2023-07-05 14:34 UTC, ValenberghsSven commented
no changes needed to frontend with new (better) approach

2023-07-06 07:01 UTC, sergiofenoll approved these changes

2023-07-06 12:36 UTC, ValenberghsSven commented
nothing to merge, not pushing commits

2023-07-06 12:36 UTC, closed without merging