SignaturePill now conform except for signed pill
kanselarij-vlaanderen/frontend-kaleidos pull request #1850
Opened 2023-08-04 08:23 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-4215

2023-08-10 14:09 UTC, ValenberghsSven requested changes

2023-08-10 14:09 UTC, ValenberghsSven commented on app/components/signature-pill.js
> +    if (statusUri === REFUSED || statusUri === CANCELED || statusUri === SIGNED || !signingHubUrl) {
Initial thought:
Should we make this similar to code used below?
`if ([REFUSED, SIGNED, CANCELED].includes(this.data?.value?.status?.uri) || !signingHubUrl) {`

After closer inspection:
Do we even need to check the status uri here?
In the loading of the data, we already check for these 3 statuses (+ MARKED) and we don't load the `signingHubUrl` if any of those 4 statussen are active.
So checking status again doesn't really make sense.
Also, in the case of `MARKED` the pill should be clickable because we have a route that leads to `signatures.index` in that case (even though it might not show up in that list yet because of constraints)

So a clickable pill should be when there is a `this.data?.value?.route` or a `this.data?.value?.signingHubUrl`

2023-08-10 14:09 UTC, ValenberghsSven commented on app/components/signature-pill.js
> +    return 'link';
when we have a link, we should have the skin link? (`"link"` is blue, `"default"` is grey)
So we need to show the blue link when we have a signingHubUrl or the route to signatures?

```
 const route = this.data.value?.route;
 
 .....
 
else if (signingHubUrl || route) {
   return 'link';
```

2023-08-10 14:09 UTC, ValenberghsSven commented on app/components/signature-pill.js
> +    return 'link';
Also, the css class `au-c-pill--link` shows a hover with a pointer. `au-c-pill-default` does not.

2023-08-14 07:14 UTC, tdn approved these changes

2023-08-14 07:14 UTC, tdn commented on app/components/signature-pill.js
> +    return true;
I always get a bell ringing in my head when a `true` or `false` is returned after an `if` statement:

In my opinion, it's cleaner to return the condition as a boolean directly then. In this case: 
```
return signingHubUrl && statusUri !== REFUSED && statusUri !== CANCELED && statusUri !== SIGNED; 
```

2023-08-14 14:39 UTC, ValenberghsSven approved these changes
Made some small changes.
Template had an `or` with only 1 value.
changed the `if x or y return true else false` to `return !!x || !!y`

2023-08-14 14:49 UTC, merged