Generate minutes - feedback secretarie
kanselarij-vlaanderen/frontend-kaleidos pull request #1892
Opened 2023-09-19 12:38 UTC by StuyckRuben

on updating secretary, piece-part for minutes mentioning secretary will update secretary
https://kanselarij.atlassian.net/browse/KAS-4303

- [ ] merge https://github.com/kanselarij-vlaanderen/decision-report-generation-service/pull/4

2023-10-10 15:26 UTC, sergiofenoll requested changes

2023-10-10 15:26 UTC, sergiofenoll commented on app/controllers/agenda/agendaitems/agendaitem/index.js
**question**: why do we need these changes?

This is the controller for the agendaitem route, i.e. we're editing a specific agendaitem. The bulk of the changes occur in the `saveSecretary` action which deals with editing the secretary for said agendaitem/decision-activity.

I don't think we want to update the minutes of the meeting when editing a single agenditem's secretary. I am fairly certain that should only happen when the meeting's secretary changes.

2023-10-10 15:26 UTC, sergiofenoll commented on app/components/meeting/edit-meeting-modal.js
> -    if (this.enableDigitalAgenda) {
**question**: is moving this whole block outside of the feature flag intentional?

2023-10-10 15:26 UTC, sergiofenoll commented on app/components/meeting/edit-meeting-modal.js
> +    if (this.args.meeting.secretary != this.secretary) {
**chore**: compare URIs, not objects

2023-10-10 15:26 UTC, sergiofenoll commented on app/components/meeting/edit-meeting-modal.js
> +      }
**chore**: undo these changes

The feature to re-generate the minutes when changing the secretary was already added in https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1887, let's remove the changes here so we don't implement the same thing twice.

2023-10-11 09:55 UTC, sergiofenoll commented on app/controllers/agenda/minutes.js
> +        mededelingOrNota: capitalizeFirstLetter(mededelingOrNota)
**chore**: don't call `capitalizeFirstLetter` here

The string ends up looking like this: `De Vlaamse Regering neemt akte van Deze mededeling.`

2023-10-12 15:18 UTC, ValenberghsSven approved these changes
reviewed, changed code with Tom and tested

2023-10-12 15:18 UTC, merged