add message to beslissing piece-part when agendaitem is retracted or …
kanselarij-vlaanderen/frontend-kaleidos pull request #1902
Opened 2023-10-04 10:30 UTC by StuyckRuben

…postponed
https://kanselarij.atlassian.net/browse/KAS-4331

2023-10-09 14:03 UTC, sergiofenoll requested changes
You also need to implement this behaviour for when you change the decision result in the pill in the decisions tab.

![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22411874/177e7dbc-036f-4bf8-b7fb-119f0d4d5168)


```js
// example code
// app/components/agenda/gendaitem/agendaitem-decision.js in onDecisionEdit

if (!this.report || !this.beslissingPiecePart) {
  return;
}

let newBeslissingValue = this.beslissingPiecePart.value;
const decisionResultCode = await this.args.decisionActivity
  .decisionResultCode;
switch (decisionResultCode.uri) {
  case CONSTANTS.DECISION_RESULT_CODE_URIS.UITGESTELD:
    newBeslissingValue = this.intl.t('postponed-item-decision');
    break;
  case CONSTANTS.DECISION_RESULT_CODE_URIS.INGETROKKEN:
    newBeslissingValue = this.intl.t('retracted-item-decision');
    break;
  default:
    break;
}
if (newBeslissingValue !== this.beslissingPiecePart.value) {
  const now = new Date();
  const newBeslissingPiecePart = await this.store.createRecord('piece-part', {
    title: 'Beslissing',
    value: newBeslissingValue,
    report: this.report,
    previousPiecePart: this.beslissingPiecePart,
    created: now,
  });
  await newBeslissingPiecePart.save();
  await this.decisionReportGeneration.generateReplacementReport.perform(
    this.report
  );
}
this.loadBeslissingPiecePart.perform();
```

2023-10-09 14:03 UTC, sergiofenoll commented on app/components/agenda/agendaitem/agendaitem-controls.js
> +    const report = yield this.store.query('report', {
**issue**: replace `this.store.query` with `this.store.queryOne`

[`Store.query`](https://api.emberjs.com/ember-data/4.8/classes/Store/methods/query?anchor=query) returns a promise that resolves to an array. Here `report` is actually an array that contains a single report, down the line you do `report.id` which won't work because the array has no id.

We have a custom [`queryOne`](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/development/app/services/store.js#L8-L18) method that automatically unpacks the array when you expect a single record.

2023-10-13 13:26 UTC, ValenberghsSven commented
I'm guessing that we also have to do this if the first creation happens when the decision is already "uitgesteld".
Now it only happens when there is already a generated report, which may not be the case.
Doing this now

2023-10-13 13:57 UTC, ValenberghsSven approved these changes

2023-10-13 13:57 UTC, merged