decision-activity status approved after making decision-activity
kanselarij-vlaanderen/frontend-kaleidos pull request #1907
Opened 2023-10-11 11:08 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-4289

2023-10-11 12:10 UTC, sergiofenoll commented
**question**: no decision result code for announcements, is this intended?

If we go through with the current changes all new agendaitems will have no decision result code until a report is created. But for announcements reports generally aren't generated, which means that users would have to create a report, save it and then delete it have the result code set to "Akte genomen". Is this intentional, or should we instead keep the current behaviour for announcements and only add in the behaviour for new notas? @tdn

2023-10-16 10:24 UTC, tdn commented on app/components/agenda/agendaitem/agendaitem-decision.js
> +    if (!report.id) {
Probably better to check for existence of decisionResultCode instead. Otherwise decisions might get overwritten when saving a report

2023-10-16 10:25 UTC, tdn commented
> **question**: no decision result code for announcements, is this intended?
> 
> If we go through with the current changes all new agendaitems will have no decision result code until a report is created. But for announcements reports generally aren't generated, which means that users would have to create a report, save it and then delete it have the result code set to "Akte genomen". Is this intentional, or should we instead keep the current behaviour for announcements and only add in the behaviour for new notas? @tdn

Indeed. Announcements were not part of the ticket and still must have "Akte genomen"

2023-10-16 10:29 UTC, ValenberghsSven requested changes

2023-10-16 10:29 UTC, ValenberghsSven commented on app/services/agenda-service.js
> -
announcement has to stay `KENNISNAME`
Not setting `GOEDGEKEURD` should be be behind feature flag (maybe, users might want this now? feature flag for now)

2023-10-16 10:29 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-decision.js
> +    if (!report.id) {
not having a report id means new file?.
only set `decisionActivity.decisionresultCode` when none exists might be better if a result code was already set manually.

2023-10-16 13:48 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-decision.js
> +    if (decisionResultCode) {
reverse if, only if there no decisionResultCode yet.

2023-10-16 13:48 UTC, ValenberghsSven commented on Dockerfile
> +ENV EMBER_ENABLE_DECISION_GOEDGEKEURD=""
I did mean the existing `digital_agenda` flag, I could have been more precise.

2023-10-16 13:48 UTC, ValenberghsSven commented on app/services/agenda-service.js
> +    }
suggestion
```
} else {
  defaultDecisionResultCodeUri = this.enableDigitalAgenda ? null : CONSTANTS.DECISION_RESULT_CODE_URIS.GOEDGEKEURD;
}
```

2023-10-18 11:10 UTC, tdn approved these changes

2023-10-18 11:10 UTC, ValenberghsSven approved these changes
approved for now. Wait for cypress in case any test fails on missing decision result.

2023-10-19 09:16 UTC, merged