Feature/kas 4372 document card toon file created date en nooit piece created date updaten
kanselarij-vlaanderen/frontend-kaleidos pull request #1969
Opened 2023-12-05 13:20 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-4372

2023-12-18 17:20 UTC, SchrodingersCat00 requested changes
Suggested some minor changes

2023-12-18 17:20 UTC, kobemertens commented on app/components/agenda/agenda-header/agenda-version-actions.hbs
> +                    {{or (datetime-at piece.file.created) (datetime-at piece.created)}}
Why not `datetime-at (or piece.file.created piece.created)`?

2023-12-18 17:20 UTC, kobemertens commented on app/components/documents/document-card.hbs
> +                    {{or (datetime-at this.piece.signedPieceCopy.file.created) (datetime-at this.piece.signedPieceCopy.created)}}
Same here

2023-12-18 17:20 UTC, kobemertens commented on app/components/documents/document-card/edit-modal.hbs
> +            {{or (datetime-at @piece.file.created) (datetime-at @piece.created)}}
Same

2023-12-18 17:20 UTC, kobemertens commented on app/components/documents/document-preview/version-card.hbs
> +          {{or (datetime-at @piece.file.created) (datetime-at @piece.created) "-"}}
same

2023-12-18 17:20 UTC, kobemertens commented on app/components/documents/linked-document-link.hbs
> +                {{or (datetime-at this.lastPiece.file.created) (datetime-at this.lastpiece.created)}}
same

2023-12-18 17:20 UTC, kobemertens commented on app/components/documents/linked-document-link.hbs
> +                      {{or (datetime-at piece.file.created) (datetime-at piece.created)}}
same

2023-12-18 17:20 UTC, SchrodingersCat00 commented on app/components/documents/document-card/edit-modal.js
> +    this.router.refresh('agenda.agendaitems.agendaitem.documents');
Refreshing a specific route from a component is a bad idea, we can't make any assumptions about where this component will be used. I would look into a `reload` of the relevant models, or refresh via the `onSave` function in the specific route where the component is used.

2024-01-24 16:29 UTC, ValenberghsSven reviewed
small changes and a question.

2024-01-24 16:29 UTC, ValenberghsSven commented on app/components/documents/document-preview/version-card.hbs
> +          {{datetime-at (or @piece.file.created @piece.created "-")}}
`"-"` outside of the or?
this is now an or with 3 params
The `datetime-at` helper accepts a datetime and an override for the "om" text to show date + time:
`helper(function datetimeAt([datetimeOrString, at = "om"])`
so `{{datetime-at (or @piece.file.created @piece.created) "-"}}`

2024-01-24 16:29 UTC, ValenberghsSven commented on app/components/documents/linked-document-link.hbs
> +                {{datetime-at (or this.lastPiece.file.created this.lastpiece.created)}}
if we have `this.lastPiece.file.created` we enter the if, so the second statement of the `datetime-at (or` will never be used

keep ` {{#if this.lastPiece.created}}` ? if there is a piece.created, we can check if there is a file.created and use that instead

2024-01-24 16:29 UTC, ValenberghsSven commented on app/components/documents/document-card/edit-modal.hbs
> -        {{#if @piece.created}}
keep the if as-is and just prefer piece.file.created if it exists?
Odd are good that if piece has a created that file will have one

2024-01-24 16:29 UTC, ValenberghsSven commented on app/components/documents/document-version-history-item.js
> +    return this.args.piece.modified;
This uses the modified property instead of the `file.created`
The question arises: When to use `piece.modified` and when to use `piece.file.created`
We don't update `piece.modified` when replacing a `piece.file` in the backend services

2024-01-25 16:10 UTC, sergiofenoll commented on app/components/documents/document-preview/version-card.hbs
> +          {{datetime-at (or @piece.file.created @piece.created "-")}}
Hah, when I looked at this during review I assumed the `"-"` was there as a "fallback". If there's no `file.created` nor `piece.created`, show a dash. But this makes a lot more sense, and it's also in-line with the current behaviour. Will change.

2024-01-25 16:17 UTC, sergiofenoll commented on app/components/documents/document-version-history-item.js
> +    return this.args.piece.modified;
This is meant to follow the lines of the `document-card`, where we will always show `piece.modified`  if the piece has been editor (for regular pieces, for pieces with parts we use the part creation time).

I think those two are in line/doing the same thing?

2024-01-29 09:11 UTC, ValenberghsSven approved these changes

2024-01-29 09:12 UTC, merged