KAS-4496: reordering agendaitems now doesnt automatically save after each move + added sum helper
kanselarij-vlaanderen/frontend-kaleidos pull request #2022
Opened 2024-02-08 11:05 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-4496

2024-02-12 09:26 UTC, sergiofenoll requested changes

2024-02-12 09:26 UTC, sergiofenoll commented on app/templates/agenda/agendaitems.hbs
> +        @showReorderButton="true"
```suggestion
        @showReorderButton={{not this.showModifiedOnly}}
```

When we show modified only we don't allow re-ordering (so e.g. we hide the `ChangesAlert` component), if you still click this button while in this state you get stuck: the button becomes greyed out and the alert that has buttons to cancel is not shown.

Better to just hide this button when in a state we don't support.

2024-02-12 09:26 UTC, sergiofenoll commented on app/components/agenda/agenda-overview.hbs
> +  {{#if (and @isEditingOverview this.canMoveAgendaitems)}}
```suggestion
  {{#if this.canMoveAgendaitems}}
```
`this.canMoveAgendaitems` already contains `this.args.isEditingOverview`

2024-02-12 09:26 UTC, sergiofenoll commented on app/components/agenda/agenda-overview.hbs
> +        {{#each this.announcements as |announcement indexitems|}}
```suggestion
        {{#each this.announcements as |announcement indexItems|}}
```
Casing here is different, better to match `camelCasing`

2024-02-12 09:26 UTC, sergiofenoll commented on app/components/agenda/agenda-overview.hbs
>                @isFirst={{eq indexitems 0}}
```suggestion
              @isFirst={{eq indexItems 0}}
```

2024-02-12 09:26 UTC, sergiofenoll commented on app/components/agenda/agenda-overview.hbs
There's a longstanding bug here where when re-ordering in an agenda with notas and announcements, the two lists will get merged. Before it didn't matter because as soon as a user stopped dragging we would save the changes and reset the view, but now it's important to get this working.

Screencast:
[Screencast from 2024-02-12 10-18-52.webm](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22411874/98a3d14f-e176-4ddb-8ed1-d760a3974923)

This seems to be a known thing with the addon we use, see [this part of their README](https://github.com/adopted-ember-addons/ember-sortable/tree/v4.0.3?tab=readme-ov-file#multiple-ember-sortables-renders-simultaneously)

Here we can fix it by passing in an extra `groupName` argument to all the `sortable-group` and `sortable-items` helpers. So e.g.

```hbs
<ul {{sortable-group groupName="notas" onChange=this.setNotas}}>
  {{each ... }}
    <li
      ...
      {{sortable-item
        groupName="notas"
      }}
```

And `announcements` for the announcements bits.

2024-02-16 11:43 UTC, sergiofenoll commented on app/helpers/sum.js
We already include the `ember-math-helpers` dependency that implements a helper with the same name and function, this custom helper can be removed.

https://robbiethewagner.github.io/ember-math-helpers/docs/api/helpers/sum

2024-02-19 12:46 UTC, sergiofenoll commented on app/components/agenda/agenda-overview/agenda-overview-item.hbs
@brenner-company in deze commit heb ik een paar CSS changes gemaakt zodat de selector rechts staat en om ervoor te zorgen dat de aflijning van alle items nog in orde blijft.

- Voeg `auk-o-flex--vertical-center` klasse toe aan wrapper div in `AgendaOverviewItem` om alles op één lijn te centreren
- Bottom margin verwijderen uit `.vlc-agenda-items__subject` (centreren gebeurt nu via de flex property op de parent div)
- Voeg `.auk-u-flex-grow` helper klasse toe en gebruik deze om de selector wrapper zo breed mogelijk te maken

Laat maar weten als dat zo gemerged mag worden of als je liever hebt dat dit anders aangepakt wordt. 

![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22411874/3eee4d08-a8be-4a47-8373-ed4bc5fc4244)

2024-03-01 13:29 UTC, brenner-company commented on app/components/agenda/agenda-overview/agenda-overview-item.hbs
Ziet er top uit ✅

2024-03-04 12:52 UTC, ValenberghsSven requested changes
Going to review this PR and make some changes based on what i've found after a small test:
- changing the order of announcements patches immediately (notas looks ok)
- it looks possible to search and reorder with the filtered items only

possibly more, not mergable as-is

2024-03-05 12:38 UTC, ValenberghsSven approved these changes
Changed:
- Cancel reset local variables
- Search agendaitems not possible when changing order
- Changing order button not possible on typing anything in the search bar
- Removed some unnecessary args
- Announcement dragging no longer saves immediately
- Hide newsletter status while reordering
- Renamed changes alert close > confirm so it made more sense with the added cancel method
- Updated cypress test with moved/renamed selectors

2024-03-08 10:03 UTC, merged