Feature/kas 4493 status op website aanpassen bij mededeling
kanselarij-vlaanderen/frontend-kaleidos pull request #2026
Opened 2024-02-08 15:10 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-4493

2024-02-12 11:33 UTC, sergiofenoll requested changes

2024-02-12 11:33 UTC, sergiofenoll commented on app/components/agenda/agendaitem/agendaitem-decision-edit.js
> +        this.args.onPostponedOrRetracted();
This action will be triggered as soon as a user selects the uitgesteld/ingetrokken decision in the dropdown (i.e. before saving). We only want to trigger the action when saving.

We should handle this outside of this component, you can just add the check to the `onDecisionEdit` task in `AgendaitemDecision`. Get the decision result code there (it's already been saved here) and then just remove the newsletter if needed.

2024-02-12 11:33 UTC, sergiofenoll commented on app/components/agenda/agendaitem/agendaitem-case-panel/agendaitem-case-panel-edit.js
We might need this same logic in the `Subcase::SubcaseTitlesPanel::SubcaseTitlesPanelEdit` component (you can also make subcases/agendaitems confidential there). @tdn is this necessary?

If so, you can base yourself off the following query to find the pertinent agendaitems (from the `agenda-and-subacse-properties-sync` service):
```js
      const agendaitemsOnDesignAgendaToEdit = await this.store.query('agendaitem', {
        'filter[agenda-activity][subcase][:id:]': item.id,
        'filter[agenda][status][:uri:]': CONSTANTS.AGENDA_STATUSSES.DESIGN,
      });
```

2024-02-12 11:33 UTC, sergiofenoll commented on app/components/agenda/agendaitem/agendaitem-case-panel/agendaitem-case-panel-edit.js
Toggling the `inNewsletter` attribute of `this.newsItem` here is fine, the problem is that in this view, the sidebar contains a pill for it (Op de website/Niet op de website). When changing confidentiality, that pill doesn't update because of bad data loading in that component.

I think the simplest route here is to add a `this.router.refresh()` at the end of the save action of this component.

2024-02-19 12:26 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case-panel/agendaitem-case-panel-edit.js
> +    this.router.refresh();
router refresh to update 1 icon in the side bar is very load heavy.
Let me see if I can fix it to update better

2024-02-19 15:15 UTC, ValenberghsSven requested changes
Doing these changes as I'm reviewing.
Will be pushing the updates soon.

We will also might need a change to the `agenda-submission` service.
As we create the announcement newsItem there.
We always default to "true", even if the subcase is already confidential

2024-02-19 15:15 UTC, ValenberghsSven commented on app/components/subcase/subcase-titles-panel/subcase-titles-panel-edit.js
> +    });
This will get all agendaitem versions and return a random one.
Technically fine, you could have postponed subcases but not typically with announcements. 
Also it wouldn't really make sense to change confidentiality very late in the progress.
But we could query for newsletters directly or at least make sure we only get the current latest newsletter

2024-02-19 15:15 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-controls.js
> +      }
missing save?

2024-02-19 15:15 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-decision.js
> +        yield newsItem.save();
If the `inNewsletter` was already on false we don't have to save it.
so `newsItem?.inNewsletter` would be better.
Smaller use case but it could avoid concurrency

2024-02-19 15:15 UTC, ValenberghsSven commented on app/components/subcase/subcase-titles-panel/subcase-titles-panel-edit.js
> +  }
we have 4 copies of the same code. A service call could be beneficial here?

2024-02-19 15:15 UTC, ValenberghsSven commented on app/components/subcase/subcase-titles-panel/subcase-titles-panel-edit.js
> +      yield this.removeFromNewsletter.perform();
bit of insider knowledge. 
The term "newsletter" in terms of the actual model was replaced to "news-Item / newsItem" a while ago.
some routes and services still have the name but used mainly in reference to the entire collection of newsItems for a meeting.
so a "newsletter" has a bunch of "newsItems"
There are still some "incorrect" names floating around, but we should avoid reintroducing more.

2024-02-19 15:24 UTC, ValenberghsSven commented on app/components/subcase/subcase-titles-panel/subcase-titles-panel-edit.js
> +      yield this.removeFromNewsletter.perform();
I changed the duplicate code to a service call in the newsletterService (in favor of a util since utils should not update models imo)
called the method `updateNewsItemVisibility` (technically you could update to true or false here, but in our case we only want to update to false)

2024-02-19 15:30 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case-panel/agendaitem-case-panel-edit.js
> +    this.router.refresh();
Managed to fix this quite easily without a full page refresh

2024-03-01 09:13 UTC, ValenberghsSven approved these changes
pair review with Tom

2024-03-01 09:15 UTC, merged