feature/KAS 4499
kanselarij-vlaanderen/frontend-kaleidos pull request #2028
Opened 2024-02-09 08:32 UTC by SchrodingersCat00

- add view-documents-postponed-and-retracted
- add messages to agenda detail view
- remove log statement
- add warning message to agenda overview
- fix indentation
- add message to subcase-item
- fix indentation
- add message to subcase documents

2024-02-09 08:39 UTC, SchrodingersCat00 commented
A lot of code duplication, not sure if I should refactor. Suggestions welcome

2024-02-12 14:24 UTC, sergiofenoll requested changes

2024-02-12 14:24 UTC, sergiofenoll commented on app/components/agenda/agenda-overview/agenda-overview-item.js
> +      [INGETROKKEN, UITGESTELD].includes(decisionActivityResultCode)
```suggestion
      [INGETROKKEN, UITGESTELD].includes(decisionActivityResultCode.uri)
```

`decisionActivityResultCode` is a record, can't be compared with strings.

2024-02-12 14:24 UTC, sergiofenoll commented on app/components/agenda/agenda-overview/agenda-overview-item.js
`loadDocumentsPublicationStatus` now depends on `loadDecisionActivity` having loaded (because you're using `this.decisionActivity` inside `loadDocumentsPublicationStatus`, which is only set in `loadDecisionActivity`.

`loadDocumentsPublicationStatus` should not be called in the constructor, instead it should be called after `loadDecisionActivity` is done, e.g.:

```js
// in constructor
this.loadDecisionActivity.perform().then(() => this.loadPublicationStatus.perform());

// or

  @task
*loadDecisionActivity() {
  // ...
  this.loadDocumentsPublicationStatus.perform();
}

```

2024-02-12 14:24 UTC, sergiofenoll commented on app/components/subcases/subcase-item.js
> +      [INGETROKKEN, UITGESTELD].includes(decisionActivityResultCode)
Same as above, use `decisionActivityResultCode.uri`

2024-02-12 14:24 UTC, sergiofenoll commented on app/routes/cases/case/subcases/subcase/documents.js
> +      [INGETROKKEN, UITGESTELD].includes(decisionActivityResultCode)
```suggestion
      [INGETROKKEN, UITGESTELD].includes(decisionActivityResultCode.uri)
```

2024-02-12 14:24 UTC, sergiofenoll commented on app/routes/agenda/agendaitems/agendaitem/documents.js
> +      [INGETROKKEN, UITGESTELD].includes(decisionActivityResultCode)
```suggestion
      [INGETROKKEN, UITGESTELD].includes(decisionActivityResultCode.uri)
```

2024-03-08 15:18 UTC, ValenberghsSven approved these changes

2024-03-08 15:18 UTC, ValenberghsSven commented on app/components/agenda/agenda-overview/agenda-overview-item.js
will do option 2

2024-03-08 15:18 UTC, ValenberghsSven commented on app/components/subcases/subcase-item.js
> +      [INGETROKKEN, UITGESTELD].includes(decisionActivityResultCode)
will do

2024-03-08 15:18 UTC, ValenberghsSven commented on app/components/subcases/subcase-item.js
>    }
This if else is different from agenda-overview-item.
In the first if, the logic is revered so profiles without the `view-documents-before-release` enter this if.
All other profiles hit the else so `hasDocumentsToShow` should be true because you want to show the alert
Going to adapt the logic to be more like  `agenda-overview-item.js`

2024-03-08 15:18 UTC, merged