KAS-4598: now updates agendaitem number when changing agendaitemtype
kanselarij-vlaanderen/frontend-kaleidos pull request #2078
Opened 2024-04-05 16:14 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-4598

2024-04-11 13:10 UTC, sergiofenoll requested changes

2024-04-11 13:10 UTC, sergiofenoll commented on app/components/subcase/description-panel/edit.js
> +      sort: 'number'
Needs to be `-number`. Sorting is ascending by default (so 1, 2, 3, ... will be returned). We want the largest number first, so we want to make it descending, using `-`.

See: https://github.com/mu-semtech/mu-cl-resources?tab=readme-ov-file#sorting

2024-04-11 13:10 UTC, sergiofenoll commented on app/components/subcase/description-panel/edit.js
> +      'filter[agenda-activity][subcase][agenda-item-type][:uri:]': agendaitemType.uri,
`'filter[type][:uri:]': agendaitemType.uri` also works and is less heavy on the query.

2024-04-11 13:10 UTC, sergiofenoll commented on app/components/subcase/description-panel/edit.js
> +      await this.recalculateAgendaitemNumber();
Recalculating after the agendaitem has been saved won't always work.

For example: this subcase is a nota with number 7. There are 3 mededelingen on the agenda. When switching the type to mededeling, the query in this function (after fixing it) will find this subcase (as 7 is larger than 3) and set its number to 8.

We need to perform this calculation before saving, or at the very least filter out the current agendaitem when trying to find the number.

2024-05-07 15:09 UTC, ValenberghsSven commented
When changing type, we change the decision name but not the number.
Going to try and fix this quick

2024-05-07 16:56 UTC, ValenberghsSven approved these changes
New number is now also used to generate the new piece name.
Tested locally.
Can merge if jenkins is green

2024-05-08 12:29 UTC, ValenberghsSven commented
only flaky tests are also on dev

2024-05-08 12:29 UTC, merged