Feature/kas 4565 publicatie view binnen dossier
kanselarij-vlaanderen/frontend-kaleidos pull request #2101
Opened 2024-05-06 16:21 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-4565

- [ ] merge https://github.com/kanselarij-vlaanderen/yggdrasil/pull/63

2024-05-28 13:25 UTC, sergiofenoll approved these changes

2024-05-28 13:25 UTC, sergiofenoll commented on app/components/publications/publication/case/info/improved-publication-case-info-panel.hbs
This panel is quite analogous to the sibling `publication-case-info-panel`, but it has a very different implementation. I'd be inclined to move it to a different path (e.g. `components/subcase/publication/case-info-panel`) to reduce potential confusion but it can stay.

2024-05-28 13:25 UTC, sergiofenoll commented on app/components/publications/publication/case/mandatees/mandatees-and-submitter-panel.hbs
This is OK as-is, it's implemented like in usertest, but perhaps we shouldn't duplicate a common visual pattern. This is very similar to `Mandatees::MandateePanel`, if the new design is desired perhaps we should update the existing component and ensure all instances use the new design, instead of having slightly different variations over our app.

Something to be discussed with design, maybe, at some point.

2024-06-18 15:16 UTC, tdn requested changes
Some minor things (see comments).

Most important one is the statuses panel, which doesn't work right now.

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/contact-persons/contact-persons-panel.js
> +    return isPresent(this.args.mayAddContactPerson) ? this.args.mayAddContactPerson : true;
This getter is a bit superfluous. Might be cleaner to flip it around and use `@isEditDisabled` in the template

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/government-areas/government-areas-panel.js
> +    return isPresent(this.args.isEditingAllowed) ? this.args.isEditingAllowed : true;
Same here. use `isEditDisabled` as an argument and use directly in the template without a getter

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/info/improved-publication-case-info-panel.js
> +        this.links.push(link);
if there is no publication yet, these links should not be generated. So best to add a check for publication status around this

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/inscription/inscription-panel.js
> +  get getIsCaseLinkVisible() {
Same here, these getters can be replaced by an argument

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/statuses/publication-statuses-info-panel.js
> +    this.translationActivity = yield publicationSubcase.publicationActivity;
copy paste error? 
`this.translationActivities = yield publicationSubcase.translationActivities;`
Also, this needs `translationSubcase` first.

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/statuses/publication-statuses-info-panel.js
> +    this.proofingActivity = yield publicationSubcase.publicationActivity;
copy paste error?
`this.proofingActivities = yield publicationSubcase.proofingActivities;`
Sort by descending date would be nice as well

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/statuses/publication-statuses-info-panel.hbs
> +          {{#if this.translationActivity}}
This will need to be an `#each this.translationActivities`

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/statuses/publication-statuses-info-panel.hbs
> +          {{#if this.proofingActivity}}
This will need to be an `#each this.proofingActivities`

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/statuses/publication-statuses-info-panel.hbs
> +          {{#if this.publicationActivity}}
This will need to be an `#each this.publicationActivities`

2024-06-18 15:16 UTC, tdn commented on app/components/publications/publication/case/statuses/publication-statuses-info-panel.js
> +    this.publicationActivity = yield publicationSubcase.publicationActivity;
This is an array. So `this.publicationActivities = yield publicationSubcase.publicationActivities;`

2024-06-18 15:16 UTC, tdn commented on translations/nl-be.json
> +  "publication-flow-numac-number-text": "Numac number",
Numac nummer (Nederlands)

2024-06-18 15:18 UTC, tdn commented on app/components/publications/publication/status-pill.hbs
> +{{else}}
Pill should be red (danger) in case of cancellation.

2024-06-28 13:49 UTC, ValenberghsSven approved these changes
Pair reviewed.
Tested locally. minister and government profile can see all needed data.
minister after release decisions
government after release documents

2024-06-28 13:51 UTC, merged