KAS-4652: now shows different message in AgendaGroupHeader if the subcase.type is bekrachtiging
kanselarij-vlaanderen/frontend-kaleidos pull request #2109
Opened 2024-05-21 13:56 UTC by StuyckRuben

2024-05-27 10:36 UTC, sergiofenoll approved these changes
Looks good and works as expected

2024-06-05 14:17 UTC, ValenberghsSven requested changes
not fully ok it seems.
I locally have 2 ratification, but only 1 is shown in the print view
![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22245223/b94d63ce-0301-4188-b17e-9f4b33408d30)
![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22245223/cda9d38b-057e-44cd-941a-1283297b3e70)


There is some logic to include if a ratification subcase does have mandatees but that messes up the print view.
![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22245223/ef741b57-d85b-46e4-8c23-7781ae5e5ed0)
![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/22245223/2dcfcae2-24fe-4e35-a7ed-cf204190181c)

2024-06-05 14:17 UTC, ValenberghsSven commented on app/controllers/agenda/agendaitems.js
> +      });
I get we need the subcase here.
A query is an option.
In the child route agendaitems/agendaitem we also need the subcase.
to get the subcase there we do
```
    this.agendaActivity = await model.agendaActivity;
    this.subcase = await this.agendaActivity?.subcase;
```
this means we are now loading the similar data in 2 ways which will slow down the general loading.
It will be fine locally but with large agendas it could mean 100 extra uncached data calls.
I think anyway. it makes more sense to reuse the same calls (either query or relation calls)

2024-06-05 14:17 UTC, ValenberghsSven commented on app/components/agenda/printable-agenda/list-section/item-group.js
> +    this.isBekrachtiging = subcase?.isBekrachtiging;
`subcase?.isBekrachtiging;` is an sort of sync getter on the modal that uses possible unloaded async data (type)
so we should do `yield subcase?.type;` when we want to use it.

2024-06-05 14:17 UTC, ValenberghsSven commented on app/services/agenda-service.js
> +
This has nothing to do with agenda views.
Is this needed here? Not mentioned in ticket

2024-06-18 13:19 UTC, tdn requested changes
Some small comments left to be resolved. 
Does work nicely already

2024-06-18 13:19 UTC, tdn commented on app/components/agenda/printable-agenda/list-section/item-group.hbs
> +          {{#if this.isBekrachtiging}}
`if (and (eq this.sortedMandateesFromFirst.length 0) (not this.isBekrachtiging))` here as well?

2024-06-18 13:19 UTC, tdn commented on app/services/agenda-service.js
> +
It would seem logical to me, but given Kort Bestek's reluctance to change, and this being a request from secretarie, we might want to leave this out for now

2024-06-18 13:19 UTC, tdn commented on app/components/agenda/printable-agenda/list-section/item-group.hbs
> +          {{#if this.isBekrachtiging}}
Test this by creating 2 ratifications at the end of the agenda. Give the last one 1 or more mandatees, and the mandatee titles should show in the print view. Now it shows "Bekrachtiging en afkondiging" twice.

![image](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/assets/941839/f7c237f9-30ba-4659-9124-3c4d02b521b5)

2024-06-28 14:44 UTC, tdn approved these changes

2024-06-28 14:44 UTC, merged