KAS-4782: Ontbrekende witruimte rond 'empty state' componenten
kanselarij-vlaanderen/frontend-kaleidos pull request #2195
Opened 2024-09-03 17:15 UTC by brenner-company

**Tickets binnen Jira:** 
- https://kanselarij.atlassian.net/browse/KAS-4782

⚠️ Moet op zich niet echt gereviewed worden, maar alle tests moeten wel volledig ok zijn om te weten dat er geen functionele impact is.

2024-10-16 13:57 UTC, ValenberghsSven requested changes
2 van deze lijken niet ok.
Daar is de empty state niet de lengte van de modal.
De rest zag er goed uit.

Ik heb daarnaast nog 1 plaats gevonden waar een bordered helpt in de dossier view als er nog geen procedurestappen zijn toegevoegd.

Willen we een snippet van deze includen in de styleguide voor de emptyState?

2024-10-16 13:57 UTC, ValenberghsSven commented on app/components/cases/subcases/proposable-agendas-modal.hbs
> -          <Auk::EmptyState @message={{t "no-meetings"}} />
![image](https://github.com/user-attachments/assets/bd0925ec-514b-4d59-a107-c674efd2bc5b)

2024-10-16 13:57 UTC, ValenberghsSven commented on app/components/cases/submissions/proposable-agendas-modal.hbs
> -          <Auk::EmptyState @message={{t "no-meetings"}} />
![image](https://github.com/user-attachments/assets/d4929694-45f6-401d-889d-a2e3735b6431)

2024-10-17 10:49 UTC, brenner-company commented
> @brenner-company 2 van deze lijken niet ok. Daar is de empty state niet de lengte van de modal. De rest zag er goed uit.

Aangepast ✅

> Ik heb daarnaast nog 1 plaats gevonden waar een bordered helpt in de dossier view als er nog geen procedurestappen zijn toegevoegd.

Super, bedankt!

> Willen we een snippet van deze includen in de styleguide voor de emptyState?

Toegevoegd binnen de styleguide ✅

2024-10-17 14:30 UTC, tdn approved these changes
looks fine locally

2024-10-17 14:31 UTC, merged