KAS-4834: Add persagenda view
kanselarij-vlaanderen/frontend-kaleidos pull request #2230
Opened 2024-10-12 08:20 UTC by sergiofenoll

2024-10-12 08:25 UTC, sergiofenoll commented on app/components/agenda/press/list-section/item-group.hbs
This is a copy-paste of `Agenda::PrintableAgenda::ListSection::ItemGroup` with the bits we didn't need removed and replacing the CSS class `l-printable-agenda__subcase-name-indented` with `l-printable-agenda__subcase-name`.

2024-10-12 08:26 UTC, sergiofenoll commented on app/components/agenda/press/list-section/item-group/item/content.hbs
This is a copy-paste of `Agenda::PrintableAgenda::ListSection::ItemGroup::Item::Content` with the bits we didn't need removed and replacing the CSS class so the text wasn't indented.

2024-10-12 08:27 UTC, sergiofenoll commented on app/routes/agenda/press.js
> +  async sortAgendaitems(agendaitems) {
Re-implementation of [the code from the `agenda-submission` service](https://github.com/kanselarij-vlaanderen/agenda-submission-service/blob/main/lib/agendaitem-order.js#L91-L130).

2024-10-16 13:14 UTC, ValenberghsSven requested changes
the ticket mentions:

- een trigger om agenda aan te maken (we now navigate to a view page)
- een automatisch gegenereerde persagenda (als pdf) op basis van de agenda (not done, how are they expecting this agenda? generate a pdf for every press of the action?)
- de mogelijkheid om deze te downloaden  (guessing you can print the page, but I think they wanted to download the pdf from above)
- Deze functie is enkel beschikbaar voor admin & secretarie (not done, everyone can see this, also for kanselarij)

2024-10-16 13:19 UTC, sergiofenoll commented
> the ticket mentions:
> 
>     * een trigger om agenda aan te maken _(we now navigate to a view page)_
> 
>     * een automatisch gegenereerde persagenda (als pdf) op basis van de agenda _(not done, how are they expecting this agenda? generate a pdf for every press of the action?)_

Ticket also links to a Usertest view where none of this is implemented and instead a view like the "printable agenda view" is implemented. Given that the ticket content is just a copy-paste of the Feature Passport from Design, I assumed that the FP was out-of-date with the actual expected implementation from Usertest.
 
>     * de mogelijkheid om deze te downloaden  _(guessing you can print the page, but I think they wanted to download the pdf from above)_

Yes they can just print the page.

>     * Deze functie is enkel beschikbaar voor admin & secretarie _(not done, everyone can see this, also allow kanselarij to view this)_

I forgot about this.

2024-10-16 14:03 UTC, ValenberghsSven commented
@tdn 
Creating a pdf with just the content or printing directly from your browser will be very different.
Browser print contains a lot of data in the header and footer. Has this been checked/verified with the users if this is ok?
For me this works, but then we should update the ticket since Kenny will not be looking at usertest links.

2024-10-17 13:14 UTC, ValenberghsSven approved these changes
fixed small bugs, added permission

2024-10-17 13:15 UTC, tdn approved these changes

2024-10-17 13:17 UTC, merged