KAS-4865: Auk-additions die uit prototype overgebracht zijn overlopen en refactoren/verplaatsen waar nodig
kanselarij-vlaanderen/frontend-kaleidos pull request #2246
Opened 2024-11-11 20:32 UTC by brenner-company

**Tickets binnen Jira:** 
- https://kanselarij.atlassian.net/browse/KAS-4865

⚠️ Moet op zich niet echt gereviewed worden, maar alle tests moeten wel volledig ok zijn om te weten dat er geen functionele impact is.

2024-11-12 15:08 UTC, tdn requested changes

2024-11-12 15:08 UTC, tdn commented on app/components/search/result-cards/agendaitem.hbs
> +        class="au-u-padding-none l-result-card__link"
We rely on this class to avoid double clicks. Will need to be fixed before this can be merged

2024-11-12 15:09 UTC, ValenberghsSven commented on app/components/search/result-cards/agendaitem.hbs
> -        class="au-u-padding-none card-link"
`clickEvent?.target.parentElement.className.indexOf('card-link') > -1

2024-11-12 15:10 UTC, brenner-company commented
Good catch @tdn & @ValenberghsSven. Will fix this!

2024-11-15 17:22 UTC, brenner-company commented
> Good catch @tdn & @ValenberghsSven. Will fix this!

Should be fixed now, but I'll wait for the tests to be completely certain.

2024-11-15 17:27 UTC, brenner-company commented
@ValenberghsSven Can you take a look at the test when you find the time? Keep getting a `ERROR: Error cloning remote repo 'origin'` within Jenkins before the actual tests run.

2024-11-29 14:09 UTC, ValenberghsSven commented on app/controllers/search/agendaitems.js
>          return;
I testes this locally, could it be that this behaviour has changed? (maybe part due to ember upgrade)
What it should do:
When clicking the card you enter the else part, no link was clicked.
When clicking the link inside the card you would transition twice, once with the LinkTo, once with our `router.transitionTo` so you would get double entries in history.
Now however, when debugging both the if and else, I never hit the return in the if statement when clicking the link. But I also don't hit transitionTo. I only hit that when not clicking a link.

Also a possible issue.
When clicking the link in the card we also stopped hitting our plausible tracking event.
The behaviour on ` @onClickRow={{this.resultClicked}}` seems to have changed.
I think this is besides that styling changing here and should be looked at independently

2024-11-29 14:15 UTC, ValenberghsSven approved these changes
I've looked at the style changes, looks ok to me.
The result card thing is not an issue for this PR. Behaviours have changed and that feature needs to be looked at (it actually works better now, but we lose our plausible tracking it seems )

2024-11-29 14:16 UTC, merged