KAS-4897: the great controllers reset
kanselarij-vlaanderen/frontend-kaleidos pull request #2278
Opened 2024-12-20 16:51 UTC by sergiofenoll

https://kanselarij.atlassian.net/browse/KAS-4897

In deze ticket ben ik door alle controllers in de app gegaan en waar mogelijk kleine issues met het resetten van de controllers rechtgezet. Het ging voornamelijk over kleine dingen zoals modals die open bleven staan en `thing = store.createRecord()` die niet verwijderd worden.

Dit laatste doen we ook in componenten en daar zouden we dat ook moeten opkuisen, maar dat is misschien voor een andere ticket.

De eigenlijke issue die in de ticket beschreven werd is in f1209186273159b35c4a79362bd29065b5f7cfee gefixt geweest met (zoals Sven al aangaf in de comments van de ticket) een `reload()`. Eigenlijk is dat ook het enige dat écht gemerged "moet" worden.

2025-01-30 12:22 UTC, ValenberghsSven commented
Avoided this one a bit. 
Tests are failing in this one.
I think some resets are to harsh, where documents that should be saved are actually deleted because of the reset.
Maybe because of a fast user (like cypress).
Perhaps I split this up into "safe" actions like reloads and "dangerous" actions like deleting pieces if we think they are to be removed.
That way, the "safe" actions can start moving while we finetune the "dangerous" ones.

2025-01-30 12:24 UTC, ValenberghsSven requested changes
Avoided this one for a while.
Tests are failing in this one.
I think some resets are to harsh, where documents that should be saved are actually deleted because of the reset.
Maybe because of a fast user (like cypress).
Perhaps I split this up into "safe" actions like reloads and "dangerous" actions like deleting pieces if we think they are to be removed.
That way, the "safe" actions can start moving while we finetune the "dangerous" ones.

Just to get this PR moving a bit

2025-02-11 15:09 UTC, ValenberghsSven reviewed
Made some changes rather than pulling apart the PR.
Any deletes are softened, just trying to cleanup any model without any id.
And in some cases, don't delete the draft-file should that exist.
Because an unsaved BIS of a draft-file should not delete the draft-file.

2025-02-11 15:09 UTC, ValenberghsSven commented on app/routes/agendas.js
> +        controller.newMeeting.deleteRecord();
tested this one:
You create a meeting
You open the meeting > we flag the just created meeting for deletion.
If you were to then change anything on the meeting and try to save you get errors
`Attempted to set 'extraInfo' on the deleted record Meeting:` 
So too aggressive.

Tried finding other scenarios where we do have a meeting "in flux" but can't find any.
You have to cancel to get out of it and canceling cleans up the meeting.
So what do we want to do with this? guessing just no delete here, just clean the controller maybe.

going to remove the deletes for this one.
We created unsaved meeting and publication activities.
So worst case the meeting is still in the controller.

2025-02-11 15:09 UTC, ValenberghsSven commented on app/routes/agenda/documents.js
> +    }
This one never seems to get called.
I can force it by commenting `newPieces = new TrackedArray([])` in the controller methods.
Then we do hit this, but again, we delete the pieces that should remain.
Going to change this so we first verify: "Is there an id? > Don't delete".
That should make it so we only target pieces that are safe to remove and not remove actual pieces.

2025-02-11 15:09 UTC, ValenberghsSven commented on app/routes/signatures/decisions.js
> +
duplicate `resetController`, going to keep the second one

2025-02-11 15:09 UTC, ValenberghsSven commented on app/routes/cases/case/subcases/subcase/new-submission.js
> +    }
same, making it less aggressive.
No ID > `deleteRecord`

2025-02-12 16:03 UTC, ValenberghsSven commented
1 test is failing after changes.
Test does:
- Create meeting MR via modal in agendas
- Create meeting PVV via modal in agendas
But what happens is:
- after the first meeting is created the view is refreshed so setupController happens
- Cypress is faster so we open the modal again before the setupController happened (the button to create is available).
- the modal closes because of the setupController as it sets the `isCreatingNewSession` to false

Can be done locally by using slow network.

I guess that behaviour is ok, it just happens slower then you would think.
Since only 1 spec is affected I will just add a check so we wait for the refresh of the page before continuing.

Just thinking if this use case of "fast users" could have more serious impact in other scenarios.
Since the setup and reset would happen _after_ the user possible did something

2025-02-13 09:58 UTC, ValenberghsSven commented on app/routes/cases/case/subcases/subcase/new-submission.js
> +    }
changed

2025-02-13 09:58 UTC, ValenberghsSven commented on app/routes/signatures/decisions.js
> +
changed

2025-02-13 09:58 UTC, ValenberghsSven commented on app/routes/agenda/documents.js
> +    }
changed

2025-02-13 09:58 UTC, ValenberghsSven commented on app/routes/agendas.js
> +        controller.newMeeting.deleteRecord();
changed

2025-02-13 09:59 UTC, ValenberghsSven commented
Wachten op jenkins groen

2025-02-14 10:41 UTC, tdn approved these changes

2025-02-14 10:41 UTC, merged