Kas 1353
kanselarij-vlaanderen/frontend-kaleidos pull request #269
Opened 2020-03-23 15:08 UTC by ValenberghsSven

2020-03-24 12:21 UTC, BenjaminDendas requested changes
Enkel een linter error, voor de rest heb ik het manueel en via de unit-testen getest en ik zag het verwachtte resultaat

2020-03-24 12:21 UTC, BenjaminDendas commented on app/templates/newsletters.hbs
> +          onClickRow=(action "navigateToNewsletter") as |table|
Linter issue tegen attribute-indentation, as |table| moet op de volgende regel staan 

>  error  Incorrect indentation of block params 'as |table|
>         }}' beginning at L16:C52. Expecting the block params to be at L17:C8.  attribute-indentation
>   17:8  error  Incorrect indentation of close curly braces '}}' for the component '{{data-table}}' beginning at L17:C8. Expected '{{data-table}}' to be at L18:C8.  attribute-indentation

2020-03-24 12:58 UTC, BenjaminDendas approved these changes

2020-03-25 12:34 UTC, woutersf approved these changes

2020-03-25 12:36 UTC, merged