KAS-1363 reduce resizing of agendaitems on setting formallyOk
kanselarij-vlaanderen/frontend-kaleidos pull request #288
Opened 2020-04-02 10:38 UTC by ValenberghsSven

I moved the computed for the document names from the component to the correct model, this also stop the constant calls made to the lazy-loading service with every set of formallyOk.

with local data, there is no more resizing of the divs, just the documents are now "flickering" several times during al the changes.

2020-04-02 13:18 UTC, BenjaminDendas commented
In enkele randgevallen verspringen de agendapunten nog zeer fel. Consistency-wise dient dit dus alsnog herbekeken te worden.
Sidenote: Omwille van deze PR/change zijn er wat onderliggende issues bloot gelegd die aangepakt dienen te worden, hiervoor maken we de nodige bug-tickets aan.

@woutersf 
Ik zou dit tegenhouden omdat dit zoals beschreven in de sidenote, een issue blootlegt wanneer je veel documenten in 1x zou uploaden.

Suggestie: Fixen van de concurrency issue waarna we dit issue kunnen pushen naar development om vervolgens te zien of de verspringingen met relevante (grotere) data zich daar ook voortdoet.

2020-04-02 13:19 UTC, BenjaminDendas requested changes
Stappen springen in sommige use-cases nog steeds zoals besproken met @ValenberghsSven tijdens de gezamelijke review, dit dient herbekeken te worden inclusief de opmerkingen in bovenstaande comment.

2020-04-15 09:07 UTC, woutersf commented
Getest en de document flikker is in elk geval verdraagbaar

2020-04-15 09:08 UTC, woutersf approved these changes
Dit is in ieder geval beter als bestaande. 
Bug met multiple documents is ook apart opgenomen, hoeft de deze dus niet langer te blokkeren.
Getest.

2020-04-20 06:30 UTC, BenjaminDendas approved these changes

2020-04-20 10:19 UTC, ValenberghsSven commented
Ik heb development er nog eens in gemerged want er was een conflict.
De speciale cases waar het toch nog flikkert kan ik lokaal niet reproduceren.
Mogelijk te maken met lokale data ?

2020-04-20 11:54 UTC, merged