KAS-1245: Fix agendaitem spacing
kanselarij-vlaanderen/frontend-kaleidos pull request #310
Opened 2020-04-16 14:42 UTC by rafael-mindreau

# 🐞Bugfix: Approve Agenda

When you approved an agenda, the modal didn't hide. So that made it possible for you to chain-create more and more agenda's. We just hide the modal when now, when you approve an agenda. Much better!

2020-04-17 06:34 UTC, woutersf requested changes
Je had in de test agenda.spec.js
op lijn 34 (na de lijn "approveDesignagenda") 
Een test kunnen toevoegen om te voorkomen dat dit probleem zich nog in de toekomst voordoet.
https://github.com/kanselarij-vlaanderen/kaleidos-frontend/blob/development/cypress/integration/unit/agenda.spec.js#L33
Zou je dit eens kunnen bekijken om hier een kleine check toe te voegen dat de modal neit meer zichtbaar is?

2020-04-20 06:26 UTC, BenjaminDendas commented
> Je had in de test agenda.spec.js
> op lijn 34 (na de lijn "approveDesignagenda")
> Een test kunnen toevoegen om te voorkomen dat dit probleem zich nog in de toekomst voordoet.
> https://github.com/kanselarij-vlaanderen/kaleidos-frontend/blob/development/cypress/integration/unit/agenda.spec.js#L33
> Zou je dit eens kunnen bekijken om hier een kleine check toe te voegen dat de modal neit meer zichtbaar is?

Omdat we deze gepaired hebben, heb ik de test snel aangepast zodat deze check er mee inzit.

2020-04-20 08:19 UTC, woutersf approved these changes

2020-04-20 08:22 UTC, woutersf approved these changes

2020-04-20 09:35 UTC, ValenberghsSven approved these changes

2020-04-20 10:31 UTC, merged