KAS-1455: Fix Document Upload Big
kanselarij-vlaanderen/frontend-kaleidos pull request #311
Opened 2020-04-16 15:15 UTC by rafael-mindreau

# 🐞Bugfix: Clear Upload Document

In decisions for an agendaitem, you can upload new decision forms. When you select a file such that it is visible in the modal, and then cancel the upload so the modal closes, you will see the document again if you click to upload another form. This prevents the user from selecting another file until he/she refreshes.

### 🚑The Fix
I added functionality to clear all documents from the mixin for uploading documents. I made a separate and better named action to close the modal, in which we explicitly clear all documents in the pipeline for potential upload. this makes it so that the modal is cleared when you open it again 👍

2020-04-17 06:24 UTC, woutersf commented on app/components/utils/add-signed-documents/component.js
> +      this.hideAddDocumentModal();
De functie bestond al, maar bevat maar 1 lijn code. 
Ik zou dat dan wegdoen. 
Tenzij ze nog ergens anders zou worden gebruikt, maar dat lijkt me niet het geval.

2020-04-17 06:29 UTC, woutersf requested changes
Code ziet er proper uit. 
Klein opmerkingske toegevoegd.
Was dit stuk al afgetest met een cypress test?
Zou je hier eventueel een klein testje voor kunnen toevoegen? Al is het maar de upload van 1 signed document. Als ik me niet vergis is hier nog geen cypress test voor.

2020-04-17 14:27 UTC, rafael-mindreau commented on app/components/utils/add-signed-documents/component.js
> +      this.hideAddDocumentModal();
I amended some changes! 👍

2020-04-17 14:42 UTC, woutersf approved these changes

2020-04-20 09:46 UTC, ValenberghsSven approved these changes

2020-04-20 12:48 UTC, merged