KAS-1399: Refactor Authentication Mixin
kanselarij-vlaanderen/frontend-kaleidos pull request #324
Opened 2020-04-27 11:17 UTC by rafael-mindreau

# ⚙️ Mixins Refactor: Authentication mixin

⚠️  **Word of warning** - This changes quite a lot of files, and has a potentially great impact on the functionality overall. In this introduction I attempt to share some insights into what could go wrong.

♻️ Tests are running...

## What has changed?

The `is-authenticated-mixin` has been phased out. It was used in 51 files. Thus this change has been very impactful.

### 🗒️ Overview of the mixin

The mixin contained the following key features:
![image](https://user-images.githubusercontent.com/1874332/80363962-58333400-8885-11ea-95af-6ee184aef663.png)

What it does, is basically expose features from the `current-session` service with easy-to-use aliases. However, if you're new to the project, and haven't seen this before, you might easily go and wonder where the hell these come from if you see them popping up in templates. Another thing I found out on the way, is that the places that include this mixin **almost never** fully use all aliases. Most of the time only one alias. In some cases there was even no use at all, due to organic growth of the code and project.

### 🎛️ Method used

Mainly search and replace. I went and checked all usages per file. Component/Template pairs. Substitution of the alias prepended with the service that I would inject locally, and then unlink the mixin to see if it still worked. From the testing I've done locally, this all seemed to still work properly, but I can't stress enough that this change is quite critical.

### 🔧 Note on refactors

I've also taken the time to do some refactoring to Octane, and angle brackets in the templates where I could. This was done in a best-effort fashion, meaning I did this where I could. There were some places where this was tougher, or where computed properties were async. I've attempted to change those, but it introduced a lot of hassle, so much that I would just drop refactoring when encountering these.

The basic rule was:
1. Is there still another mixin on the component?
2. Are there async computed properties?
3. Other advanced constructions or observers?

Any of these would prevent me from going too deep. Later I just kept myself to the basic refactor of the mixin only, to save on time.

## 👀 What to look out for

* Any place requiring operations on the user role
* Any place requiring operations on the user object
* Any place checking if the current session is an Editor, Admin, or Viewer

2020-04-27 15:00 UTC, BenjaminDendas requested changes
Zeer lijvige PR met heel wat changes is, lijkt me normaal dat hier nog wat aan gedaan dient te worden.. Ik ben al scannend door de code gegaan omwille van de grootte en heb eerder zitten kijken of in de applicatie alles nog werkt zoals verwacht. Mijn bevindingen:

## 🐞 Bugs
### Switchen van agendaitem
Wanneer je switched van agendaitem dan wordt er een error geworpen in de console: 
![image](https://user-images.githubusercontent.com/11557630/80377853-18c41200-889c-11ea-82a9-a11dd91d2010.png)
Update: Dit blijkt een issue te zijn dat momenteel ook al op development zit.. dient wel aangepakt te worden.. Ik zal hier een ticket voor maken.

### Uploaden van documenten
Het uploaden van documenten werkt niet meer.
Agenda -> Agendaitem -> Documenten -> Upload document
![image](https://user-images.githubusercontent.com/11557630/80378501-0bf3ee00-889d-11ea-8cbe-9c88465c0d30.png)

### linken van reeds bezorgde documenten
Het linken van reeds bestaande documenten lukt niet meer:
![image](https://user-images.githubusercontent.com/11557630/80378634-3c3b8c80-889d-11ea-9a26-db12796e94a2.png)

### Een opmerking plaatsen
Een opmerking plaatsen geeft een error in de console:
![image](https://user-images.githubusercontent.com/11557630/80379127-f4693500-889d-11ea-89e2-71954d97968e.png)

### Authenticatie issues
Refactor zorgt ervoor dat je in een non-logged in state kan geraken waardoor je alles kan zien in kaleidos.
De sessie zit wel nog in de localstorage onder de key `ember-simple-auth-session` 
```{"authenticated":{"authenticator":"authenticator:mock-login","links":{"self":"/mock/sessions/current"},"data":{"type":"sessions","id":"5ea6dc5aa61bec000d000022","attributes":{"roles":["admin"]}},"relationships":{"account":{"links":{"related":"/accounts/f445824e-69d6-46ff-8803-718137ccbbad"},"data":{"type":"accounts","id":"f445824e-69d6-46ff-8803-718137ccbbad"}},"group":{"links":{"related":"/account-groups/71c068e6-d2f0-43de-93ab-cd1e7156ac4b"},"data":{"type":"account-groups","id":"71c068e6-d2f0-43de-93ab-cd1e7156ac4b"}}}}}```

![image](https://user-images.githubusercontent.com/11557630/80383695-3301ee00-88a4-11ea-8547-f092be30e40e.png)

2020-04-27 15:00 UTC, BenjaminDendas commented on app/components/agenda/agenda-header/template.hbs
> +            as |attacher|}}
Linter issue @ line 73: 
`  73:25  error  Incorrect indentation of close curly braces '}}' for the component '{{attach-popover}}' beginning at L73:C25. Expected '{{attach-popover}}' to be at L74:C12.  attribute-indentation`

2020-05-04 08:27 UTC, woutersf commented
@ValenberghsSven  en @rafael-mindreau  Kunnen jullie de merge conflicts samen ook bekijken?

2020-05-08 11:56 UTC, BenjaminDendas requested changes
# Note:
door de app gegaan en vervolgens al scannend door de code

# 🐞Gevonden bugs

### Verwijderen opmerking
Het verwijderen van een opmerking vanuit een agenda-item geeft een foutmelding in de console die niet voorkomt op de development omgeving.
![image](https://user-images.githubusercontent.com/11557630/81398264-3198b700-9129-11ea-8475-021e03e6d7a7.png)

### Het switchen naar de notulen tab werkt niet meer waardoor de app blijft hangen.
Je krijgt de volgende error in de console en de applicatie reageerd hierna niet meer wanneer je switched naar eender welke tab
![image](https://user-images.githubusercontent.com/11557630/81398541-a9ff7800-9129-11ea-9a42-8b20f1c51db0.png)

Soms krijg je ook deze (ik denk dat deze is omdat de app blijft hangen):
![image](https://user-images.githubusercontent.com/11557630/81398627-e03cf780-9129-11ea-9846-d78de02bd1f0.png)

### Documenten wijzigen werkt niet meer
Dit dient nieuwe panel te tonen met de opties die je kan aanpassen..
**Branch:**
![image](https://user-images.githubusercontent.com/11557630/81399117-b9cb8c00-912a-11ea-8cab-82d920aa01ba.png)
**Op Dev:(na het klikken op wijzigen) **
![image](https://user-images.githubusercontent.com/11557630/81399145-c8b23e80-912a-11ea-9e2d-9c7094e99298.png)

### Het downloaden van documentversies werkt niet meer
Je wordt redirect naar de niet gevonden pagina ..

![image](https://user-images.githubusercontent.com/11557630/81399313-19299c00-912b-11ea-8399-0c261c640ebd.png)

### Documentversie downloaden vanaf het tabblad documenten van de agenda werkt niet (lijkt me hetzelfde component als bovenstaande issue
![image](https://user-images.githubusercontent.com/11557630/81400568-b554a280-912d-11ea-8f20-f2ba3e8b7805.png)

### Het wijzigen van de nota vanuit een agendaitem werkt niet meer
![image](https://user-images.githubusercontent.com/11557630/81399618-93f2b700-912b-11ea-92c7-b96b328d4ce3.png)
**Error:**
![image](https://user-images.githubusercontent.com/11557630/81399665-aec52b80-912b-11ea-96c0-488606dfc719.png)

2020-05-11 08:01 UTC, woutersf approved these changes

2020-05-13 07:38 UTC, woutersf commented
Voor mij is hij goed.

2020-05-13 07:58 UTC, merged