Kas 1574 - Het wijzigen van een beleidsveld geeft een visuele bug
kanselarij-vlaanderen/frontend-kaleidos pull request #388
Opened 2020-06-05 13:21 UTC by brechtPhilips

**Het wijzigen van een beleidsveld geeft een visuele bug**

Bij het veranderen van een item value wordt de onderliggende lijst ook bijgewerkt en krijg je geen leeg veld meer te zien.

Files changed:
- management-government-fields/component.js
- manage-ise-code/component.js
- model-manager/component.js

Added test in:
- shouldTestTheModalBehindManageGovermentDomains.spec.js

2020-06-08 10:04 UTC, BenjaminDendas requested changes
Een paar mini-opmerkingen die best nog opgelost worden, voor de rest fine.

2020-06-08 10:04 UTC, BenjaminDendas commented on cypress/integration/unit/settings/general/shouldTestTheModalBehindManageGovermentDomains.spec.js
> +      'Economie, wetenschap & innovatie',
Ik zou hier de array teruggeven zodat je ze in de beforeEach kunt steken in de variabele ipv een bestaande variabele op te vullen, dan is de methode een pure function.

2020-06-08 10:04 UTC, BenjaminDendas commented on cypress/integration/unit/settings/general/shouldTestTheModalBehindManageGovermentDomains.spec.js
> +    cy.get('.ember-power-select-option').should('have.length', govermentDomains.length );
Leftover space

2020-06-08 10:04 UTC, BenjaminDendas commented on cypress/integration/unit/settings/general/shouldTestTheModalBehindManageGovermentDomains.spec.js
> +    cy.get(form.formInput).clear()
`;` vergeten

2020-06-08 11:06 UTC, woutersf commented
@brechtPhilips  testen mss ns runnen in deze branch?

2020-06-09 11:37 UTC, BenjaminDendas approved these changes
Heb de testen gisteren al laten lopen, was normaal in orde.. changes zijn gedaan.. lijkt mij in good to go

2020-06-09 11:43 UTC, merged