KAS-1409: Sorted Agendaitems Route Mixin Refactor
kanselarij-vlaanderen/frontend-kaleidos pull request #389
Opened 2020-06-05 15:02 UTC by rafael-mindreau

# ⚙️  Mixins Refactor: Sorted Agendaitems Route Refactor

⚠️ Tests not started yet (or automatically running with CI)

## What to expect
I've put all mixin functions into the four files where they were used. I moved on from there and put common functions into utils. Only the newsletter overview had some custom code.

## How to test
These routes are accessed by going to an agenda, and then in the actions menu navigating to the following four:

* `Beslissingen bekijken`
* `Kort bestek bekijken`
* `Notulen bekijken`
* `Persagenda bekijken`

These four will forward to a page with the agenda items listed. Click the `klad` tab there to get to the overview page. You can put a breakpoint in the model hook just to be sure you're in the right place.

2020-06-09 06:07 UTC, woutersf commented
✅ TESTS OK

2020-06-09 06:07 UTC, woutersf commented
Mag er voor mij in

2020-06-09 07:33 UTC, brechtPhilips approved these changes
De testen werken, mag gemerged worden van mij

2020-06-09 08:07 UTC, BenjaminDendas requested changes
Ik denk dat we hier hetzelfde hebben als bij documenten, enkele stukken duplicated code.. kunnen we dit misschien best refactoren in een util @rafael-mindreau ?

2020-06-09 08:07 UTC, BenjaminDendas commented on app/routes/print-overviews/press-agenda/overview.js
> +        return EmberObject.create(item);
Kunnen we dit niet refactoren naar een util?

2020-06-09 08:07 UTC, BenjaminDendas commented on app/routes/print-overviews/press-agenda/overview.js
> +    }
Kunnen we dit ook niet refactoren naar een aparte functie

2020-06-09 08:07 UTC, BenjaminDendas commented on app/routes/print-overviews/decisions/overview.js
> +      });
Kunnen we dit niet herschrijven in een functie?

2020-06-09 08:07 UTC, BenjaminDendas commented on app/routes/print-overviews/decisions/overview.js
> +    }
Kunnen we dit niet herschrijven in een functie?

2020-06-09 11:34 UTC, BenjaminDendas approved these changes
Ziet er goed uit voor mij!

2020-06-11 17:50 UTC, woutersf commented
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/FeatureBranches/view/change-requests/job/feature%252FKAS-1409-sorted-agendaitems-route-mixin-refactor/2/

2020-06-12 09:02 UTC, woutersf commented
<img width="653" alt="Screenshot 2020-06-12 at 11 02 09" src="https://user-images.githubusercontent.com/592312/84485282-34447a00-ac9c-11ea-8732-145da0025185.png">

2020-06-12 09:02 UTC, woutersf commented
ALL GREEN - mag erin @rafael-mindreau

2020-06-15 08:11 UTC, merged