KAS-1308: toevoegen header op zoeken pagina
kanselarij-vlaanderen/frontend-kaleidos pull request #420
Opened 2020-06-24 09:57 UTC by BenjaminDendas

# KAS-1308: toevoegen header op zoeken pagina
In deze PR hebben we een header toegevoegd op de zoeken pagina om ervoor te zorgen dat deze in lijn ligt met de overige overzicht pagina's..

##  What has changed

2020-06-25 06:32 UTC, woutersf approved these changes
consistency is king!

2020-06-26 07:56 UTC, ValenberghsSven requested changes

2020-06-26 07:56 UTC, ValenberghsSven commented on app/pods/search/template.hbs
> +</div>
1 indent opschuiven

2020-06-30 10:04 UTC, BenjaminDendas commented on app/pods/search/template.hbs
> +</div>
Solved, my bad.

2020-06-30 10:05 UTC, merged