KAS-1634: removed the observer and refactored the component to octane
kanselarij-vlaanderen/frontend-kaleidos pull request #430
Opened 2020-07-06 06:46 UTC by brechtPhilips

# KAS-1634 : Removed the observer and refactored the component to octane.

## What did i do:

- Refactored the component to an octane component.
- Refactored the template to match tracked and args propperties.
- Deleted the use of an observer

2020-07-10 10:39 UTC, woutersf approved these changes

2020-07-10 12:57 UTC, rafael-mindreau requested changes
![image](https://user-images.githubusercontent.com/1874332/87156886-afaa4300-c2bd-11ea-94d1-371e3be0b66f.png)

It's broken 😕

2020-07-13 15:09 UTC, ValenberghsSven requested changes
Dit is stuk, niet door jouw code, maar iets dat er al stond  lijn 160 en 161
Er staat:
```
    list.map((combinedItem) => {
      const leftGroupName = get(combinedItem, 'left.groupName');
      const rightGroupName = get(combinedItem, 'right.groupName');
```
en er zou moeten staan (dan werkt het lokaal)
``` 
    list.map((combinedItem) => {
      const leftGroupName = combinedItem.get('left.groupName');
      const rightGroupName = combinedItem.get('right.groupName');
```

2020-07-13 15:21 UTC, ValenberghsSven commented
Willen we misschien ook een test schrijven om de vergelijk functie af te testen ?
Gewoon om te bevestigen dat zulke errors eruit komen.
Hoeft niet te veel in detail te gaan

2020-07-15 07:13 UTC, brechtPhilips commented
> Dit is stuk, niet door jouw code, maar iets dat er al stond lijn 160 en 161
> Er staat:
> 
> ```
>     list.map((combinedItem) => {
>       const leftGroupName = get(combinedItem, 'left.groupName');
>       const rightGroupName = get(combinedItem, 'right.groupName');
> ```
> 
> en er zou moeten staan (dan werkt het lokaal)
> 
> ```
>     list.map((combinedItem) => {
>       const leftGroupName = combinedItem.get('left.groupName');
>       const rightGroupName = combinedItem.get('right.groupName');
> ```

Aangepast !

2020-07-15 17:08 UTC, ValenberghsSven approved these changes

2020-07-15 17:11 UTC, ValenberghsSven commented
Approved zonder cypress test voor die compare functie.
Opgelijst in KAS-1571

2020-07-16 09:19 UTC, merged