KAS-1638: Themes Selector Observer Refactor
kanselarij-vlaanderen/frontend-kaleidos pull request #433
Opened 2020-07-09 08:34 UTC by rafael-mindreau

# ⚙️ Observer Refactors: Themes Selector

## What changed?

Moved the component to Octane `@ember/component` with the new syntax. Removed the useless observer from the themes selector.

2020-07-10 14:47 UTC, BenjaminDendas commented
🚨🚨🚨 Werkt nog niet naar behoren! 
Wanneer je geen thema's hebt in een kort bestek en je selecteert er een en kiest vervolgens voor opslaan dan zal het thema opgeslagen worden. Wanneer je echter de thema's van een andere procedurestap opent in de klad view, dan zie je dat de selectie van het vorige thema overgenomen wordt in de volgende agenda.. Het lijkt echter wel geen data-persistence issue te zijn maar eerder checkboxen die niet correct uitgevinkt worden wanneer nodig.

2020-07-16 06:45 UTC, brechtPhilips commented on app/pods/components/utils/themes-selector/component.js
> +  get selectedThemesReload() {
Minor change: set a new line before the selectedThemesReload

2020-07-20 13:30 UTC, rafael-mindreau commented
@ValenberghsSven @BenjaminDendas your changes seem to have had a good effect. I just checked them and they seem to be fair dinkum! Great succes! 😎 👍

2020-07-20 14:43 UTC, BenjaminDendas commented
Ik heb hier niets actief aan gedaan he, dat waren @ValenberghsSven  en @brechtPhilips , @brechtPhilips wel nog even kijken waarom de test faalt.

2020-07-23 08:11 UTC, woutersf commented
🟢  jenkins

2020-07-27 15:59 UTC, BenjaminDendas requested changes
Wanneer je de thema’s aanpast van een KB vanuit het overzicht scherm en je vervolgens naar het klad scherm gaat zonder op te slaan in het overzicht scherm, dan zie je de geselecteerde thema’s staan op de kladversie, dit is op development niet het geval en zal voor verwarring zorgen bij de eindgebruiker.

Waarschijnlijk komt dit omdat thema's nu op het model aangepast gaan worden en dit dus ook continue geupdatet wordt, we willen enkel persisteren naar het effectieve model wanneer je op `opslaan` klikt.

De knop annuleren heeft nu dus ook geen nut omdat je niet meer kunt annuleren eens je een aanpassing doet.

2020-07-31 09:50 UTC, rafael-mindreau commented
@BenjaminDendas I made a bug to deal with this later, so we can unclog the pipeline here. Check et uut: https://kanselarij.atlassian.net/browse/KAS-1769

2020-08-04 11:37 UTC, merged