KAS-1636: Case Search Observer Refactor
kanselarij-vlaanderen/frontend-kaleidos pull request #436
Opened 2020-07-09 09:47 UTC by rafael-mindreau

# 👁️ Observer Refactors: Case Search

## What changed?

* Replaced the Observer with an action-based feedback from the searchTerm input field
* Refactored the entire component to be `@glimmer/object` instead.

## How to test?

We first thought the component was removed. It's not easy to find the location of this component at all! Go to Dossiers > Select a case > Select a subcase > Go to actions and click on move subcase. This opens a modal with a search. This is the case search component we've refactored in this PR! Everything should work as expected, of course 🌝

2020-07-10 11:08 UTC, woutersf approved these changes
✅  🤖 jenkins likes it
✅  ☮️  I like it

2020-07-10 14:19 UTC, BenjaminDendas requested changes
Ziet er goed uit voor mij.. getest en ik heb hetzelfde resultaat als ervoor gehad..
Ik had één gedachtenspinsel over het stukje code dat ik gecomment had.. wat denk jij daarvan?

2020-07-10 14:19 UTC, BenjaminDendas commented on app/pods/components/utils/case-search/component.js
> +      filter[searchModifier + textSearchKey] = searchTerm;
Zouden we hier niet: ```filter[`${searchModifier}${textSearchKey}`]``` van maken?

2020-07-13 14:45 UTC, ValenberghsSven approved these changes
De refactor ziet er goed uit + getest en werkt.
Het enigste dat ik zou opmerken is dat we niet telkens terug naar page 0 gaan bij een nieuwe zoektocht.
Dit was echter al zo voor de refactor, dus geen blokkerende factor voor dit ticket.

2020-07-14 14:04 UTC, merged