KAS-1640: Refactored the observer out of job model
kanselarij-vlaanderen/frontend-kaleidos pull request #443
Opened 2020-07-10 13:35 UTC by BenjaminDendas

# 👁‍🗨 KAS-1640: Refactored the observer out of job model
In deze PR hebben we de observer uit de job model gerefactored.

## ✏️ What has been done:
De logica die in de observer stak hebben we geïntegreerd in de computed property. Dit geeft na testen identiek hetzelfde resultaat.

## Tests:
- `currently running on jenkins`

2020-07-14 12:21 UTC, rafael-mindreau requested changes

2020-07-14 12:21 UTC, rafael-mindreau commented on app/models/job.js
> +    if(isSuccess) {
WILL YOU PLACE SPACE

```js
if (isSuccess) {
```

2020-07-14 13:06 UTC, BenjaminDendas commented on app/models/job.js
> +    if(isSuccess) {
fixed

2020-07-14 14:50 UTC, MikiDi commented
Sluit deze PR aub zonder te mergen :pray: . Dit is een definitie van wat computed properties niet moeten zijn. Je triggered een event als side-effect van een computed prop die re-compute.
:brain: :thought_balloon: We zijn observers aan het verwijderen omdat de linter zegt dat we dat moeten doen :arrow_right:  De linter zegt dat we dat moeten doen omdat de ember community dat zo geconfigureerd heeft :arrow_right:  Men heeft dat zo geconfigureerd omdat men ondervonden heeft dat als je veel observers gebruikt, je snel onverwachte neveneffecten creëert. Met observers kan je eender welke actie triggeren door eender welke variabele te observen. De developer die na je komt, en zich niet bewust is van het bestaan van je observer, kan dus heel wat onverwachte effecten veroorzaken door wijzigingen in een variabele waar je observer op steunt.  
Een computed property is eigenlijk een specifieke vorm van observer. Enkel ga je ipv _eender welke actie triggeren_, een nieuwe waarde toekennen aan die property. Dat houdt het overzichtelijk.  
Hier ken je niet enkel een nieuwe waarde toe (door iets te returnen), maar trigger je ook een event. Dat herleidt deze computed property eigenlijk tot "een observer die geen linting errors geeft". Dat maakt het alleen maar meer confusing :thinking:

2020-07-14 21:07 UTC, BenjaminDendas commented
We weten dat we hier ingaan tegen de principes van een computed property (we hebben deze met 3 man zitten pairen).. 
Het is in ofwel dit ofwel de observer behouden.. of er een andere manier voor vinden om dit op te lossen....

Ik vind het jammer dat het op het model zit.. voor een systeem dat een download in actie zet moeten er toch andere implementaties mogelijk zijn?

2020-07-20 12:22 UTC, rafael-mindreau requested changes
I will follow suit with @MikiDi and say that this isn't desirable. I opt for leaving this as an observer (wrapped with eslint's disable). I knew there was going to be at least one case which we would not be able to refactor fully. Observers are deprecated, sure, but doing side-effects in a CP is a crime 😂 

We're either going to change the code or leave the observer be, but in any case I would close this PR and its ticket on JIRA.

2020-07-23 07:44 UTC, closed without merging