KAS-1382: Vrijgeven documenten overheid
kanselarij-vlaanderen/frontend-kaleidos pull request #446
Opened 2020-07-13 09:56 UTC by BenjaminDendas

# KAS-1382: Vrijgeven documenten overheid

In deze PR lossen we een `bug` op die de documenten verbergt als je als overheid ingelogd bent en de documenten nog niet vrijgegeven zijn.

## Reproduce:

- Maak een procedurestap aan met documenten, agendeer
- Stel het agendapunt uit
- Keur de agenda goed / afsluiten / vrijgeven beslissingen / vrijgeven documenten
- Kopieer de uitgestelde procedurestap (actie bij aanmaken procedurestap), agendeer op een nieuwe agenda
- Keur de nieuwe agenda goed.

Als je nu als overheid gaat kijken naar die laatste agenda kan de documenten niet meer zien als overheid..

## 🖼 Views

### agenda overview
**Admin:**
![image](https://user-images.githubusercontent.com/11557630/87290841-cee3e300-c4fe-11ea-8ef2-b20c2b407d38.png)

**Overheid:**
![image](https://user-images.githubusercontent.com/11557630/87290996-0488cc00-c4ff-11ea-89fa-d9a71bba2a3f.png)

### agenda detail
**Admin**
![image](https://user-images.githubusercontent.com/11557630/87290996-0488cc00-c4ff-11ea-89fa-d9a71bba2a3f.png)

**Overheid:**
![image](https://user-images.githubusercontent.com/11557630/87291051-18ccc900-c4ff-11ea-82a1-f448ebc452e1.png)

2020-07-14 14:14 UTC, rafael-mindreau requested changes
Some small changes required.

2020-07-14 14:14 UTC, rafael-mindreau commented on app/pods/components/agenda/agendaitem/agendaitem-case/subcase-documents/component.js
> +      if(isAgendaItem) {
😬  spacing

2020-07-14 14:14 UTC, rafael-mindreau commented on app/pods/components/agenda/agendaitem/agendaitem-case/subcase-documents/component.js
> +      if(isSubcase) {
😬 Spacing

2020-07-14 15:08 UTC, BenjaminDendas commented on app/pods/components/agenda/agendaitem/agendaitem-case/subcase-documents/component.js
> +      if(isAgendaItem) {
fixed

2020-07-14 15:08 UTC, BenjaminDendas commented on app/pods/components/agenda/agendaitem/agendaitem-case/subcase-documents/component.js
> +      if(isSubcase) {
fixed

2020-07-14 21:11 UTC, BenjaminDendas commented
![image](https://user-images.githubusercontent.com/11557630/87476816-4f9dfe80-c627-11ea-8497-9698b1138cee.png)

2020-07-17 12:08 UTC, ValenberghsSven approved these changes

2020-07-20 10:22 UTC, rafael-mindreau requested changes
I tried to reproduce, but overheid never saw anything. We should check this one out together.

2020-07-20 10:22 UTC, rafael-mindreau commented on app/services/current-session.js
> +  checkOverheidRights() {
Renaming suggestion `checkGovernmentRights`. Using mixed language variables looks funny 😂

2020-07-27 16:14 UTC, BenjaminDendas commented on app/services/current-session.js
> +  checkOverheidRights() {
Solved

2020-08-05 07:49 UTC, merged