KAS-1636: removed obeserver and refatorer to octane
kanselarij-vlaanderen/frontend-kaleidos pull request #449
Opened 2020-07-15 06:44 UTC by brechtPhilips

## 🐙 KAS-1636: removed obeserver and refatorer to octane

# 👨‍⚕️ What did i do:
- octane refactor in `app/pods/components/utils/add-existing-document/component.js`
- removed observer from `app/pods/components/utils/add-existing-document/component.js`
- updated properties in `app/pods/components/utils/add-existing-document/template.hbs`

2020-07-16 09:30 UTC, BenjaminDendas requested changes
Few minor fixes required

2020-07-16 09:30 UTC, BenjaminDendas commented on app/pods/components/utils/add-existing-document/component.js
> +    this.items = documents
`;` vergeten

2020-07-16 09:30 UTC, BenjaminDendas commented on app/pods/components/utils/add-existing-document/component.js
> +    const documents = yield this.store.query('document-version', this.queryOptions());
`documents` variabele lijkt me hier overbodig, we doen er geen extra checks op dus zou rechtstreeks op items gezet worden.

2020-07-17 09:02 UTC, BenjaminDendas approved these changes

2020-07-17 12:15 UTC, ValenberghsSven approved these changes

2020-07-17 12:16 UTC, merged