KAS-1701: Kort bestek bericht leeg maken geeft error
kanselarij-vlaanderen/frontend-kaleidos pull request #451
Opened 2020-07-16 15:00 UTC by BenjaminDendas

# 😬 KAS-1701: Kort bestek bericht leeg maken geeft error

De RDFA editor gaf al een langere tijd verschillende foutmeldingen.. dit was een van de bug-tickets die Johan opengezet had.. we hebben deze nu opgelost met een versie upgrade naar RDFA-editor v0.39.0

## ✏️ What has been done
- Versie bump van de RRDFA-editor naar v0.39.0
- code aangepast in Kort-bestek, Notulen en Beslissingen om de nieuwe RDFA-editor te ondersteunen..
- Hoogte van de default RDFA-editor aangepast zodat deze niet meer een groot deel van het scherm in beslag neemt maar eerder dezelfde grootte als de vorige RDFA-editor.
- Indentatie in de RDFA-editor gedisabled via de opties omdat deze errors kunnen werpen wanneer dit gebruikt wordt op een niet-lijst element. (ter voorzorg)

## 🖼 Screenshots:
Voor:
![image](https://user-images.githubusercontent.com/11557630/87687206-c18c5a00-c785-11ea-843e-8b6f668a27a3.png)

Na:
![image](https://user-images.githubusercontent.com/11557630/87687118-a588b880-c785-11ea-8319-9852765c94d3.png)

## 🧪 Test
- Dit moet **grondig** getest worden, voor we dit laten doorgaan, ook testen op oude data!!!
- De cypress testen zijn aan het lopen op deze PR.

2020-07-20 09:52 UTC, rafael-mindreau requested changes
The new RDFA editor boasts a completely different visual style. Has this been discussed? It's quite impactful. For the code I only had a small remark

2020-07-20 09:52 UTC, rafael-mindreau commented on app/pods/components/news-item/edit-item/component.js
> +      this.set('initValue', this.get('initValue') + val);
Suggested:

```javascript
this.set('initValue', `${this.get('initValue')} ${val}`);
```

2020-07-23 06:49 UTC, woutersf commented
@madnificent  Is it correct that in the minor versionbump from ~0.23.2"  to  "0.39.0" a restyling was done? Is it possible to have the old style in the new version? This does not fit nice in our application in some places.

2020-07-23 06:50 UTC, woutersf commented
⚠️ NIET MERGEN: zie KAS-1701

2020-07-23 07:47 UTC, madnificent commented
@woutersf To my understanding, Say now has a style which is more in line with the construction of AppUniversum whilst being configurable.  The default feel is now a Say feel (I guess that makes sense).  The README contains some information on how to restyle but I think the fastest path forward is to let @dietr and @wolfr discuss.  Both are on the chat, will start a conversation.

2020-07-23 11:46 UTC, Wolfr commented
These vars need to be set to false I think:

https://github.com/lblod/ember-rdfa-editor/blob/master/app/styles/ember-rdfa-editor/_s-theme.scss#L11-L12

This one could be made white to make it look like the older design:

https://github.com/lblod/ember-rdfa-editor/blob/master/app/styles/ember-rdfa-editor/_s-theme.scss#L20

Extra opionion/info posted in https://kanselarij.atlassian.net/browse/KAS-1701

2020-07-28 12:43 UTC, BenjaminDendas commented
Snippet vanuit de RDFA discussion op Rocket Chat:

```
Ik kom nog even terug op het gesprek van de RDFA editor:
Met de opmerkingen van wolfr heb ik een oplossing werkende om de editor inderdaad terug naar de oude layout te zetten. (TOP)

Echter ben ik wel moeten gaan zoeken hoe de SCSS variable system werkt want dat kende ik niet..
Nu geeft de sass reference aan: https://sass-lang.com/documentation/variables#default-values

Normally when you assign a value to a variable, if that variable already had a value, its old value is overwritten. But if you’re writing a Sass library, you might want to allow your users to configure your library’s variables before you use them to generate CSS


Op stackoverflow gaven ze het volgende aan: https://stackoverflow.com/questions/48962960/sass-overriding-default-variables-of-imported-stylesheets
You can assign to variables if they aren't already assigned by adding the !default flag to the end of the value. This means that if the variable has already been assigned to, it won't be re-assigned, but if it doesn't have a value yet, it will be given one.

Het lijkt me dus dat we de variabele niet kunnen overschrijven nadat de variabele gezet is in de @import van de library..
$say-paper                       : true !default; // True = displays a paper like background.
$say-paper-sidebar               : true !default; // True = adds space for a sidebar to the right.

Is de !default hier dan wel de juiste keuze? Het minor issue dat we nu hebben is dat we de variabele zouden moeten declareren voordat we de import doen van de library ipv erna wat binnen kaleidos de manier van werken was.. daarom zijn er scss-fix files voor zover ik er weet van heb..

Het is natuurlijk een kwestie van personal preference veronderstel ik maar het is wel stuff om eens over te babbelen..

Anyway ik heb het momenteel opgelost gekregen met een import erboven te zetten, ik besprek later wel met wolfr of dit een approach is die wenst is, het gaat alleszins in tegen de huidige flow die we voor de scss structuur volgen.
To be continued.. wanneer wolfr terug is.
```

We zouden dus in principe verder kunnen gaan met deze implementatie en indien nodig, een paar minor changes patchen naderhand

2020-08-13 13:05 UTC, woutersf approved these changes
Getest. Lijkt wel te werken zoals er voor .
Funny dingskes die er nog steeds in zitten:
- Pasten pakt je focus niet mee naar het laatste karakter. Dus meerdere keren pasten lijkt telkens tussen te voegen. Dit is raar (lijkt me niet related met onze change eerder RDFA quirks).
- text selecteren naar links en rechts met SHIFT links en SHIFT rechts lijkt ook niet te werken. (idem hierboven) dit gooit wel een fout.

2020-08-18 14:44 UTC, Wolfr commented
@woutersf ik heb de 2 zaken die je opmerkt reeds gelogd op de repo van de RDFA editor:

* https://github.com/lblod/ember-rdfa-editor/issues/28
* https://github.com/lblod/ember-rdfa-editor/issues/32

2020-08-28 08:47 UTC, rafael-mindreau approved these changes
Zorgen dat er voor alle side-tracked problems een ticket bestaat, maar deze mergen we best al...

2020-08-31 08:56 UTC, merged