KAS-1209: Opmerking tonen in document overzicht
kanselarij-vlaanderen/frontend-kaleidos pull request #469
Opened 2020-08-11 12:59 UTC by BenjaminDendas

# 👓 KAS-1209: Opmerkingenveld tonen in doc overzicht

## 🔨 What has changed
- De opmerking wordt nu getoond in het overzicht voor documenten van een agendaitem.
- Er is een bestaande test aangepast die valideert of het veld er is.

## 🖼 Screenshots
Before:
![image](https://user-images.githubusercontent.com/11557630/89899853-28fdc400-dbe3-11ea-9bc0-104670334e1c.png)

After:
![image](https://user-images.githubusercontent.com/11557630/89899631-dde3b100-dbe2-11ea-9778-361a3c1fb8ba.png)

## 🧪 Tests:
`agenda.spec.js`

2020-08-13 09:51 UTC, MikiDi commented
Dit heeft ons bijgeleerd waarom het initieel zo wrong voor het implementeren van deze opmerking (`item.explanation`). De opmerking is niet eigen aan het agendapunt, maar eigen aan de documenten die bij het agendapunt horen. Kan je bij deze `explanation`-eigenschap in het model van agendapunt een commentaartje schrijven om dit te duiden? Zo weten we binnen een jaar nog wat `explanation` nu juist inhoudt ...

2020-08-13 11:01 UTC, woutersf approved these changes
Ik heb die comment toegeveogd. Indien testen green: ✅ for me

2020-08-14 13:31 UTC, ValenberghsSven requested changes
Beetje nitpicky, maar explaination test selector => explanation  plz :sweat_smile:

2020-08-17 11:16 UTC, ValenberghsSven approved these changes

2020-08-17 11:17 UTC, merged