KAS-1726: Rename agendaItem to agendaitem
kanselarij-vlaanderen/frontend-kaleidos pull request #471
Opened 2020-08-12 09:56 UTC by BenjaminDendas

# 😬 KAS-1726: Rename agendaItem to agendaitem
In deze PR hebben we de inconsistentie van agendaItem aangepakt in de code van de frontend.

## ✏️ What has changed
Via een `search all` in de IDE hebben we de occurrences van agendaItem aangepast naar agendaitem.
Er zijn meerdere searches gebeurd om alle occurrences eruit te halen.

## ⚠️🚨 Important
Het gebruik van agendaItem dient herbekeken te worden wanneer er branches gemergd worden.

## 🧪 Tests
Dit zou geen functionele changes moeten hebben, de testen dienen dit aan te tonen.

2020-08-13 09:35 UTC, MikiDi commented
Ik snap het consistentie-argument, maar imo kies je voor de verkeerde optie. `agenda item` wordt in het engels steeds los van elkaar geschreven. In camelcase-logica wordt dat dus `agendaItem`, in kebab-case-logica `agenda-item`.
Ik vermoed dat de verwarring er in is geslopen door het taalkundig verschil tussen het engels en het nederlands. In het nederlands worden samenstellingen (`agendapunt`) vrijwel altijd aan elkaar geschreven, in het engels steeds los van elkaar, met uitzondering van "heel populaire woorden" die uiteindelijk 1 worden.

2020-08-13 10:09 UTC, woutersf commented
Dit is gewoon een oefening om het gelijk te trekken. 
De beiden kwamen voor in het project.
Nu komt het nog slechts op een manier voor.

Als we dit allemaal moeten hernoemen naar agendaItem, kunnen we dit in een aparte PR doen.

2020-08-13 10:53 UTC, woutersf approved these changes
uniformiteit - I like it

2020-08-17 10:54 UTC, ValenberghsSven requested changes
Er zijn nog +- 130 plaatsen waar agendaItem voorkomt, maar dan in langere namen (AgendaItem)
Die met hoofdletter A lijken hier gemist te zijn.

De discussie of het nu agendaItem of agendaitem of agenda-item is terzijde.
Er zijn in de huidige codebase veel meer zonder hoofdletter I (1419) dan met hoofdletter I (340) of met koppelteken (127, waarvan veel css)
Gelijktrekken naar de meest voorkomende is een eerste stap naar uniformiteit (en sneller gedaan)

2020-08-28 08:41 UTC, rafael-mindreau approved these changes
Juist nog merge conflicten oplossen

2020-09-11 14:36 UTC, merged