KAS-1779: Migrate icons
kanselarij-vlaanderen/frontend-kaleidos pull request #474
Opened 2020-08-14 13:01 UTC by rafael-mindreau

# Icon Migrations

This PR is for the migration away from WebUniversum icon font and towards our own generated one.

## 👀  What changed?

Thanks to @Wolfr we had a list of distinct occurrences. Went ahead and replaced all old icons with the existing ones in our new set. Took note of all icons we did not yet have. List is on JIRA. We synced a bit. Then I was able to change over a few icons. **Draft status: Not all icons have been migrated. Waiting for design to present new candidates for remaining unresolved icons**.

I also had to make some very specific fixes for alignment and size. Made a new file to house all of these kinds of changes together.

2020-08-14 14:40 UTC, BenjaminDendas commented
@rafael-mindreau geen draft meer dan?

2020-08-14 15:23 UTC, rafael-mindreau commented
@BenjaminDendas O jawel hoor, er is nog werk dat gedaan moet worden!

2020-08-17 13:25 UTC, BenjaminDendas commented
⚠️ Testen zijn niet aangepast, jenkins zou hier sowieso op falen voor bv `.vi-vl-pencil`. ⚠️
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/FeatureBranches/view/change-requests/job/PR-474/1/

Heb wel alvast nog een build laten lopen zodat je een build report hebt van de laatste versie.

2020-08-20 04:35 UTC, BenjaminDendas requested changes
Ik vind nog changes in de codebase m.b.t. icons die niet in de lijst staan van JIRA die icons die er nog niet zijn.. deze lijken me over het hoofd gezien?

De lijst op jira:
```
vl-vi vl-vi-copy-paste
vl-vi vl-vi-expand-vertical
vl-vi vl-vi-link-broken
vl-vi vl-vi-printer-view
vl-vi vl-vi-save
vl-vi vl-vi-synchronize
vl-vi vl-vi-timeline
```

bv: in `app/pods/components/web-components/vl-alert` (VlAlertComponent) staan de volgende icons nog in de component file:

- `vl-vi-alert-triangle`
- `vl-vi-alert-circle`
- `vl-alert--${classType}` dit geeft: `vl-alert--success`, `vl-alert--error`, `vl-alert--warning`

In `app/pods/components/utils/documents-list-for-item` vind ik de volgende nog:
- `vl-vi-minus`, ik geloof dat deze vervangen kan worden door `ki-remove` ?

In `app/pods/components/subcase/subcase-case/subcase-titles` vind ik de volgende:
- `vl-vi vl-vi-lock`

In `app/utils/config` vind ik de volgende:
- `vl-vi vl-vi-question-mark` dit kan `ki-circle-question` of `ki-question-mark` worden..

2020-08-20 06:27 UTC, Wolfr commented
Als hier vragen over zijn, graag centraliseren op bv. #kaleidos-design op Rocket chat of in een specifiek gesprek over de issue zodat zowel @emilyvandewalle als ik kunnen volgen.

2020-08-27 13:12 UTC, rafael-mindreau commented
@BenjaminDendas Can you re-iterate?

2020-09-03 05:46 UTC, woutersf approved these changes
🙏  sorry @rafael-mindreau  Ziet er goed uit. 
Ik zie wel dat er testen bouwen op die classes
<img width="931" alt="Screenshot 2020-09-03 at 07 39 21" src="https://user-images.githubusercontent.com/592312/92075365-a36fcd00-edb8-11ea-9ee8-f97e69315ab1.png">
Ik heb daarvoor nog een klein commitje gepushed. Als de build groen is in jenkins is ie voor mij 👍 good to go

2020-09-03 08:44 UTC, merged