KAS-1775: change css voor mededeling
kanselarij-vlaanderen/frontend-kaleidos pull request #481
Opened 2020-08-25 14:27 UTC by BenjaminDendas

# 🧹 KAS-1775: Agenda-detail minor style update

## ✏️ What has been changed:
De mededeling `Er zijn nog geen mededelingen in deze agenda` in de agenda-detail component heeft een minor css update gekregen

## 🖼 Screenshots:
![image](https://user-images.githubusercontent.com/11557630/91186666-9df6f080-e6ef-11ea-8da9-a074892f5dc1.png)

2020-08-27 11:28 UTC, rafael-mindreau requested changes
You used `px`

2020-08-27 11:28 UTC, rafael-mindreau commented on app/styles/custom-components/_vlc-agenda-detail-sidebar.scss
> +  margin: 15px;
You used `px`

2020-08-27 11:28 UTC, rafael-mindreau commented on app/styles/custom-components/_vlc-agenda-detail-sidebar.scss
> +  margin: 15px;
You used `px`

2020-08-27 15:11 UTC, BenjaminDendas commented on app/styles/custom-components/_vlc-agenda-detail-sidebar.scss
> +  margin: 15px;
fixed

2020-08-27 15:11 UTC, BenjaminDendas commented on app/styles/custom-components/_vlc-agenda-detail-sidebar.scss
> +  margin: 15px;
fixed

2020-08-28 13:04 UTC, rafael-mindreau approved these changes

2020-08-28 13:07 UTC, rafael-mindreau requested changes
Testen falen hier op?

2020-09-02 09:37 UTC, merged

2020-09-02 09:38 UTC, ValenberghsSven commented
1 flaky test, 1 test die gefixt is op development dus ticket is gemerged