KAS-1840: Create publications tab
kanselarij-vlaanderen/frontend-kaleidos pull request #496
Opened 2020-09-03 10:29 UTC by rafael-mindreau

# Publications tab

## 👀  What changed
Added a new feature flag and tab for publications. Will only be visible local and on development. Never on acceptance nor production. The page is just an empty route placeholder for now

2020-09-07 10:09 UTC, woutersf commented on config/environment.js
> +    ENV.APP.ENABLE_PUBLICATIONS_TAB = true;
@rafael-mindreau  kunnen we dit default op false zetten?

2020-09-07 10:09 UTC, woutersf requested changes
Als de tab default op false stata is het goed voor mij.

2020-09-07 10:09 UTC, woutersf approved these changes
nevermind the above

2020-09-07 10:45 UTC, MikiDi commented
Een tip, voor het geval we intensiever gebruik zouden gaan maken van feature flags: https://github.com/kategengler/ember-feature-flags (verder prima voor mij ...)

2020-09-08 23:06 UTC, BenjaminDendas requested changes
Ge kunt me hier een muggenzifter voor noemen.. de design geeft aan dat de publicatie tab voor dossiers staat.

Als we naar een 1 op 1 mapping willen gaan voor designs, dan volgen we het best hier ook :)
Moest iemand aangegeven hebben dat het voor het `zoeken` veld moet komen, dan geven we dat best door zodat de designs aangepast kunnen worden.

2020-09-23 14:04 UTC, MikiDi commented on app/pods/publications/route.js
> +  authenticationRoute: 'login',
Default. Mag je weg laten in feite

2020-09-23 14:06 UTC, MikiDi commented
2 algemene opmerking, relevant voor alle nieuwe code die we schrijven:
- Native class notatie gebruiken voor `Route`, `Controller`, `Component`, ...
- Anglebrackets notatie gebruiken in de templates

Wanneer bovenstaanden vervuld, mag deze voor mij gemerged worden :-)

2020-09-28 10:09 UTC, woutersf approved these changes

2020-09-28 10:09 UTC, woutersf commented
@rafael-mindreau  jenkins is hier wel 4 keer gefaald.
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/FeatureBranches/job/PR-496/

2020-09-28 10:12 UTC, merged