KAS-1465: removed notulen from interface
kanselarij-vlaanderen/frontend-kaleidos pull request #511
Opened 2020-09-23 13:48 UTC by woutersf

### 🔗 Related PR's
Yggdrasil: https://github.com/kanselarij-vlaanderen/yggdrasil/pull/23 
Project: https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/113

### 🎨 Frontend

- Notule tab weg (in agenda detail)
- Print overview van notulen ook weg

### ⚙️Project
migratie ext:Notule naar dossier:genereert. 
(dossiers linken niet meer via meeting-record ext:notule KLASSE maar dan wel via dossier:genereert relatie)
Migration steps:
1 stukken die via notule gekoppeld zijn een type “notule“ geven (in hun container).
2 stukken rechstreeks koppelen aan zitting (van zitting naar stuk)
3 notules verwijderen
4 kuis relaties ext:getekendeDocumentVersiesVoorNotulen ext:notulenVanAgendaPunt  ext:getekendeNotulen op

### 🧪 Testen
Die run ik eerst nog lokaal
Voortgang volgt.

### 🔍 Please review!
🦅 Eagle eye @ValenberghsSven  en 
🕵️ Data detective @MikiDi

2020-09-24 05:23 UTC, woutersf commented
unit/document-version.spec.js
unit/agendaitem-changes.spec.js
e2e/mandatee-full.spec.js
Hebben nog complementen, working on it.

2020-09-24 09:47 UTC, woutersf commented
✅ And test are green.

2020-09-28 07:56 UTC, Wolfr commented
De bug die ik vrijdag gemerkt had rond dat de print view elk agendapunt op een aparte pagina zet, heeft te maken met deze notulen feature (het is de print view van notulen)

Notulen feature wordt nu verwijderd zie ik. Wat is de projectlogica hierachter? (Ik ben voorstander van ongebruikte features weg te halen hé, wil gewoon even weten waarom)

2020-09-28 10:41 UTC, woutersf commented
> De bug die ik vrijdag gemerkt had rond dat de print view elk agendapunt op een aparte pagina zet, heeft te maken met deze notulen feature (het is de print view van notulen)
> 
> Notulen feature wordt nu verwijderd zie ik. Wat is de projectlogica hierachter? (Ik ben voorstander van ongebruikte features weg te halen hé, wil gewoon even weten waarom)

https://kanselarij.atlassian.net/browse/KAS-1465 werd niet gebruikt. Zat geen data in en zal ook zo niet gebruikt worden.  = dood gewicht

2020-09-28 11:15 UTC, Wolfr commented
Oké, logisch. Nu wil het toeval dat we dit net terug zijn beginnen onderzoeken, maar de effectieve uitwerking is pas voor later.

2020-09-28 14:07 UTC, ValenberghsSven requested changes
`router.js` nog aanpassen 
`this.route('minutes', { path: '/notulen', });`

```
this.route('notes', { path: '/notulen/:agenda_id', }, function() {
      this.route('overview', { path: '/klad', });
      this.route('agendaitems', { path: '/agendapunten', });
    });
```

`agendaitem-nav component`:
`  @tracked meetingMinutesExist = false;`
`this.meetingMinutesExist = isPresent(await this.agendaitem.get('meetingRecord'));`
`
add-signed-documents component` staat nog veel logica rond meeting-record / signedMinutes / signedDocument

`agendaitem.js` model:
`meetingRecord: belongsTo('meeting-record'),`

`meeting.js` model:
`notes: belongsTo('meeting-record'),`
+ nieuwe relatie leggen naar die dossier:genereert ? ook in project nog doen

`meeting-record.js` model bestaat nog, delete

algemeen nog heel veel references naar `meeting-record`, `meetingRecord`, `signedDocument`
in componenten, dispatcher, 

in config.ex:
"http://mu.semte.ch/vocabularies/ext/Notule",

+ in testen: meeting-overviews.spec.js
`it('should visit notule print overview', () => {
    cy.visit(notule);
    cy.wait(1500);
  });`

2020-09-29 05:47 UTC, woutersf commented
> `router.js` nog aanpassen
> `this.route('minutes', { path: '/notulen', });`
> 
> ```
> this.route('notes', { path: '/notulen/:agenda_id', }, function() {
>       this.route('overview', { path: '/klad', });
>       this.route('agendaitems', { path: '/agendapunten', });
>     });
> ```
> 
> `agendaitem-nav` component:
> ` @tracked meetingMinutesExist = false;`
> `this.meetingMinutesExist = isPresent(await this.agendaitem.get('meetingRecord'));`
> ` add-signed-documents component` staat nog veel logica rond meeting-record / signedMinutes / signedDocument
> 
> `agendaitem.js` model:
> `meetingRecord: belongsTo('meeting-record'),`
> 
> `meeting.js` model:
> `notes: belongsTo('meeting-record'),`
> 
> * nieuwe relatie leggen naar die dossier:genereert ? ook in project nog doen
> 
> `meeting-record.js` model bestaat nog, delete
> 
> algemeen nog heel veel references naar `meeting-record`, `meetingRecord`, `signedDocument`
> in componenten, dispatcher,
> 
> in config.ex:
> "http://mu.semte.ch/vocabularies/ext/Notule",
> 
> * in testen: meeting-overviews.spec.js
>   `it('should visit notule print overview', () => { cy.visit(notule); cy.wait(1500); });`

Aanpassingen doorgevoerd. 
Er zitten nog enkele occurences van "meeting-record" in die ik samen met jou is wil bezien

2020-10-15 09:35 UTC, MikiDi approved these changes

2020-10-19 09:02 UTC, merged