KAS-1824: Procedurestappen tree in agenda
kanselarij-vlaanderen/frontend-kaleidos pull request #514
Opened 2020-09-24 14:40 UTC by BenjaminDendas

# 🌲 KAS-1824: Verwijderen procedurestappen tree in agenda
Om de overvloed aan data die we weergeven in te perken, verwijderen we de mogelijkheid om de procedurestappen te zien vanuit de agenda overview

## ✏️ What has changed

- Verwijderen van procedurestappen 🌲 in de dossiers tab van de agenda
- Verwijderen van het component dat enkel hier gebruikt werd om een procedurestap te tonen.

2020-09-25 10:27 UTC, woutersf commented
@BenjaminDendas  Tests blijven wel falen? Heeft dat met de changes te maken?

2020-09-28 10:03 UTC, woutersf approved these changes

2020-09-28 10:07 UTC, woutersf commented
@BenjaminDendas  Blijft ook failure geven in Jenkins (op flaky minister testen, maar ook eentje bij de agendas)
@BenjaminDendas  als dat niet related is met de change moeten we dat mss apart is bezien?
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/FeatureBranches/job/PR-514/5/artifact/reports/cypress_screenshots/screenshots/all-flaky-tests/subcase.spec.js/Subcase%20tests%20--%20should%20open%20an%20existing%20case%20and%20add%20a%20subcase%20(failed).png

2020-09-28 14:11 UTC, ValenberghsSven requested changes
getCaseSubcases nog bekijken in de testen. die faalt legit omdat die route nooit wordt gecalld
weg uit subcase spec,  full spec heeft enkel de route maar wordt niet gebruikt dus ook weg

2020-09-30 06:34 UTC, woutersf commented
fout ligt niet aan tree van procedurestappen, maar aan documenten in beslissing.

2020-09-30 06:34 UTC, merged