Features/kas 1821 goedkeuren afsluiten agenda
kanselarij-vlaanderen/frontend-kaleidos pull request #525
Opened 2020-09-30 05:25 UTC by brechtPhilips

## Features/KAS-1821: Goedkeuren afsluiten agenda

# Cypress:
- added cypress test for closing  an agenda with all OK and some OK and some NOT.
- added cypress test for closingAndApproving  an agenda with all OK and some OK and some NOT.

# Changes:
- Fix pop-ups logica, the order that the pop-ups are being called.
- Delete NOT agendaitems while closing an agenda

2020-09-30 09:20 UTC, BenjaminDendas requested changes
Jenkins faalt nog op enkele bestaande testen.. bekijk je die nog? Heb ook nog enkele opmerkingen geplaatst

2020-09-30 09:20 UTC, BenjaminDendas commented on app/pods/components/agenda/agenda-header/component.js
> +      console.log('Current Agenda, isLockingAgenda:', this.get('isLockingAgenda'));
Denk dat deze nog weg moet :)

2020-09-30 09:20 UTC, BenjaminDendas commented on app/pods/components/agenda/agenda-header/component.js
> +      console.log('Current Agenda, agendas:', agendas);
Nog eentje ;p

2020-09-30 09:20 UTC, BenjaminDendas commented on app/pods/components/agenda/agenda-header/component.js
> +      console.log('Current agenda, lastagenda:', lastAgenda);
Deze

2020-09-30 09:20 UTC, BenjaminDendas commented on app/pods/components/agenda/agenda-header/component.js
> +      console.log('Current agenda, designagenda:', designAgenda);
Deze mag ook weg

2020-09-30 09:20 UTC, BenjaminDendas commented on cypress/support/commands/agenda-commands.js
> +  //   })
Als deze niet gebruikt worden.. dan mogen ze weg

2020-10-06 12:10 UTC, woutersf approved these changes
Die comments in de agenda commands file zou ik er ook nog uit halen. 
Voor de rest lijkt me die wel ok!

2020-10-12 10:18 UTC, woutersf commented
TESTEN blijven ook wel falen

2020-10-12 10:18 UTC, woutersf commented
best agenda test eens checken

2020-10-12 10:19 UTC, woutersf requested changes
testen toch is bezien

2020-10-12 17:52 UTC, BenjaminDendas commented
Ik heb die daarstraks laten lopen, ze slagen individueel wel.. denk dat het ergens in combinatie met andere testen is dat hij aan het falen is.

2020-10-19 13:12 UTC, ValenberghsSven commented
Branch up to date gebracht, zal even kijken waarom testen falen

2020-10-20 11:35 UTC, ValenberghsSven approved these changes

2020-10-20 11:36 UTC, woutersf approved these changes

2020-10-20 11:36 UTC, merged