KAS:1825 deleted comments route and components from agendaitem
kanselarij-vlaanderen/frontend-kaleidos pull request #528
Opened 2020-10-05 08:13 UTC by brechtPhilips

## KAS-1825  Als ontwikkelaars willen we het comments panel in agenda verwijderen.

### Files deleted:
- deleted:    app/pods/agenda/agendaitems/agendaitem/comments/route.js
- deleted:    app/pods/agenda/agendaitems/agendaitem/comments/template.hbs
- deleted:    app/pods/components/agenda/agendaitem/agendaitem-comments/component.js
- deleted:    app/pods/components/agenda/agendaitem/agendaitem-comments/template.hbs
- deleted:    app/pods/components/agenda/agendaitem/new-comment/component.js
- deleted:    app/pods/components/agenda/agendaitem/new-comment/template.hbs

### Files modified:
- modified:   app/pods/components/agenda/agendaitem/agendaitem-nav/template.hbs

### Screenshot: 
![Screenshot 2020-10-05 at 10 12 50](https://user-images.githubusercontent.com/22370478/95055327-69655400-06f3-11eb-8019-057e37d7d816.png)

2020-10-06 12:07 UTC, woutersf requested changes
@brechtPhilips Heb je hiervoor ook changes in het datamodel gedaan?
Ik had verwacht ook een PR tegen te komen in het project en een migration omeventuele data op te kuisen?
publicatie-domain.lisp -> schema:Comment 
Als er geen data is, is een migratie niet nodig, maar dan zou het model wel uit de lisp files mogen.

2020-10-14 09:43 UTC, BenjaminDendas commented
Gechecked op Dev en Prod, geen comments, migratie is dus niet nodig

2020-10-14 10:21 UTC, BenjaminDendas approved these changes
Hebben we samen nog aangepast, frontend lijkt OK.. backend PR dient nog door iemand gevalideerd te worden.

2020-10-15 09:44 UTC, MikiDi approved these changes

2020-10-19 11:52 UTC, ValenberghsSven approved these changes

2020-10-19 12:24 UTC, merged