Feature/kas 1966 no ie edit
kanselarij-vlaanderen/frontend-kaleidos pull request #572
Opened 2020-11-19 16:18 UTC by MikiDi

Make sure users cannot open say-editor in an unsupported browser.

2020-11-20 08:24 UTC, erikap approved these changes

2020-11-20 12:27 UTC, ValenberghsSven commented
Werken de cypress testen hier dan nog mee (jenkins is even stout en will PR's niet builden)
want cypress werkt met electron

2020-11-20 12:43 UTC, MikiDi commented
@ValenberghsSven Ik had gehoopt dat dat onder `isChromeHeadless` zou vallen. Moest dat niet het geval zijn zullen we de `userAgent` die cypress meegeeft moeten aanpassen. Zie [hier](https://docs.cypress.io/guides/references/configuration.html#Browser) onderaan.

2020-11-20 15:36 UTC, ValenberghsSven commented
Aangezien jenkins PR's niet build, even lokaal een test runnen waar de editor gebruikt wordt.
liefst headless, dan is het zeker electron

2020-11-23 10:45 UTC, ValenberghsSven requested changes
De change op zich ziet er goed uit.
Maar ik heb lokaal getest en een kort-bestek tekst aangepast met een ondersteunde browser.
Daarna kort-bestek bekeken met niet ondersteunde browser.
Als ik met die browser het kort-bestek opsla dan overschrijf ik de tekst van het kort-bestek (null) en is de data dus verloren..
Ofwel moeten we het opslaan blokkeren in het geheel, of we moeten de richtext onveranderd meegeven.
Dit op elke plaats waar de rdfa editor gebruikt wordt.

2020-11-23 11:03 UTC, MikiDi commented
Hahá! Good find. Ik zal dat herwerken.

2020-11-24 13:51 UTC, MikiDi commented
> Als ik met die browser het kort-bestek opsla dan overschrijf ik de tekst van het kort-bestek (null) en is de data dus verloren.

Bij deze opgelost. De text wordt niet meer silently overschreven als de editor instance niet beschikbaar is.

2020-11-30 15:25 UTC, ValenberghsSven commented
Lokaal getest, overschrijven lijkt niet meer te gebeuren.
Geupdate met dev (normaal zouden de testen nu groen moeten zijn)
Ik wacht deze nog af voor ik die PR merge

2020-11-30 18:09 UTC, ValenberghsSven commented
cypress testen: 1 gefaald (andere redenen, zit op development), 1 flaky
Dus mag erdoor van mij

2020-11-30 18:09 UTC, ValenberghsSven approved these changes

2020-11-30 18:09 UTC, merged