Feature/kas 1981 zoek dossier
kanselarij-vlaanderen/frontend-kaleidos pull request #585
Opened 2020-12-01 12:44 UTC by woutersf

2020-12-02 08:31 UTC, MikiDi commented on app/pods/publications/template.hbs
> +                {{on "input" this.debouncedSearch}}
Je kan hier meteen de `{{perform ...}}`-helper gebruiken (zie ook http://ember-concurrency.com/docs/tutorial/refactor), zo heb je de extra wrapping task niet nodig ;-)

2020-12-03 11:20 UTC, ValenberghsSven requested changes

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/template.hbs
> +                                           data-test-publication-button-cancel>
Indentatie ofzo?
```
<WebComponents::AuButton
  @skin="borderless"
  {{on "click" this.closePublicationModal}}
  data-test-publication-button-cancel
>
```
zou misschien beter zijn ?

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/template.hbs
> +                  {{on "change" (await isPublicationNumberAlreadyTaken)}}
indentatie

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/template.hbs
> +  </WebComponents::VlModal>
auModal ?

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/to-treat/controller.js
> +      sort: '-created',
sort overbodig, telkens maar 1 id.

alternatief findRecord op case met id, reload:true en dan kijken of case een publication-flow heeft.

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/to-treat/route.js
> +    console.log(params.searchText);
:thinking:

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/to-treat/template.hbs
> +    {{else}}
AuLoader gebruiken/proberen, @message.

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/to-treat/template.hbs
> +                @isLoading={{this.isLoadingModel}}
vl-classes nodig ? is er een auk alternatief ?

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/to-treat/template.hbs
> +              <th class="vl-data-table-col-1"></th>
vl-classes nodig ? is er een auk alternatief ?

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/to-treat/template.hbs
> +                    </button>
AuButton

2020-12-03 11:20 UTC, ValenberghsSven commented on app/pods/publications/to-treat/template.hbs
> +                <td class="vl-u-align-right">
auk ? eventueel auk-u util aanmaken in de package

2020-12-03 11:20 UTC, ValenberghsSven commented on translations/nl-be.json
> -  "search-placeholder": "Vul uw zoekterm in...",
Deze placeholder behouden, die tonen we nu overal (op prod en accept ook)

2020-12-03 11:20 UTC, ValenberghsSven commented on translations/nl-be.json
> +  "search-placeholder": "Geef hier uw zoekterm in",
deze placeholder hernoemen naar een unieke naam als je die wil gebruiken
Het ticket en de figma vermelden andere placeholders
ofwel leeg, ofwel zoeken...

2020-12-03 11:20 UTC, ValenberghsSven commented on translations/nl-be.json
> +  "publication.not.started.yet": "Nog niet gestart",
liefst - ipv . gebruiken

2020-12-03 15:40 UTC, BenjaminDendas requested changes
Mini changes die wel nuttig kunnen zijn denk ik.

2020-12-03 15:40 UTC, BenjaminDendas commented on app/styles/custom-utilities/_text.scss
> +
Kunnen we hier geen AUK css voor gebruiken.. ik zou verwachten dat zulke alignment utils er al inzitten.. indien niet best toevoegen in die css package en die klasse daaruit gebruiken.. zo blijven we niet met .vlc utils werken.

2020-12-03 15:40 UTC, BenjaminDendas commented on app/styles/custom-utilities/_autocomplete.scss
> +}
Ik ga er vanuit dat deze klasse er is om het op de juiste positie te krijgen en dat dit verschillend is vanaf het prototype?

2020-12-03 15:40 UTC, BenjaminDendas commented on app/pods/publications/to-treat/template.hbs
> +        <div class="vl-u-spacer--small"></div>
Best geen `vl` css meer gebruiken.. kijken of we een spacer--small hebben in de AUK utillity css

2020-12-03 15:40 UTC, BenjaminDendas commented on app/pods/publications/controller.js
> +    if (pubFlows.content.length > 0) {
Je zou normaal gezien gewoon de length property van de promisearray kunnen aanspreken wanneer hij succesvol geresolved is https://api.emberjs.com/ember-data/3.4/classes/DS.PromiseArray

2020-12-03 15:40 UTC, BenjaminDendas commented on app/pods/components/web-components/au-dropdown/item/component.js
> +    return '';
Hier willen we `null` hebben staan.. een lege quote zetten, genereerde een spatie op de plekken waar de css staat in de html geloof ik.. dat willen we liever niet.

2020-12-07 15:00 UTC, BenjaminDendas approved these changes

2020-12-07 15:00 UTC, merged