minister edit, rm no-longer supported mandate model/relationship
kanselarij-vlaanderen/frontend-kaleidos pull request #595
Opened 2020-12-07 14:41 UTC by MikiDi

Fixes bug [KAS-2025](https://kanselarij.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=KAS&modal=detail&selectedIssue=KAS-2025). Proper relationship `mandatee`-`mandate` ("Is this a pm, vpm or plain minister?") remains todo though (new feature).

2020-12-08 06:40 UTC, woutersf approved these changes

2020-12-09 10:14 UTC, ValenberghsSven reviewed
die holds wordt nog gebruikt in de code
manage-mandatees/component.js
`const holds = await oldMandatee.get('holds');`

```
const newMandatee = this.store.createRecord('mandatee', {
          title: oldMandatee.get('title'),
          start: this.get('selectedStartDate') || moment().toDate(),
          end: moment().add(5, 'years')
            .toDate(),
          person: selectedPerson,
          holds,
```

nl-be.json heeft nog een vertaling voor dat model.
Die worden nergens anders gebruikt.
`"mandate": "Bevoegdheid",`
`"mandates": "Bevoegdheden",`

2020-12-09 10:25 UTC, ValenberghsSven requested changes
die holds wordt nog gebruikt in de code
manage-mandatees/component.js
`const holds = await oldMandatee.get('holds');`

```
const newMandatee = this.store.createRecord('mandatee', {
          title: oldMandatee.get('title'),
          start: this.get('selectedStartDate') || moment().toDate(),
          end: moment().add(5, 'years')
            .toDate(),
          person: selectedPerson,
          holds,
```

nl-be.json heeft nog een vertaling voor dat model.
Die worden nergens anders gebruikt.
`"mandate": "Bevoegdheid",`
`"mandates": "Bevoegdheden",`

2020-12-10 13:47 UTC, ValenberghsSven approved these changes
Ok zo
Als Jenkins groen is, mergen maar

2020-12-14 10:03 UTC, merged