KAS-2073: Add col for publicationNumber, add sortable header
kanselarij-vlaanderen/frontend-kaleidos pull request #603
Opened 2020-12-10 08:02 UTC by woutersf

- Added column for publication number.
- Added sortable header for this field.
<img width="671" alt="Screenshot 2020-12-10 at 09 01 35" src="https://user-images.githubusercontent.com/592312/101738364-56da1300-3ac6-11eb-9967-a977a8d50017.png">

2020-12-10 14:01 UTC, ValenberghsSven requested changes

2020-12-10 14:01 UTC, ValenberghsSven commented on app/pods/publications/in-progress/in-progress-not-minister/template.hbs
>          {{row.case.shortTitle}}<br/>
Br mag weg dan

2020-12-10 14:01 UTC, ValenberghsSven commented on app/pods/publications/in-progress/in-progress-minister/template.hbs
>          {{row.case.shortTitle}}<br/>
BR mag weg

2020-12-10 14:05 UTC, woutersf commented on app/pods/publications/in-progress/in-progress-not-minister/template.hbs
>          {{row.case.shortTitle}}<br/>
🦅 it is done

2020-12-10 17:35 UTC, BenjaminDendas requested changes
De sortering zit hier toch ook mee in right? Deze werkt namelijk nog niet zoals verwacht lijkt me.

![image](https://user-images.githubusercontent.com/11557630/101808228-608b6700-3b16-11eb-85c0-bf78cd911cfd.png)
![image](https://user-images.githubusercontent.com/11557630/101808265-6d0fbf80-3b16-11eb-9170-5d48f91b9e0c.png)
![image](https://user-images.githubusercontent.com/11557630/101808318-7d279f00-3b16-11eb-8777-175b60e6b705.png)

2020-12-10 17:45 UTC, woutersf commented
@BenjaminDendas klopt, het field is alfanumeriek en musearch sorteert ook alfanumeriek.
in dit field komt ook text num-TER

2020-12-10 17:45 UTC, woutersf commented
Om dit numeriek te laten sorteren zal er een extra nummer field (numeriek) moeten ingesteld worden dat ok geindexeerd wordt

2020-12-10 17:47 UTC, woutersf commented
> De sortering zit hier toch ook mee in right? Deze werkt namelijk nog niet zoals verwacht lijkt me.
> 
> ![image](https://user-images.githubusercontent.com/11557630/101808228-608b6700-3b16-11eb-85c0-bf78cd911cfd.png)
> ![image](https://user-images.githubusercontent.com/11557630/101808265-6d0fbf80-3b16-11eb-9170-5d48f91b9e0c.png)
> ![image](https://user-images.githubusercontent.com/11557630/101808318-7d279f00-3b16-11eb-8777-175b60e6b705.png)

Persoonlijk zou ik dit in een ander issue stoppen.

2020-12-14 10:09 UTC, ValenberghsSven commented
Sortering fixen komt in ander ticket, deze changes zijn goed

2020-12-14 10:09 UTC, merged