Feature/kas 2033 drukproef aanmaken
kanselarij-vlaanderen/frontend-kaleidos pull request #609
Opened 2020-12-10 12:53 UTC by brechtPhilips

## 🍥  KAS-2033:Drukproef aanvragen.

- design gemaakt voor de drukproeven.
- Todo's gezet voor de functionaliteit
- Basic design functionaliteit toegevoegd.

## 🎅  Remarks:
- Ingetrokken op wordt normaal niet getoond (boolean) dit staat er om het visueel te testen

## 🥃  Screen to the shots:

<img width="661" alt="Screenshot 2020-12-10 at 13 47 30" src="https://user-images.githubusercontent.com/22370478/101774349-45a4fc80-3aee-11eb-8b41-d44724b92e72.png">
<img width="664" alt="Screenshot 2020-12-10 at 13 48 03" src="https://user-images.githubusercontent.com/22370478/101774410-58b7cc80-3aee-11eb-8573-c2f448df09af.png">

2020-12-10 15:45 UTC, ValenberghsSven requested changes
Ik was stevig aant reviewen maar het is wel de bedoeling dat we hier data uit DB halen en tonen

2020-12-10 15:45 UTC, ValenberghsSven commented on app/pods/publications/publication/documents/controller.js
> +    this.transitionToRoute('publications.publication.translations');
Is dit een vraag van de gebruikers dat je reroute na aanmaken aanvraag of gebruikt tijdens testen?
Als je meerdere aanvragen wil doen (voor grotere dossier waar ze meerdere kleine publicaties willen doen) is dit mogelijk ongewest gedrag.

2020-12-10 15:45 UTC, ValenberghsSven commented on app/pods/publications/publication/publishpreview/controller.js
> +    alert('this action is implemented in another ticket');
als je acties op voorhand klaarzet geef je ze best al een correcte naam, zijn geen translation activities

2020-12-10 17:00 UTC, BenjaminDendas requested changes
Global opmerkingen op dit ticket:
Dit lijkt me eerder KAS-2037, KAS-2033 is er gisteren al doorgegaan.

Volgens het design moet enkel `Begeleidende tekst` in een donkere kleur dan de reguliere tekst, de tekstkleur komt ook nog niet overeen met hoe het in de design staat.
Moest het design en prototype niet overeenkomen, dan check je best met @Wolfr af welk je moet nemen.. ik zie dat het design `666666, 100%` heeft als kleur en in de code `#545961`

De tekst die eronder staat is een gewone paragraaf zonder styling (zorg wel dat het juiste lettertype en tekstgrootte gebruikt wordt)

Beide elementen zitten in een Label met css `auk-label`, dat zorgt ervoor waarom het hier misloopt. Tekst uit de Label trekken zal het probleem oplossen.

![image](https://user-images.githubusercontent.com/11557630/101802423-b3adeb80-3b0f-11eb-9d30-b4ee1babcba1.png)

De lijn onder de drukproef titel is er niet in het design en het lettertype lijkt me te groot, staat op 2rem terwijl het design 18px aangeeft (1.8rem)
![image](https://user-images.githubusercontent.com/11557630/101803269-9d545f80-3b10-11eb-902e-2fe441cf654d.png)

Het design geeft nog `ministerieel besluit` weer, dit hebben we nog niet, weten we vanwaar dit komt?
![image](https://user-images.githubusercontent.com/11557630/101803534-ea383600-3b10-11eb-88f2-c28aca1b58ce.png)

De placeholder tekst komt niet overeen met hoe het in het design staat.
![image](https://user-images.githubusercontent.com/11557630/101803692-15bb2080-3b11-11eb-9a6a-4b218701c13d.png)

2020-12-10 17:00 UTC, BenjaminDendas commented on app/pods/publications/publication/publishpreview/controller.js
> +    this.panelIcon = ((this.panelIcon === 'chevron-up') ? 'chevron-down' : 'chevron-up');
Best geen check doen op de `panelIcon` maar eerder op de `panelCollapsed`. Als de icons ooit zouden veranderen dan geeft dit overhead om aan te passen terwijl je een perfecte state variabele hebt.

2020-12-10 17:00 UTC, BenjaminDendas commented on app/pods/publications/publication/publishpreview/controller.js
> +    alert('this action is implemented in another ticket');
Ik sluit hierbij aan, ik zou ook niet te generiek gaan bij de namen `deleteProof` etc.. maar eerder naar een methodenaam gaat die effectief zegt wat het moet doen.. Ik vind `proof` een beetje dubbel om te begrijpen. Heb het zelf met google translate gechecked en die geeft idd `proof` maar ik ben er niet echt voor te vinden.. then again `PressProof`/ `PressProofPiece` is ook niet echt een leuk alternatief lijkt me maar je zou dan wel methoden krijgen als `deletePressProofPiece`

2020-12-10 17:00 UTC, BenjaminDendas commented on app/pods/publications/publication/publishpreview/template.hbs
> +              <WebComponents::AuInput @value={{this.model.publicationFlow.numacNumber}} readlonly></WebComponents::AuInput>
Er staat hier nog een TODO bij dat het field weg moet, waarom het dan al niet weghalen?

2020-12-11 08:06 UTC, brechtPhilips commented on app/pods/publications/publication/publishpreview/template.hbs
> +              <WebComponents::AuInput @value={{this.model.publicationFlow.numacNumber}} readlonly></WebComponents::AuInput>
Omdat het numac nummer een nieuwe link gaat krijgen in de data (zo heb ik her verstaan) of ze waren hier nog niet over uit en eenmaal; de backend gewijzigd is kan ik in de frontend de logica opbouwen met de correcte data

2020-12-11 08:06 UTC, brechtPhilips commented
Ik snap deels de verwarring het gaat hier om ticket KAS-2034, foute benaming in de branch gebruikt.

Als ik naar dit ticket kijk staat hier niets in van data in te laden (als het model dit al ondersteund wil ik dat graag erbij nemen ).

2020-12-11 08:29 UTC, ValenberghsSven commented on app/pods/publications/publication/publishpreview/controller.js
> +    alert('this action is implemented in another ticket');
in de meeste gevallen is drukproef een publish preview

2020-12-11 08:33 UTC, ValenberghsSven commented on app/pods/publications/publication/publishpreview/controller.js
> +    this.panelIcon = ((this.panelIcon === 'chevron-up') ? 'chevron-down' : 'chevron-up');
@BenjaminDendas Hier gaan we best werken met een component per drukproef denk ik
Dan kan je in die component een tracked collapsed hebben.
Want er zijn meerdere drukproeven in deze view dus die collapsed = true/false zou dan alle drukproeven open en toe klappen

2020-12-15 10:34 UTC, BenjaminDendas approved these changes

2020-12-15 10:35 UTC, merged