KAS-2134: add <<start publication>> button and <to publication> link …
kanselarij-vlaanderen/frontend-kaleidos pull request #634
Opened 2020-12-24 09:10 UTC by woutersf

Add link to start publication from agenda-items that have a case.

<img width="1195" alt="Screenshot 2020-12-24 at 09 25 21" src="https://user-images.githubusercontent.com/592312/103077491-2323e080-45d0-11eb-8f8f-86e94f3c2356.png">
<img width="1165" alt="Screenshot 2020-12-24 at 09 26 07" src="https://user-images.githubusercontent.com/592312/103077495-25863a80-45d0-11eb-9ddb-6cf252dd55bc.png">
<img width="781" alt="Screenshot 2020-12-24 at 09 32 03" src="https://user-images.githubusercontent.com/592312/103077496-261ed100-45d0-11eb-8055-61ee516f23c4.png">
<img width="347" alt="Screenshot 2020-12-24 at 10 09 06" src="https://user-images.githubusercontent.com/592312/103077497-261ed100-45d0-11eb-95db-7f898084824c.png">

…in overview and detail

2021-01-04 06:48 UTC, BenjaminDendas requested changes
De view refreshed niet wanneer je een publicatie start vanuit een agenda. Ik zou verwachten dat de agenda pagina herlaad zodat je de link krijgt om naar de publicatie te gaan.

Niet in scope van het ticket maar dacht het hier toch even in te vermelden:
Willen we de link naar de publictieflow en de publicatieflow starten knop overal zien? Er is me nu opgevallen dat deze ook zichtbaar is tijdens het editeren van de agenda voor de secretarie.. en ik weet niet of dat wel de beste optie is.. 

Ik zou hem persoonlijk enkel tonen wanneer er niet ge-edit wordt, voor de rest in orde

2021-01-04 08:57 UTC, woutersf commented
> De view refreshed niet wanneer je een publicatie start vanuit een agenda. Ik zou verwachten dat de agenda pagina herlaad zodat je de link krijgt om naar de publicatie te gaan.
Je kan zien in de code dat er bij het aanmaken een transition gebeurt naar de publication. Dus na het aanmaken van de publication wordt je daarnaar verwezen.

> 
> Niet in scope van het ticket maar dacht het hier toch even in te vermelden:
> Willen we de link naar de publictieflow en de publicatieflow starten knop overal zien? Er is me nu opgevallen dat deze ook zichtbaar is tijdens het editeren van de agenda voor de secretarie.. en ik weet niet of dat wel de beste optie is..
> 
> Ik zou hem persoonlijk enkel tonen wanneer er niet ge-edit wordt, voor de rest in orde
Aangepast

2021-01-05 12:16 UTC, BenjaminDendas commented
> > De view refreshed niet wanneer je een publicatie start vanuit een agenda. Ik zou verwachten dat de agenda pagina herlaad zodat je de link krijgt om naar de publicatie te gaan.
> 
> Je kan zien in de code dat er bij het aanmaken een transition gebeurt naar de publication. Dus na het aanmaken van de publication wordt je daarnaar verwezen.
> 
> > Niet in scope van het ticket maar dacht het hier toch even in te vermelden:
> > Willen we de link naar de publictieflow en de publicatieflow starten knop overal zien? Er is me nu opgevallen dat deze ook zichtbaar is tijdens het editeren van de agenda voor de secretarie.. en ik weet niet of dat wel de beste optie is..
> > Ik zou hem persoonlijk enkel tonen wanneer er niet ge-edit wordt, voor de rest in orde
> 
> Aangepast

Hij doet de transition toch niet bij mij, console geeft ook een error.
![image](https://user-images.githubusercontent.com/11557630/103645427-42b7f300-4f58-11eb-9d28-a7867b9551e5.png)

2021-01-05 13:08 UTC, BenjaminDendas approved these changes
Works like a charm.

2021-01-06 11:52 UTC, merged