[DRAFT] KAS-2125: add withdrawn and pauzed status and enable withdrawn status
kanselarij-vlaanderen/frontend-kaleidos pull request #635
Opened 2020-12-24 09:27 UTC by woutersf

### 🔗 related pr
Related Backend PR: https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/144
### Functionality
Allow publications to be withdrawn.
<img width="355" alt="Screenshot 2020-12-24 at 10 25 10" src="https://user-images.githubusercontent.com/592312/103078571-739c3d80-45d2-11eb-97ce-04320acfcad5.png">

De klant wil later ook kunnen pauzeren, dus deze status zit er ook al in. 
Maar voorlopig visualiseren we dit nog niet. Designs hebben dit nog niet.

2021-01-04 06:59 UTC, BenjaminDendas commented
Deze PR gaat nog niet werken omdat er een dependency mismatch is, v.1.2.4 van https://www.npmjs.com/package/@kanselarij-vlaanderen/au-kaleidos-icons is nog niet gepublished op npm, dit dienen we eerst te doen om deze branch opstartbaar te maken.

2021-01-04 08:07 UTC, woutersf commented
> Deze PR gaat nog niet werken omdat er een dependency mismatch is, v.1.2.4 van https://www.npmjs.com/package/@kanselarij-vlaanderen/au-kaleidos-icons is nog niet gepublished op npm, dit dienen we eerst te doen om deze branch opstartbaar te maken.

Icon hardcoded toegevoegd

2021-01-04 14:03 UTC, ValenberghsSven requested changes
nieuw design voor de popup
https://www.figma.com/file/TV7uHiWOymlNTZnD1DGMiE/%F0%9F%92%AF-Kaleidos---Grooming-Digitale-Publicaties?node-id=839%3A10503

![image](https://user-images.githubusercontent.com/22245223/103542858-e7c1c580-4e9d-11eb-8a89-dd9d19ab9b8e.png)

2021-01-04 14:05 UTC, ValenberghsSven commented on translations/nl-be.json
> +  "withdraw": "intrekken"
Hoofdletter voor "intrekken" of anders {{capitalize (t "withdraw")}}

2021-01-04 14:25 UTC, woutersf commented
> nieuw design voor de popup
> https://www.figma.com/file/TV7uHiWOymlNTZnD1DGMiE/%F0%9F%92%AF-Kaleidos---Grooming-Digitale-Publicaties?node-id=839%3A10503
> 
> ![image](https://user-images.githubusercontent.com/22245223/103542858-e7c1c580-4e9d-11eb-8a89-dd9d19ab9b8e.png)

@ValenberghsSven  Johan zegt mij het volgende: "neen, zolang het een confirmation modal is het goed, hoeft niet exact"
beslis jij maar wat we er mee doen

2021-01-04 14:27 UTC, BenjaminDendas commented
> > nieuw design voor de popup
> > https://www.figma.com/file/TV7uHiWOymlNTZnD1DGMiE/%F0%9F%92%AF-Kaleidos---Grooming-Digitale-Publicaties?node-id=839%3A10503
> > ![image](https://user-images.githubusercontent.com/22245223/103542858-e7c1c580-4e9d-11eb-8a89-dd9d19ab9b8e.png)
> 
> @ValenberghsSven Johan zegt mij het volgende: "neen, zolang het een confirmation modal is het goed, hoeft niet exact"
> beslis jij maar wat we er mee doen

Ik heb dat ook met sven kort besproken.. als we daarin de vrijheid krijgen dan stel ik voor dat we voor consistency gaan en als we de bestaande modals met panels in volgen dan zouden de lijnen mogen blijven staan met een harde scheiding tussen header-body-footer.

2021-01-06 10:57 UTC, woutersf commented
<img width="568" alt="Screenshot 2021-01-06 at 11 57 24" src="https://user-images.githubusercontent.com/592312/103761083-63df1900-5016-11eb-9dda-5aa27c22a20f.png">

2021-01-06 11:01 UTC, ValenberghsSven approved these changes

2021-01-06 11:02 UTC, merged