KAS-2119: Fix Ember octane (with ember-view wrapper div)
kanselarij-vlaanderen/frontend-kaleidos pull request #642
Opened 2021-01-06 08:05 UTC by woutersf

2021-01-06 14:14 UTC, BenjaminDendas approved these changes

2021-01-13 10:22 UTC, ValenberghsSven requested changes
er zijn 5 fixes in place momenteel voor die ember-view.
4 daarvan zijn hiermee nog niet opgelost (heb dit niet visueel gecheckt)

Een betere oplossing zou kunnen zijn dat we de css doen werken zonder die css fixes?
De reden dat die ember-view komt is omdat we templates hebben zonder componenten.
Lege componenten maken zou dan ook een deel van die fixes kunnen weghelpen (weet niet hoe dat zit met die application/template)

note, van die 4 andere kan het zijn dat die componenten niet gebruikt worden (oude au-componenten?) maar we moeten dat wel bekijken

![image](https://user-images.githubusercontent.com/22245223/104439126-0ce6c000-5591-11eb-810a-9bb36232c30b.png)

2021-01-13 18:01 UTC, woutersf commented
> er zijn 5 fixes in place momenteel voor die ember-view.
> 4 daarvan zijn hiermee nog niet opgelost (heb dit niet visueel gecheckt)

Wat wil je hiermee zeggen?
Ik denk dat @MikiDi die "octane" er in wou omdat zijn editor dan slimmer kon omspringen met octane code. 
Ik had niet begrepen dat ik de css moest gaan herschrijven.
Ik heb gewoon de ontbrekende div toegevoegd waardoor de applicatie werkt zoals vroeger met een toegevoegde div.
Ik had niet begrepen dat ik de css refactor moest gaan doen om die .ember-view klasse er uit te hebben?
Is dat de bedoeling?
Is het niet goed zo? Het werkt en we hebben     "edition": "octane" in onze package?

2021-01-14 09:36 UTC, ValenberghsSven commented
om deze lokaal werkende te krijgen moest in package-lock.json weggooien.
npm i gaf:
npm ERR! Could not install from "node_modules/@lblod/ember-vo-webuniversum-data-table/ember-data-table@git+https:/github.com/MikiDi/ember-data-table.git#1239029475ec83b7e111ba21bb0741cf995faa95" as it does not contain a package.json file.

op dev branch:
![image](https://user-images.githubusercontent.com/22245223/104572766-619f3f00-5654-11eb-89f1-d1e868b14562.png)

op deze branch:
![image](https://user-images.githubusercontent.com/22245223/104572789-69f77a00-5654-11eb-822d-d641f1e41117.png)

2021-01-14 10:54 UTC, ValenberghsSven approved these changes
Sommige van die css lijkt niet meer nodig te zijn, removed and approved

2021-01-14 10:54 UTC, merged