[DRAFT]
kanselarij-vlaanderen/frontend-kaleidos pull request #644
Opened 2021-01-06 11:36 UTC by woutersf

- added published  pulication flows overview 
- modified date for publicationflow 
- modified date for activities

2021-01-06 11:56 UTC, ValenberghsSven commented
Te controleren: Als we een model laten overerven van modelWithModifier moet elke save van dat model await worden

2021-01-13 14:06 UTC, ValenberghsSven requested changes
Werkt nog niet zoals het moet.
Had lokaal even die fout attr verwijderd
Als je in die status zit (publicatie werd aangepast...) kan je wel documenten toevoegen. (omdat we die niet gaan toevoegen aan de publication-flow, maar aan de case triggert daar geen concurrency). Willen we dit blokkeren of niet ? Staat er op zich los van.

+ alle saves van publication-flow en activity moeten await worden, anders kom je mogelijk uit op self-concurrency in 1 tab

+ vertaling ontbreekt voor het model activity, hoe gaan we dat vertalingen aangezien er meerdere soorten mogelijk zijn
![image](https://user-images.githubusercontent.com/22245223/104463314-ea18d380-55b1-11eb-991c-73de7e1ad2e6.png)
Je blijft ook eindeloos steken in die spinner dan. Je moet nu wel refreshen want je zit vast

2021-01-13 14:06 UTC, ValenberghsSven commented on app/router.js
> +    this.route('done', { path: '/behandeld', }, function() {
Op development noemt de tab "Gepubliceerd"
willen we dat dan ook hier aanpassen ?

2021-01-13 14:06 UTC, ValenberghsSven commented on app/models/activity.js
> +  @attr('user') modifiedBy;
Is geen attr maar een belongsTo
Maar dit moet hier niet staan, die belongsTo is al gedefinieerd in ModelWithModifier. dus gewoon weghalen

2021-01-13 14:06 UTC, ValenberghsSven commented on app/models/publication-flow.js
> +  @attr('user') modifiedBy;
Is geen attr maar een belongsTo
Maar dit moet hier niet staan, die belongsTo is al gedefinieerd in ModelWithModifier.

2021-01-21 15:36 UTC, ValenberghsSven commented
Jenkins gaat hier altijd op falen om dat er backend changes bij zijn.

2021-02-02 13:54 UTC, woutersf commented
> Werkt nog niet zoals het moet.
> Had lokaal even die fout attr verwijderd
> Als je in die status zit (publicatie werd aangepast...) kan je wel documenten toevoegen. (omdat we die niet gaan toevoegen aan de publication-flow, maar aan de case triggert daar geen concurrency). Willen we dit blokkeren of niet ? Staat er op zich los van.
> 
> * alle saves van publication-flow en activity moeten await worden, anders kom je mogelijk uit op self-concurrency in 1 tab
De activities worden allemaal afgewacht.
Die van de publciation flows gebeuren inline, en hoeven misschien niet ge-await worden?
> * vertaling ontbreekt voor het model activity, hoe gaan we dat vertalingen aangezien er meerdere soorten mogelijk zijn
>   ![image](https://user-images.githubusercontent.com/22245223/104463314-ea18d380-55b1-11eb-991c-73de7e1ad2e6.png)

Ik heb de translation voor activity toegevoegd. Denk dat er voor de aparte activities niet echt vertalingen nodig zijn. Je hebt net een actie gedaan. Uiteindelijk horen die confirmation niet te volgen uit activites, maar uit de logica met een custom mededeling. Lijkt me een apart issue.

>   Je blijft ook eindeloos steken in die spinner dan. Je moet nu wel refreshen want je zit vast
> 
> Ik kon op tab 1 van drukproefaanvraag een document toevoegen
> daarna op tab 2 (zonder refresh) de publicatie aanvragen en dat lukt ook.
> Aangezien we de daar geen activity saven, maar eerder een nieuwe activity starten triggert die concurrency ook niet.
> Met als gevolg dat ik een publicatie heb gestart en het document is niet mee verstuurd.
> dit geval zou kunnen opgelost zijn als we een einddatum zouden saven, want de drukproef acitivity is eigenlijk afgerond als je overgaat naar een publicatieaanvraag, niet ?
> 

Hiermee ben ik niet mee.

> Dit zijn maar enkele voorbeeldjes, die concurrency goedkrijgen betekent ook veel testen op wat mogelijk is

2021-02-23 07:09 UTC, closed without merging