Feature/kas 2148 spoedprocedure
kanselarij-vlaanderen/frontend-kaleidos pull request #649
Opened 2021-01-11 11:12 UTC by woutersf

### 1. Related backend PR
https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/148
### 2. CRUD feature
<img width="233" alt="Screenshot 2021-01-11 at 12 10 41" src="https://user-images.githubusercontent.com/592312/104173510-27d8f900-5406-11eb-97ed-218838435754.png">
### 3. In overviews added
(muis verdwenen in screenshot)
 <img width="362" alt="Screenshot 2021-01-11 at 12 10 35 (3)" src="https://user-images.githubusercontent.com/592312/104173547-3a533280-5406-11eb-8686-e857d4c8368a.png">

2021-01-11 12:20 UTC, BenjaminDendas approved these changes

2021-01-13 11:16 UTC, ValenberghsSven requested changes
Bij ingetrokken publicaties lijkt het mij overbodig, maar het stoort niet.

Echter staat het wel op de foute plaats bij ingetrokken "niet via ministerraad":
![image](https://user-images.githubusercontent.com/22245223/104445274-3a376c00-5599-11eb-8fc4-931260c8e039.png)

2021-01-13 11:16 UTC, ValenberghsSven commented on app/pods/publications/withdrawn/withdrawn-minister/template.hbs
> +      </td>
Heeft het nut om dat ook te tonen bij ingetrokken publicatie?
Als het ingetrokken is lijkt het mij niet meer dringend

2021-01-13 11:18 UTC, ValenberghsSven commented on app/pods/publications/withdrawn/withdrawn-not-minister/template.hbs
> +      </td>
Moet 1 TD lager, na die met de drukproef

2021-01-13 11:18 UTC, ValenberghsSven commented on app/pods/publications/withdrawn/withdrawn-minister/template.hbs
> +      </td>
+ het staat fout 
Moet 1 TD lager, na die met de drukproef

2021-01-13 17:54 UTC, woutersf commented on app/pods/publications/withdrawn/withdrawn-minister/template.hbs
> +      </td>
De tabel is hetzelfde voor (en zal ook aangepast worden op) alle routes.
Of ze het veld willen zien zullen ze in de toekomst zelf kunnen kiezen. 
Op zich zal deze tabel in de nabije toekomst zowiezo aangepast worden.

2021-01-13 17:54 UTC, woutersf commented on app/pods/publications/withdrawn/withdrawn-minister/template.hbs
> +      </td>
Ik stel voor om het hier te laten staan.

2021-01-13 17:56 UTC, woutersf commented on app/pods/publications/withdrawn/withdrawn-not-minister/template.hbs
> +      </td>
Aangepast

2021-01-14 11:10 UTC, ValenberghsSven approved these changes

2021-01-14 11:11 UTC, merged