Feature/val 225 refactor document components
kanselarij-vlaanderen/frontend-kaleidos pull request #659
Opened 2021-01-14 10:32 UTC by erikap

Making document components more Data-Down-Actions-Up in preparation of model refactoring for submission activity

2021-01-22 08:20 UTC, woutersf commented
Zijn wat merge conflicts en testen die nog falen.
Dit lijkt me nog niet in orde.
<img width="1044" alt="Screenshot 2021-01-22 at 09 19 34" src="https://user-images.githubusercontent.com/592312/105465279-ff1cf300-5c92-11eb-85b1-6ee7932c7c54.png">

2021-01-28 14:30 UTC, BenjaminDendas requested changes
Functioneel enkele tests gedaan en is OK.

Ik heb echter wel mijn bemerkingen op de naamgevingen van sommige componenten.. Ik ben iemand die houd van uniformiteit en waar we nu over heel kaleidos het pad in de mappenstructuur volgen voor de naamgevingen (voor zover ik weet), wordt er hier ineens een andere naamgeving gebruikt.

Op zich niks mis mee maar als we zoiets doortrekken dan zou dat overal moeten beginnen te gebeuren.. anders kan iedereen de routes beginnen noemen zoals hij wilt.

Anderzijds lijken me sommige components een grotendeelse copy-paste waardoor de naamgeving geen match is met de folder waarin het inzit.. lijkt me goed om dit ook nog aan te passen.

2021-01-28 14:30 UTC, BenjaminDendas commented on app/pods/components/web-components/au-loader/template.hbs
> +  <div class="auk-loader-wrapper">
Waarom is hier de `auk-loader-wrapper--small` weg? Dit geeft nu terug een grote loader terwijl dit niet volgens het design is.
![image](https://user-images.githubusercontent.com/11557630/106146407-ed49bd00-6176-11eb-94e3-8d9fded35662.png)

2021-01-28 14:30 UTC, BenjaminDendas commented on app/pods/components/documents/linked-documents/component.js
> +  @service currentSession;
Moet dit niet `LinkedDocuments` zijn?

2021-01-28 14:30 UTC, BenjaminDendas commented on app/pods/components/documents/batch-document-edit/component.js
> +export default class DocumentList extends Component {
Moet dit niet `BatchDocumentEdit` noemen?

2021-01-28 14:30 UTC, BenjaminDendas commented on app/pods/cases/case/subcases/subcase/documents/route.js
> +export default class DocumentsSubcaseSubcasesRoute extends Route {
Zou dit niet eerder `subcasesSubcaseDocuments` noemen zodat dit in lijn ligt met de rest van de applicatie?

2021-01-28 14:30 UTC, BenjaminDendas commented on app/pods/cases/case/subcases/subcase/documents/controller.js
> +export default class DocumentsSubcaseSubcasesController extends Controller {
zelfde opmerking als bij de route

2021-01-28 14:30 UTC, BenjaminDendas commented on app/pods/agenda/documents/controller.js
>    @service currentSession;
`AgendaDocumentsController` ?

2021-01-29 08:13 UTC, MikiDi commented on app/pods/components/web-components/au-loader/template.hbs
> +  <div class="auk-loader-wrapper">
Moet er ergens met een merge tussengeglipt zijn :thinking: ... aangepast.

2021-01-29 08:14 UTC, MikiDi commented on app/pods/components/documents/linked-documents/component.js
> +  @service currentSession;
:heavy_check_mark: Class names aangepast naar hoe de cli ze zou genereren.

2021-02-12 10:36 UTC, MikiDi approved these changes

2021-02-12 14:56 UTC, ValenberghsSven reviewed
Ik heb wat getest en niet direct problemen gevonden, enkel dat die detail view die renderdetails kwijt is

2021-02-12 14:56 UTC, ValenberghsSven commented on app/pods/components/agenda/agenda-detail/sidebar-item/template.hbs
> -              {{#if this.renderDetails}}
Waarom is deze eruit ? dit was een fix dat de detailview ineens al deze data gaat ophalen voor alle agendapunten, ook al zijn die niet in view

2021-02-12 14:56 UTC, ValenberghsSven commented on app/pods/components/agenda/agenda-detail/sidebar-item/component.js
> -
Waarom is deze eruit ? dit was een fix dat de detailview ineens al deze data gaat ophalen voor alle agendapunten, ook al zijn die niet in view

2021-02-12 14:56 UTC, ValenberghsSven commented on app/pods/components/agenda/agenda-detail/sidebar-item/component.js
> -
Waarom is deze eruit ? dit was een fix dat de detailview ineens al deze data gaat ophalen voor alle agendapunten, ook al zijn die niet in view

2021-02-12 14:56 UTC, ValenberghsSven commented on app/pods/components/agenda/agenda-detail/sidebar-item/template.hbs
>      <span class="vlc-agenda-detail-sidebar-sub-item__numbering">
Waarom is deze eruit ? dit was een fix dat de detailview ineens al deze data gaat ophalen voor alle agendapunten, ook al zijn die niet in view

2021-02-14 18:17 UTC, erikap commented
@ValenberghsSven Uw opmerking over het verwijderen van de `renderDetails` in `app/pods/components/agenda/agenda-detail/sidebar-item/template.hbs` wat correct. Ik heb dit terug toegevoegd.

2021-02-17 10:16 UTC, woutersf commented
Kan gemerged worden na oplossen Conflicting files
app/pods/components/documents/document-link/component.js
app/pods/components/web-components/au-loading-overlay/template.hbs
cypress/support/commands/document-commands.js

2021-02-17 10:29 UTC, merged