refactor: access-level component to glimmer + minor arg naming changes
kanselarij-vlaanderen/frontend-kaleidos pull request #663
Opened 2021-01-16 16:58 UTC by MikiDi

Refactoring of the access-level component to glimmer component. In preparation of refactor of the document-card component.
Automated testing in progress

2021-01-22 08:17 UTC, woutersf commented
<img width="1221" alt="Screenshot 2021-01-22 at 09 16 14" src="https://user-images.githubusercontent.com/592312/105464923-933a8a80-5c92-11eb-96e6-0ec807745b8a.png">
<img width="1266" alt="Screenshot 2021-01-22 at 09 16 24" src="https://user-images.githubusercontent.com/592312/105464940-97ff3e80-5c92-11eb-948c-8a4434e88eaf.png">
<img width="844" alt="Screenshot 2021-01-22 at 09 16 37" src="https://user-images.githubusercontent.com/592312/105464943-9897d500-5c92-11eb-9d75-506ac936d84c.png">
Lijkt nog een en ander uit de haak met de filesen de propagation?

2021-01-28 16:42 UTC, BenjaminDendas requested changes
Bug gevonden wanneer je de status aanpast dan worden de pills niet overal geupdate waar ze geupdated moeten worden.

![image](https://user-images.githubusercontent.com/11557630/106169177-5f2e0080-618f-11eb-970d-e3cd634a2d70.png)

2021-01-29 08:47 UTC, MikiDi commented
Terechte opmerking, thanks. Ik bekijk of 't op te lossen valt zonder deze component data down actions up te refactoren. Ik zet 'm momenteel even in draft.

2021-01-29 10:24 UTC, MikiDi commented
Ik sluit deze af wegens te moeilijk om te refactoren zonder ook document-card onder handen te nemen. Ik steek deze mee in https://github.com/kanselarij-vlaanderen/kaleidos-frontend/tree/feature/document-card-refactor .

2021-01-29 10:24 UTC, closed without merging