VAL-150 reload newsitem when saving agendaitem
kanselarij-vlaanderen/frontend-kaleidos pull request #667
Opened 2021-01-20 13:42 UTC by Annelies-P

2021-01-25 15:51 UTC, BenjaminDendas requested changes
Dit lijkt me niet de correcte aanpak, waarom willen we hier de frontend laten wachten op een propagatie van een backend-feature?? Lijkt me eerder om iets aan te pakken in de backend niet? Ik vind dit echt vuil.

We hebben momenteel 2 setTimeout's in de codebase en wil er liefst geen bij krijgen. We wachten hier 1000 ms, hoe weten we uberhaupt dat dit op alle omgevingen voldoende gaat zijn? Er wordt hier maar gewoon een getal op geplakt in de hoop dat het werkt, not done.

`
if (this.newsletterInfo && this.newsletterInfo.get('hasDirtyAttributes')) {
        	        await this.newsletterInfo.save();
   }
`
`this.newsletterInfo` kan null zijn, wanneer er nog geen nieuwsbrief aangemaakt is, het stuk code zou waarschijnlijk ook in de `if` moeten staan.

2021-01-25 17:28 UTC, erikap commented
@BenjaminDendas Ik ga deze PR nog verder bekijken, maar kan je even verduidelijken wat je bedoelt met "Lijkt me eerder om iets aan te pakken in de backend niet?". Hoe zou jij dat dan aanpakken?

2021-01-26 12:03 UTC, Annelies-P commented
@BenjaminDendas In de bestaande if hoort het niet thuis aangezien de 2e conditie niet van toepassing is op deze use case. Maar een null check kan idd best worden toegevoegd.
Daarnaast 'wacht' de frontend niet op de reload, dus zie ik jouw punt niet. De reload moet gedaan worden om ervoor te zorgen dat de getoonde data in sync is met de backend data. Het lijkt mij vuiler data te tonen die niet meer up-to-date is dan het op deze manier op te lossen. Ik zie ook niet hoe dit momenteel kan opgelost worden in de backend binnen de scope van dit issue?

2021-01-26 12:41 UTC, MikiDi commented
Voor redenen (waarvan ik de details niet ken) is het best dat de timeout mee in de ember runloop opgenomen wordt. Zie [later - @ember/runloop](https://api.emberjs.com/ember/3.24/functions/@ember%2Frunloop/later) (meer uitleg [op embermap](https://embermap.com/topics/async-testing/instead-of-settimeout-use-run-later)). Verder zou het natuurlijk cool zijn moesten we push updates hebben, maar da's niet voor hier ... Goed voor mij.

2021-01-26 12:41 UTC, MikiDi approved these changes

2021-01-27 09:10 UTC, ValenberghsSven commented
Ik heb hier 1 minuut getest en kan een error produceren
![image](https://user-images.githubusercontent.com/22245223/105968838-df693e80-6087-11eb-90ae-ef73d4dc8259.png)

2021-01-27 09:44 UTC, ValenberghsSven requested changes
Mijn bedenkingen:
Wat ik afleid uit de code hier en de sync service is dat we de titel en inhoud van kort bestek willen updaten als die van agendaitem zijn geupdate.
Dit enkel bij mededelingen omdat de mensen met van kort-bestek daar niet naar kijken.

Dit kan perfect allemaal bij in deze component.
Als nieuwsbrief bestaat en het agendaitem is een mededeling, dan doen we gewoon een set van die attributen hier? We hebben alle informatie om dit te doen.

Die newsitem-sync-service zit ook heel veel select queries te doen voor niks, 50 select queries op enkele minuten tijd, en dan heb ik nog niet veel edits gedaan.

```
if (this.newsletterInfo && this.args.agendaitem.showAsRemark) {
      this.newsletterInfo.set('richtext', trimText(this.args.agendaitem.title));
      this.newsletterInfo.set('title', trimText(this.args.agendaitem.shortTitle));
    }
```

Dit blokje van 4 lijnen doet wat die hele delta/microservice setup moet doen zonder de overhead.

note: Eventueel deze overschrijving optioneel maken ? 
Nu is dat altijd bij aanpassing van edits van een mededeling.
Maar stel nu dat persoon x van kanselarij het kort-bestek heeft aangevuld met extra tekst, en persoon y voegt ergens een puntje toe bij de tekst van agendaitem.
Dan is persoon x zijn werk ineens weg.

2021-01-27 10:20 UTC, MikiDi commented
Ik heb dit bij aanmaken van de story ws verkeerd ingeschat. Ik had geen duidelijk genoeg beeld van het aantal plaatsen in de frontend waar je de titel van agendapunt kan aanpassen (minstens 2 plaatsen dacht ik).  
Als het op meerdere plaatsen is, wil je niet zitten bijhouden waar overal in de frontend je tegelijk dat nieuwsbericht moet aanpassen ("separation of concern"). Dat was mijn gedachtengang. Nu dat blijkt dat er maar 1 plaats in de interface is waar je die agendapunt titel kan wijzigen, ziet dat er wat knullig uit. Als we weten dat er binnen voorzienbare tijd geen extra plaatsen bij gaan komen waar je de titel van het agendapunt wijzigt, pakken we het beter aan zoals @ValenberghsSven suggereert.
(de `reload` moet inderdaad conditioneel zijn op het bestaan van `this.newsletterInfo`)

2021-02-04 07:59 UTC, closed without merging

2021-02-04 08:00 UTC, Annelies-P commented
de oplossing zal volledig in de frontend worden geimplementeerd zonder gebruik van een microservice