KAS-2182 drukproef aanvragen layout aanpassen (modal)
kanselarij-vlaanderen/frontend-kaleidos pull request #668
Opened 2021-01-21 08:56 UTC by brechtPhilips

## KAS-2182 : drukproef aanvragen layout aanpassen (modal)

Drukproef aanvragen layout aanpassen (modal)

# Screenshot:
![Screenshot 2021-01-21 at 09 56 15](https://user-images.githubusercontent.com/22370478/105327210-e8ad6380-5bce-11eb-87d1-b0c07297af84.png)

2021-01-21 09:22 UTC, woutersf approved these changes

2021-01-21 10:45 UTC, BenjaminDendas requested changes
Op zich goed, ik heb net de design van de effectieve drukproefaanvraag erbij genomen.. de info tekst bovenaan mag nog weg, dan in orde.
![image](https://user-images.githubusercontent.com/11557630/105340377-164dd900-5bde-11eb-90d3-36215eedfa5f.png)

2021-01-22 08:13 UTC, woutersf commented
> Op zich goed, ik heb net de design van de effectieve drukproefaanvraag erbij genomen.. de info tekst bovenaan mag nog weg, dan in orde.
> ![image](https://user-images.githubusercontent.com/11557630/105340377-164dd900-5bde-11eb-90d3-36215eedfa5f.png)

Heb dat rap aangepast. 
@brechtPhilips  Check je en merge je?

2021-01-22 08:14 UTC, woutersf approved these changes

2021-01-22 12:07 UTC, BenjaminDendas approved these changes

2021-01-25 15:23 UTC, merged