Featur/kas 2183 vertaalaanvraag onafgewerkt aangeven
kanselarij-vlaanderen/frontend-kaleidos pull request #672
Opened 2021-01-21 15:13 UTC by brechtPhilips

## KAS-2183

- Request panel aangepast naar de nieuwe designs.

# Vertaalaanvragen
![Screenshot 2021-01-21 at 16 10 35](https://user-images.githubusercontent.com/22370478/105369813-347a0000-5c03-11eb-8577-3c41f45b1f85.png)
![Screenshot 2021-01-21 at 16 10 51](https://user-images.githubusercontent.com/22370478/105369850-3cd23b00-5c03-11eb-8a78-ed751e8463ef.png)
![Screenshot 2021-01-21 at 16 12 35](https://user-images.githubusercontent.com/22370478/105370071-7a36c880-5c03-11eb-9a02-4c9643885a4b.png)

# Drukproefaanvraag
![Screenshot 2021-01-21 at 16 11 38](https://user-images.githubusercontent.com/22370478/105369958-58d5dc80-5c03-11eb-800d-2e9fdb224923.png)
![Screenshot 2021-01-21 at 16 11 51](https://user-images.githubusercontent.com/22370478/105369977-5ffcea80-5c03-11eb-956b-df3d9360c617.png)
![Screenshot 2021-01-21 at 16 12 15](https://user-images.githubusercontent.com/22370478/105370029-6e4b0680-5c03-11eb-9954-cffba74c8f6c.png)

2021-01-22 08:09 UTC, woutersf approved these changes

2021-01-22 11:14 UTC, BenjaminDendas requested changes

2021-01-22 11:14 UTC, BenjaminDendas commented on app/pods/components/publications/publication/activity-request-panel/component.js
> +    return false;
Deze code lijkt me een beetje vuil.. om het iets properder te maken kan je het misschien `modus` noemen en checken t.o.v. een generieke modus ipv een rechtstreekse implementatie van isVertaling. Stel je voor dat handtekenen een gelijkaardige view heeft, dan zou je hier je logica al moeten aanpassen omdat je jezelf zo gelimiteerd hebt in keuzes.

2021-01-22 11:14 UTC, BenjaminDendas commented on app/pods/components/publications/publication/activity-request-panel/template.hbs
> +            {{/if}}
Hier ga je de opmerking van hierboven ook moeten aanpassen.

2021-01-25 15:33 UTC, BenjaminDendas requested changes
Dit werkt nog niet volledig, als je een aanvraag aanvinkt als `afgewerkt` en hem erna terug uitvinkt.. dan blijft de checkbox te staan alsof hij `afgewerkt` is.

2021-01-28 16:28 UTC, BenjaminDendas requested changes
Nog enkele general opmerkingen, voor de rest zeker in orde kwa functionaliteit

2021-01-28 16:28 UTC, BenjaminDendas commented on app/pods/components/publications/publication/activity-request-panel/component.js
> +  @tracked checked;
Ik zou dit `finished` noemen ofzo.. vanaf het moment dat er een nieuwe checkbox bijkomt op deze view dan gaat dit verwarrend zijn.

2021-01-28 16:28 UTC, BenjaminDendas commented on app/pods/components/publications/publication/activity-request-panel/component.js
> +    return false;
Dit kunnen we one-linen als ik me niet vergis `return this.args.mode === 'translation'` en ik zou de getter dan `isTranslation` noemen bijvoorbeeld.

2021-01-28 16:28 UTC, BenjaminDendas commented on app/pods/publications/publication/publishpreview/controller.js
> +      previewActivity.endDate = undefined;
Ik zou hier ipv `undefined` , `null` gebruiken. Ik heb hier net even wat over opgezocht en kan me wel vinden in de denkwijze van de `most upvoted persoon` https://stackoverflow.com/questions/461966/why-is-there-a-null-value-in-javascript

`undefined` houden voor speciale gevallen en/of waardes die gedeclareerd zijn maar nog geen assignment gehad hebben. Als we die redenering doortrekken naar dit, dan zou hier `null` moeten staan want je had bv al een endDate kunnen hebben.

2021-01-28 16:28 UTC, BenjaminDendas commented on app/pods/publications/publication/translations/controller.js
> +      translationActivity.endDate = undefined;
Idem zoals de vorige undefined.

2021-01-28 16:28 UTC, BenjaminDendas commented on app/pods/components/publications/publication/activity-request-panel/component.js
> +    this.fetchClosedStatus();
We wachten hier niet op de status, we zijn zeker dat de checkbox altijd correct geset zal zijn?

2021-01-29 10:42 UTC, BenjaminDendas approved these changes

2021-01-29 10:43 UTC, merged