KAS-2195: lock interface while uploading multiple files
kanselarij-vlaanderen/frontend-kaleidos pull request #675
Opened 2021-01-26 07:53 UTC by woutersf

### 🎬 How does it work?
![multi_file_upload_block_interface480](https://user-images.githubusercontent.com/592312/105815907-ddce4680-5fb3-11eb-9b71-c96555bca477.gif)

### What did I do?
Added a interface blocker in the au upload component.

2021-01-28 13:12 UTC, BenjaminDendas requested changes
Good for me op deze plek but..

Beetje nitpicking: 
In het ticket stond dat het ook moest locken bij het uploaden van documenten vanuit de agenda, omdat deze het meeste gebruikt wordt, dat was de belangrijkste plaats. 

Uit het ticket:
```
We dienen te controleren dat dit zowel bij het uploaden van documenten voor de ministerraad als voor OVRB niet mogelijk is.
```

Mag voor mij in deze branch of in een andere idm. Als je het wilt doen in een ander ticket/branch dan mag deze er voor mij door.

@woutersf gechecked zoals besproken.. op de document uploader in de agenda:
![image](https://user-images.githubusercontent.com/11557630/106165515-7a970c80-618b-11eb-9d45-41cbfac14aa6.png)


We zouden moeten kijken of de oude componenten het mogelijk maken om deze allemaal op 1 plek te fixen omdat deze nog gecontainered zitten in andere componenten. 
Deze modal voor het uploaden van documenten komt namelijk nog enkele keren voor heb ik gezien, ook op de algemene documenten tab van de agenda.

![image](https://user-images.githubusercontent.com/11557630/106165800-c1850200-618b-11eb-80d0-46bc3c760cc1.png)

En een tab op de procedurestap.
![image](https://user-images.githubusercontent.com/11557630/106165853-d497d200-618b-11eb-8581-4f9e9b07aed5.png)

2021-02-02 11:13 UTC, woutersf commented
Aangepast
@brechtPhilips kan jij eens reviewen en mergen?

2021-02-12 16:38 UTC, ValenberghsSven requested changes
- Indien de uploader fullscreen is ziet de overlay er raar uit 
![image](https://user-images.githubusercontent.com/22245223/107795399-e4511200-6d58-11eb-8c5b-e1b5cb07b1df.png)


- Bij annuleren kan je nog steeds op de knop drukken ook al is die alles aan het queuen om te verwijderen, willen we bij annuleren ook een loader tonen ?

2021-02-12 16:38 UTC, ValenberghsSven commented on app/pods/components/web-components/au-file-uploader/component.js
> +      this.showLoader = true;
nergens een showLoader = false, maar toch verdwijnt die.
Willen we die ook niet in de finally ?

2021-02-12 16:48 UTC, ValenberghsSven commented
geupdate met dev, je hebt nu een progress bar bij de au-fileuploader

2021-02-16 15:27 UTC, woutersf commented
Heb bij annuleren ook die showloader gezet. 
Kan je ook niets doen terwijl die die files aan't deleten is.
Goeie catch @ValenberghsSven

2021-02-17 10:03 UTC, merged