Features/kas 2187 tabs vervangen door filter modal
kanselarij-vlaanderen/frontend-kaleidos pull request #676
Opened 2021-01-26 10:06 UTC by brechtPhilips

#KAS-2187: Tabs vervangen door filter modal

#Changes:
- Deleted tabs
- deleted unused routes,folders
- created publications.index route,template,controller
- insert filter querries .

# 🙈 Visual
## Data
![Screenshot 2021-01-26 at 11 05 11](https://user-images.githubusercontent.com/22370478/105830899-5d651100-5fc6-11eb-9406-d7cdfbec7cd7.png)

## Filter
![Screenshot 2021-01-26 at 11 05 40](https://user-images.githubusercontent.com/22370478/105830953-6eae1d80-5fc6-11eb-815d-23e64450b144.png)

# No data found
![Screenshot 2021-01-26 at 11 06 14](https://user-images.githubusercontent.com/22370478/105831022-82598400-5fc6-11eb-8519-0345fed23aad.png)

2021-01-28 12:22 UTC, woutersf approved these changes
Ik vind em wel cool.
Ook lokaal getest en werkt goed.
Als je een checkbox aanvinkt in die filter en je sluit dat venstertje dat die bewaard blijft dat vind ik wat raar.
Voor de rest ok. Kunnen we mee voort.
@brechtPhilips testen falen wel. je zal hiervoor mss toch eens naar de testen moeten zien.
Er zitten in de publication spec een aantal testen op routes die niet meer bestaan.
En we willen development graag 🟢

2021-01-28 12:24 UTC, woutersf requested changes
Als je de routes die verdwenen zijn ook nog uit de testen haalt. 
![q1g68](https://user-images.githubusercontent.com/592312/106138197-187adf00-616c-11eb-8af5-5e25e093fa95.jpg)

2021-01-28 16:04 UTC, BenjaminDendas requested changes
Ziet er mij goed uit. Ik zou inderdaad ook nog wel erin steken dat wanneer je op `Annuleren` of `X` drukt, de localstorage terug gezet wordt naar wat hij stond en dat de checkboxen ook terug correct uit/aangevinkt zijn.

2021-01-29 11:07 UTC, BenjaminDendas approved these changes

2021-02-02 07:43 UTC, merged