KAS-2159 invoeren minister niet via mr
kanselarij-vlaanderen/frontend-kaleidos pull request #685
Opened 2021-01-28 09:58 UTC by woutersf

### 🌌 Whats inside?
Linking and unlinking mandatees to publication-flows.

### 🔗 linked BACKEND PR
https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/159

### 🕋 Datamodel
<img width="491" alt="Screenshot 2021-01-28 at 08 19 30" src="https://user-images.githubusercontent.com/592312/106109843-464f2c00-614a-11eb-9af6-8e79f817fec6.png">

### 🌅 Screenshots
<img width="1337" alt="Screenshot 2021-01-28 at 09 12 28" src="https://user-images.githubusercontent.com/592312/106109898-57983880-614a-11eb-8308-c7965a5e5279.png">
<img width="1328" alt="Screenshot 2021-01-28 at 09 11 36" src="https://user-images.githubusercontent.com/592312/106109904-5a932900-614a-11eb-8e98-3c8d55e40c4a.png">
<img width="1335" alt="Screenshot 2021-01-28 at 09 11 32" src="https://user-images.githubusercontent.com/592312/106109906-5b2bbf80-614a-11eb-9b50-30ad6cc15518.png">

2021-01-28 15:36 UTC, BenjaminDendas requested changes
Als je een minister toegevoegd hebt, blijft de selectie geselecteerd, dat willen we hier niet.
![image](https://user-images.githubusercontent.com/11557630/106157841-68b16b80-6183-11eb-9a09-157acec408ae.png)

Momenteel wordt de minister ook direct gesaved wanneer je een minister selecteerd. Ik denk niet dat dit het gewenste behaviour is omdat we reeds een `Toevoegen` knop hebben staan. Dit lijkt me eerder een vraag voor JR though..

Indien we de toevoegen knop toch behouden:
Ik zou de knop nog disablen als je geen minister geselecteerd hebt.. nu kan je gewoon klikken op toevoegen en geeft hij zelf save popups.

![image](https://user-images.githubusercontent.com/11557630/106158176-c5148b00-6183-11eb-9846-7d2bdacc47f4.png)

Zouden we bij het verwijderen ook niet best om een bevestiging vragen ipv direct de actie uit te voeren?

2021-01-28 15:36 UTC, BenjaminDendas commented on app/pods/publications/publication/case/template.hbs
> +          <WebComponents::AuPanel::Body @noPadding="true">
Via ministerraad lijkt er toch nog iets niet volledig correct te verlopen.

Als ik een nieuwe agenda maak met een nieuw dossier en een nieuwe procedurestap en ik agendeer deze op de nieuwe agenda, dan krijg ik nog de header `minister` te zien.. hier willen we eigenlijk de `emtpy state` lijkt me. 

Ik vermoed dat het hier dus nog ergens foutloopt?

![image](https://user-images.githubusercontent.com/11557630/106159231-db6f1680-6184-11eb-8829-bd4de69fba09.png)

Wanneer ik een minister toevoeg vanuit de agenda komt deze wel mooi bij in de publicatieflow.. Enkel de empty state toont daar nog niet correct.

2021-01-28 16:23 UTC, woutersf commented
> Als je een minister toegevoegd hebt, blijft de selectie geselecteerd, dat willen we hier niet.
> ![image](https://user-images.githubusercontent.com/11557630/106157841-68b16b80-6183-11eb-9a09-157acec408ae.png)

Zit er in.

2021-01-28 16:27 UTC, woutersf commented
Ook clicken op minister nog aangepast met knopje (das wat je bedoelde zeker @BenjaminDendas ?)
Zit er in!

2021-02-02 08:09 UTC, brechtPhilips approved these changes

2021-02-02 08:11 UTC, merged