KAS-2128: status-afgevoerd
kanselarij-vlaanderen/frontend-kaleidos pull request #715
Opened 2021-02-17 15:41 UTC by woutersf

<img width="308" alt="Screenshot 2021-02-17 at 16 34 50" src="https://user-images.githubusercontent.com/592312/108228130-dc211a00-713e-11eb-952e-3d62445466a5.png">
<img width="499" alt="Screenshot 2021-02-17 at 16 35 28" src="https://user-images.githubusercontent.com/592312/108228138-ddeadd80-713e-11eb-8647-f0775b0d2a1f.png">
👆🏻
Is veranderd in 
👇🏻
<img width="503" alt="Screenshot 2021-02-17 at 16 36 53" src="https://user-images.githubusercontent.com/592312/108228147-df1c0a80-713e-11eb-8d9a-7fad7b06fc90.png">
<img width="315" alt="Screenshot 2021-02-17 at 16 39 38" src="https://user-images.githubusercontent.com/592312/108228151-e04d3780-713e-11eb-8046-6ba09ae22af3.png">

2021-02-18 09:34 UTC, woutersf commented
🟢 in Jenkins!

2021-02-22 11:00 UTC, ValenberghsSven requested changes
De publicationStatus aanpassen in config is niet voldoende.
Graag ook migratie van de data
```
DELETE DATA
pubstatusid:9b9b0b5e-45c8-11eb-b378-0242ac130002 skos:prefLabel "Ingetrokken"@nl .

INSERT DATA
pubstatusid:9b9b0b5e-45c8-11eb-b378-0242ac130002 skos:prefLabel "Afgevoerd"@nl .
```

Het aanpassen van ingetrokken naar afgevoerd gaat in het ticket over de publicatie.
Echter zijn er keys aangepast die slagen op de aanvragen voor vertalingen etc. Is dit de bedoeling ?
Ik ging ervan uit dat enkel een publicatie afgevoerd moest kunnen zijn.
Aanvragen intrekken lijkt nog wel correct ?

2021-02-22 11:00 UTC, ValenberghsSven commented on translations/nl-be.json
> +  "withdraw": "Afvoeren",
Withdraw vertaald naar afvoeren, dat klinkt niet juist
Aangezien de sleutel "withdraw" enkel gebruikt wordt in publicatie zou ik ook de vertaling van afvoeren gebruiken voor minder verwarring te hebben.
"eliminate", "discharge", "scrap", "cancel" zijn mogelijke kandidaten maar matchen ook niet 1 op 1 ....
echter is "cancel" al in gebruik met "Annuleren"

2021-02-22 11:00 UTC, ValenberghsSven commented on translations/nl-be.json
>    "cancel-request": "Aanvraag intrekken",
aanvraag afvoeren of is dit nog iets anders ?

2021-02-23 06:35 UTC, woutersf commented on translations/nl-be.json
>    "cancel-request": "Aanvraag intrekken",
Aanvragen gaan over vertalings of drukproefaanvragen he, daar gaat dit niet over.

2021-02-23 06:45 UTC, woutersf commented on translations/nl-be.json
> +  "withdraw": "Afvoeren",
Replaced withdrawn (voor publications) met discharged

2021-02-23 06:57 UTC, woutersf commented
> De publicationStatus aanpassen in config is niet voldoende.
> Graag ook migratie van de data
> 
> ```
> DELETE DATA
> pubstatusid:9b9b0b5e-45c8-11eb-b378-0242ac130002 skos:prefLabel "Ingetrokken"@nl .
> 
> INSERT DATA
> pubstatusid:9b9b0b5e-45c8-11eb-b378-0242ac130002 skos:prefLabel "Afgevoerd"@nl .
> ```
> 
> Het aanpassen van ingetrokken naar afgevoerd gaat in het ticket over de publicatie.
> Echter zijn er keys aangepast die slagen op de aanvragen voor vertalingen etc. Is dit de bedoeling ?
> Ik ging ervan uit dat enkel een publicatie afgevoerd moest kunnen zijn.
> Aanvragen intrekken lijkt nog wel correct ?

PR toegevoegd en copy changes doorgevoerd

2021-02-23 10:29 UTC, merged