KAS-2212: fix relation from case to multiple publicationflows
kanselarij-vlaanderen/frontend-kaleidos pull request #759
Opened 2021-02-23 13:32 UTC by woutersf

### backend PR:
https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/171

### screenshots
<img width="1661" alt="Screenshot 2021-02-23 at 14 31 07" src="https://user-images.githubusercontent.com/592312/108850627-dc5c6200-75e3-11eb-8376-7ffb1b9fd0ff.png">

<img width="1327" alt="Screenshot 2021-02-23 at 14 31 02" src="https://user-images.githubusercontent.com/592312/108850615-d9617180-75e3-11eb-88d1-2947d9c83d99.png">

2021-02-23 14:16 UTC, woutersf commented
Custom BE + FE build in http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/27/

2021-02-23 15:29 UTC, ValenberghsSven commented
Dit mergen zal er wel voor zorgen dat die knop ook in PROD gaat zichtbaar zijn, maar daar is dat nog niet aan de orde.
Dus voorlopig moeten we daar wel een feature flag rondzetten, zodat die changes nog niet op prod te zien zijn.

2021-02-24 06:58 UTC, woutersf commented
🟢 yess

2021-02-24 09:00 UTC, ValenberghsSven requested changes
Wrappen met feature flags, dit willen we nog niet op prod hebben

2021-02-24 09:17 UTC, woutersf commented
> Wrappen met feature flags, dit willen we nog niet op prod hebben

zit er in!

2021-03-03 14:08 UTC, ValenberghsSven requested changes
Niet mergebaar in huidige staat.
Nieuwe design moet worden geimplementeerd en de search op publicatie overzicht werkt niet meer.

2021-04-06 15:54 UTC, erikap commented
Opstarten van een publication flow vanuit een MR is volledig geredesigned. Deze PR is niet meer relevant.

2021-04-06 15:54 UTC, closed without merging