Feature/kas 2461 codelijst urgentieniveau
kanselarij-vlaanderen/frontend-kaleidos pull request #817
Opened 2021-04-09 12:55 UTC by TaneeG

Pull request for ticket https://kanselarij.atlassian.net/browse/KAS-2461

2021-04-09 16:13 UTC, erikap requested changes

2021-04-09 16:13 UTC, erikap commented on app/models/publication-flow.js
> +  @computed('urgencyLevel')
In een native class is de `@computed` niet noodzakelijk bij een `get` function. Je hebt dit vermoedelijk overgenomen van `get publicationNumberToDisplay()` maar ook daar is ze overbodig.

2021-04-09 16:13 UTC, erikap commented on app/pods/publications/index/template.hbs
> +            {{#if row.hasUrgencyLevel}}
De `hasUrgencyLevel` is hier wat overbodig. Je kan ook gewoon checken op `{{row.urgencyLevel}}` in de template. De `hasUrgencyLevel` getter in het model kan dan ook verwijderd worden

2021-04-09 16:13 UTC, erikap commented on app/pods/publications/publication/controller.js
> +
Probeer dubbele newlines te vermijden :-)

2021-04-09 16:13 UTC, erikap commented on app/pods/publications/publication/controller.js
> +  toggleUrgencyLevel(urgencyLevel) {
Misschien is `setUrgencyLevel` hier een betere naam?

2021-04-09 16:13 UTC, erikap commented on app/components/publications/urgency-level-checkbox.hbs
> +  {{#if this.urgencyLevels}}
Je wil hier wachten tot de volledige `loadData` taak afgewerkt is zodat ook `this.checkboxValue` geinitialiseerd is. Je kan hiervoor de derived state van ember-concurrency gebruiken (http://ember-concurrency.com/docs/derived-state/)

2021-04-12 13:05 UTC, ValenberghsSven commented
frontend / backend hebben elk een eigen ticket, maar zijn wel afhankelijk van elkaar
Bijhorende PR:
https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/179

2021-04-12 13:10 UTC, ValenberghsSven commented
Er is al een tijdje een probleem dat ik de jenkins builds niet meer met github gelinkt krijg.
Maar deze branch faalt op linter errors

2021-04-12 13:11 UTC, ValenberghsSven commented
![Uploading image.png…]()

2021-04-12 13:13 UTC, ValenberghsSven commented
@TaneeG 
Om problemen met linter te vermijden, run het pre-commit.sh script (kaleidos-frontend/scripts)
Dan gaat de linter bij elke commit (enkel deze repo) lopen, en kan je geen linter errors meer committen.

2021-04-12 14:45 UTC, ValenberghsSven requested changes
Development nog binnenhalen, er zijn conflicten + de checkboxen zien er raar uit en daar is een fix voor gebeurd op dev.

Code werkt niet helemaal.
Een publicatie met spoedprocedure kan je aanvinken en automatisch saven, maar na refresh is de checkbox niet aangevinkt terwijl de data wel ok is.
Komt doordat de promise van de relatie niet is fulfilled bij data load in je component

2021-04-12 14:45 UTC, ValenberghsSven commented on app/components/publications/urgency-level-checkbox.hbs
> +  {{#if loadData.last.isSuccessful}}
Ben niet helemaal mee waarvoor die `.last` hier nodig is.
In andere componenten testen we dit af met
`{{#unless this.loadData.isRunning}}`
Mogelijk willen we dat ook hier doen?

2021-04-12 14:45 UTC, ValenberghsSven commented on app/components/publications/urgency-level-checkbox.js
> +    this.initializeUrgency(this.args.urgencyLevel);
this.args.urgencylevel is een promise, die moet je dus ook yielden (of beter inladen in de parent route/component door bvb de data loading in de route uit te breiden)

2021-04-12 14:45 UTC, ValenberghsSven commented on app/components/publications/urgency-level-checkbox.js
> +    this.initializeUrgency(this.args.urgencyLevel);
die initializeUrgency kan je korter schrijven (vervangen) door dit bij in de loadData method te zetten
```
const urgencyLevel = yield this.args.urgencyLevel;
this.checkboxValue = urgencyLevel.get('uri') === CONFIG.URGENCY_LEVELS.spoedprocedure;
```

2021-04-12 14:45 UTC, ValenberghsSven commented on app/components/publications/urgency-level-checkbox.js
> +
whitespace mag hier weg

2021-04-12 14:45 UTC, ValenberghsSven commented on app/models/urgency-level.js
> +  @attr('string') position;
zie ook project branch, `attr('number') position` ?

2021-04-12 14:45 UTC, ValenberghsSven commented on app/pods/publications/publication/controller.js
> +
Deze getter wordt niet gebruikt

2021-04-12 14:45 UTC, ValenberghsSven commented on app/pods/publications/publication/template.hbs
> +                      @urgencyLevel={{ this.model.publicationFlow.urgencyLevel }}
Deze relatie is nog niet geladen, dus je stuurt hier een promise naar je component.
Moet hier die getter gebruikt worden ?

2021-04-13 07:32 UTC, MikiDi commented
> Om problemen met linter te vermijden, run eenmalig het pre-commit.sh script (kaleidos-frontend/scripts).
> Die vervangt/creëert de pre-commit hook, dan gaat de linter bij elke commit lopen (enkel deze repo) en kan je geen linter errors meer committen.

Een `sh`-script runnen zal voor @TaneeG op Windows niet werken. We kunnen wel manueel de pre-commit hook installeren. Voor het maken van een PR nog eens `npm run lint` draaien is ook altijd een optie ;-)

2021-04-13 07:35 UTC, ValenberghsSven commented
> > Om problemen met linter te vermijden, run eenmalig het pre-commit.sh script (kaleidos-frontend/scripts).
> > Die vervangt/creëert de pre-commit hook, dan gaat de linter bij elke commit lopen (enkel deze repo) en kan je geen linter errors meer committen.
> 
> Een `sh`-script runnen zal voor @TaneeG op Windows niet werken. We kunnen wel manueel de pre-commit hook installeren. Voor het maken van een PR nog eens `npm run lint` draaien is ook altijd een optie ;-)

Ah ik wist niet dat zij op windows zat. dat sh script doet op zich niet veel, dat kopieert gewoon de commit hook van de frontend folder naar de juiste git folder lokaal en dat kan je ook manueel doen
`cp scripts/pre-commit .git/hooks/pre-commit`

2021-04-13 11:34 UTC, erikap requested changes

2021-04-13 11:34 UTC, erikap commented on app/components/publications/urgency-level-checkbox.js
> +  }
Dit zou ik als `get` function op het model van `urgency-level` definieren. Dan kan je die gebruiken in de template van de `urgency-level-checkbox.hbs` maar ook in `app/pods/publications/index/template.hbs`

2021-04-13 11:34 UTC, erikap commented on app/pods/publications/index/template.hbs
> +            {{#if (eq row.urgencyLevel.uri urgencyLevels.spoedprocedure)}}
Zie vorige comment dat je hier de `get isUrgent` function van het model zou kunnen gebruiken

2021-04-13 11:34 UTC, erikap commented on app/pods/publications/publication/route.js
> +    controller.urgencyLevel = this.urgencyLevel;
Dit is wat vreemd om te doen. Waarom wil je dit als aparte property op de controller definieren en gebruik je niet `model.publicationFlow.urgencyLevel`? 
In de action-handler `setUrgencyLevel` ga je `this.model.publicationFlow.urgencyLevel` aanpassen, waardoor `controller.urgencyLevel` niet meer de correcte waarde bevat.

2021-04-13 11:49 UTC, erikap commented on app/pods/publications/publication/route.js
> +    controller.urgencyLevel = this.urgencyLevel;
Offline met @MikiDi besproken. Dit is om te vermijden dat promises als argument doorgegeven worden aan een component. Er moet dus enkel gezorgd worden dat ook `controller.urgencyLevel` aangepast wordt in de action-handler `setUrgencyLevel`.

2021-04-13 16:31 UTC, MikiDi commented on app/models/urgency-level.js
>  export default class UrgencyLevel extends Model {
Hier nog een vrij lijntje? :innocent:

2021-04-13 16:32 UTC, MikiDi commented
Nog 1 kleine stijlbemerking gezet. Verder klaar om te mergen voor mij :+1:

2021-04-14 05:44 UTC, TaneeG commented on app/models/urgency-level.js
>  export default class UrgencyLevel extends Model {
Fixed :)

2021-04-14 06:40 UTC, MikiDi approved these changes

2021-04-14 07:30 UTC, erikap commented on app/pods/publications/publication/route.js
> +  async setupController(controller) {
Deze moet niet async zijn. Voor de rest in orde voor mij.

2021-04-15 08:26 UTC, ValenberghsSven approved these changes

2021-04-15 08:28 UTC, merged