KAS-2490: clickable agenda-item to subcase nav-link
kanselarij-vlaanderen/frontend-kaleidos pull request #829
Opened 2021-04-13 09:23 UTC by MikiDi

[KAS-2490](https://kanselarij.atlassian.net/browse/KAS-2490). Note that a straight `LinkTo` is used instead of the `AuButtonLink`, since that doesn't support the `tertiary` (fine gray border) skin. `AuButton` should be extended in the furture to support `LinkTo` params as well.

2021-04-14 08:06 UTC, ValenberghsSven requested changes

2021-04-14 08:06 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> -                data-test-agendaitem-titles-to-subcase
test selector nog in de LinkTo zetten, testen falen omdat de selector weg is

2021-04-14 08:06 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> +              </LinkTo>
Deze "custom" button dat eigenlijk een linkTo is, willen we dit niet eerder in de au-button component zetten voor hergebruik ?
beetje zoals we nu in au-button-link doen.
Want dit lijkt me iets dat we vaak genoeg gaan nodig hebben om een template voor te maken

2021-04-14 08:06 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> +              </LinkTo>
```
{{#if @route}}
  <LinkTo class="auk-button ....
```

2021-04-14 17:25 UTC, MikiDi commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> +              </LinkTo>
Absoluut, daar heb ik met Johan ook over gesproken, maar zo zijn er nog wel wat dingen in de auk ember components die gefixed moeten worden, vandaar buiten scope van deze story gelaten.

2021-04-14 17:27 UTC, MikiDi commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> -                data-test-agendaitem-titles-to-subcase
Thx. Done.

2021-04-15 07:30 UTC, ValenberghsSven commented on app/components/agenda/agendaitem/agendaitem-case/agendaitem-titles.hbs
> +              </LinkTo>
:heavy_check_mark:

2021-04-15 07:33 UTC, merged