Feature/kas 2441 structured identifier
kanselarij-vlaanderen/frontend-kaleidos pull request #865
Opened 2021-04-27 17:24 UTC by Annelies-P

Gebruik van generiek:GestructureerdeIdentificator voor intern publicatienummer

2021-04-28 14:49 UTC, erikap approved these changes

2021-04-30 07:36 UTC, ValenberghsSven commented
gelinkte PR

2021-04-30 09:52 UTC, ValenberghsSven commented
Terwijl ik dit lokaal wat test heb ik alvast een custom jenkins build gestart
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/44/

2021-04-30 11:36 UTC, ValenberghsSven commented
In de application.js adapter willen we geen pop-up voor die modellen gaan tonen, dus die moeten nog ignored worden 
`modelListToNotShowNotificationFor`
![image](https://user-images.githubusercontent.com/22245223/116690018-174e8d80-a9b9-11eb-82a7-45ed992d3dfb.png)

2021-04-30 11:47 UTC, ValenberghsSven commented
Er zijn 2 identieke patches bij aanpassingen van die nummer in de sidebar
![image](https://user-images.githubusercontent.com/22245223/116691071-9a241800-a9ba-11eb-9c88-e307699b6357.png)

2021-04-30 14:11 UTC, ValenberghsSven commented
> Terwijl ik dit lokaal wat test heb ik alvast een custom jenkins build gestart
> http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/44/

testen zijn alvast groen, maar de suffix wordt nog niet automatisch getest
![image](https://user-images.githubusercontent.com/22245223/116707028-85517f80-a9ce-11eb-8b3e-cea90e297e2a.png)

2021-04-30 14:24 UTC, ValenberghsSven requested changes
Pop-up notificaties voor aanmaken van de identifier en structured identifier willen we mogelijk niet, teveel popups.
Bij updaten dan vermoedelijk weer wel (ofwel zelf een 1 popup tonen na saven, ofwel de lijst splitsen in adapater, eerste optie is wenselijker uiteindelijk willen we zelf kiezen wanner we pop-ups tonen, en niet afhangen van de adapter)

Dat die structured-identifier 2 keer gepatched wordt, snap ik niet goed. Komt volgens mij door die `this.didChange`

2021-04-30 16:19 UTC, erikap commented
Die 2x aanroepen van `this.args.didChange(...)` is inderdaad de oorzaak van die 2 `PATCH` requests. Al had ik eigenlijk verwacht dat Ember zou detecteren dat die 2e uniek is en dus geen netwerk request zou sturen. 
Aangezien we dit probleem nog gaan hebben met de huidige `didChange`-interface als er meerdere attributen op het zelfde object wijzigen, stel ik voor om als tweede argument van `didChange(...)` ook een array van attribute names te aanvaarden. Dan zou de code hier worden `this.args.didChange(structuredIdentifier, ['localIdentifier', 'versionIdentifier'])`. Het tweede argument wordt momenteel nog niet gebruikt in de action-handler, dus we kunnen op dit moment nog wijzigen zonder breaking te zijn. Wat denken jullie @MikiDi @ValenberghsSven ?

Voor de pop-up notificaties ben ik nu eerder geneigd gewoon de vertalingen toe te voegen. Het zijn dan inderdaad verschillende notifications die getoond zullen worden on create/update, maar dat probleem stelt zich momenteel op verschillende plaatsen in de code. Ik zie het (structureel) opkuisen hiervan doorheen de hele codebase eerder als een aparte story.

2021-05-04 11:04 UTC, ValenberghsSven commented
@erikap , @Annelies-P  om dit ticket niet tegen te houden, kunnen we dit gewoon mergen en een task of follow-up story maken voor de issues op te lossen?

Op zich werkt deze code, er is gewoon een extra save, en deel extra popups bij aanmaak en een onvertaalde string

Er zijn andere tickets die ook die identifier nodig hebben

2021-05-05 11:36 UTC, ValenberghsSven commented
moet nog worden gesync met latest dev

2021-05-05 15:59 UTC, Annelies-P commented
mogelijk moeten de bestaande publicaties worden verwijderd na deployment, wegens outdated structuur publicatienummer. Dit kan problemen geven bij de query naar het eerstvolgende publicatienummer. Lijkt mij sowieso cleaner te starten met een lege dataset.

2021-05-07 08:09 UTC, merged