Feature/kas 2219 headers publicaties grid
kanselarij-vlaanderen/frontend-kaleidos pull request #868
Opened 2021-04-30 11:29 UTC by TaneeG

De originele tabel is naar een native tabel veranderd. Ik heb de paginatie placeholder gewijs toegevoegd, want deze werkt niet meer. Zoals met Michael besproken komt deze terug via een ander ticket.
De Inhoud van de rijen is niet voor dit ticket om op te lossen

Voor de designs => https://www.figma.com/file/D8NJqS92aZbzSx8GeSOaDr/%F0%9F%92%AF-Kaleidos---Designs-Digitale-Publicaties-v3?node-id=2688%3A54

2021-04-30 16:07 UTC, erikap commented on app/pods/publications/index/route.js
> +  }
Ik weet niet wat er exact is besproken rond de scope van de pagination, maar aangezien de `page` query param gedefinieerd is met `refreshModel: true` is het aanroepen van `this.getPublications()` niet nodig. Wanneer die verwijderd worden, kunnen de actions ook verhuizen naar de controller en hoeft `getPublications` geen aparte methode te zijn wat sommige wijzigingen (`this.apiSort` vs `apiSort`) ook overbodig maakt.

2021-05-01 14:01 UTC, erikap requested changes

2021-05-01 14:01 UTC, erikap commented on app/pods/publications/index/template.hbs
> +          <tr class="auk-table--interaction-cursor"  {{on "click" (fn this.navigateToPublication row)}}>
Dit patroon is waarschijnlijk overgenomen van de oude data-table, maar de hele rij mag niet klikbaar zijn (omwille van accessibility). Het detail van 1 publicatie kan enkel geopend worden door op de chevron te klikken in de laatste kolom.

2021-05-01 14:01 UTC, erikap commented on app/pods/publications/index/template.hbs
> +                <WebComponents::AuButton {{on "click" (fn this.navigateToPublication row)}} @skin="borderless"
Aangezien het hier over een navigation/transition naar een andere route gaat, kan beter een `<LinkTo>` gebruikt worden.

2021-05-01 14:17 UTC, erikap commented
Ik ben niet helemaal mee welke volgorde van kolommen er hier nu gevolgd is.

Er is enerzijds de volgorde die OVRB doorgegeven heeft (zie ook comment in Jira ticket van 11 maart)

1. Titel/naam
2. Datum van beslissing of ondertekening
3. Spoedprocedure indicator
4. Publicatienummer (eigen nummer dossier)
5. BS weknumer (Numac)
6. Vertaling progress badge
7. Drukproef progress badge
8. Verbetering progress badge (zie KAS)
9. Gevraagde publicatiedatum
10. Publicatiedatum
11. Intrekdatum
12. Opmerking
13. Handteken progress badge
14. (andere)

Anderzijds de volgorde uit het nieuwe design in  https://www.figma.com/file/D8NJqS92aZbzSx8GeSOaDr/%F0%9F%92%AF-Kaleidos---Designs-Digitale-Publicaties-v3?node-id=2688%3A54

Maar deze branch lijkt geen van beide te volgen?

2021-05-03 09:38 UTC, TaneeG commented
Ik heb de volgorde gevolgd van de designs. Daarbij had ik dan 1 dingetje over het hoofd gezien.
Paginatie zou nu moeten werken

2021-05-06 14:01 UTC, ValenberghsSven commented
VLC css is Karel zoveel mogelijk aan het verwijderen, uiteindelijk willen we daar vanaf, dus nieuwe toevoegen lijkt dan ook niet gewenst

2021-05-07 10:18 UTC, ValenberghsSven requested changes
- css gebruikt dat nog niet bestaat in de package
- Na deze change zijn de rijen niet meer klikbaar.

- de empty state is niet zo schitterend, dat willen we vermoedelijk anders zien 
![image](https://user-images.githubusercontent.com/22245223/117435220-e8429980-af2d-11eb-9e96-09733dfa0c55.png)

Is er een design met een empty state voorzien ?

2021-05-07 10:18 UTC, ValenberghsSven commented on app/styles/au-kaleidos-css/_auk-additions.scss
> +}
Deze auk-publication-table
dat zorgt voor een onnodige whitespace onder de footer
![image](https://user-images.githubusercontent.com/22245223/117429426-55066580-af27-11eb-9d14-00be039bfb69.png)


zonder die klasse plakt de footer tegen de bodem van de pagina, maar op zich niet zo erg want in een volgend ticket gaat die footer aangepast worden en gaat de auk-pagination css ervoor zorgen dat die footer juist is

2021-05-07 10:18 UTC, ValenberghsSven commented on app/pods/publications/index/template.hbs
> +<div class="auk-scroll-wrapper auk-publication-table">
die auk-publications-table, waarom staat die hier?
In de design/prototype is de height 100%

2021-05-07 10:18 UTC, ValenberghsSven commented on app/pods/publications/index/template.hbs
> +      <table class="auk-table auk-table--styled auk-table--bordered js-data-table">
auk-table--styled, auk-table--bordered en js-data-tabel
Die 3 zijn overgenomen van design/prototype vermoed ik?
De 2 van auk-table bestaan niet in de package, en brengen dus niets bij
die js-data-table doet ook niks. (vanwaar zou die zelfs komen)

Is dit toekomstige css dat nog moet komen? onbestaande css laat ik er liever uit, als iemand dan ooit die css toevoegt krijg je mogelijk ongewenste changes in je view.
(in het prototype zelf doen die klasses ook niks)

2021-05-07 10:18 UTC, ValenberghsSven commented on app/pods/publications/index/template.hbs
> -      @onClickRow={{this.navigateToPublication}}
deze onclickrow heeft geen refactor gekregen, en de rijen zijn nu niet meer klikbaar. gebruik die `this.navigateToPublication`

2021-05-07 13:00 UTC, ValenberghsSven commented
> Dit patroon is waarschijnlijk overgenomen van de oude data-table, maar de hele rij mag niet klikbaar zijn (omwille van accessibility). Het detail van 1 publicatie kan enkel geopend worden door op de chevron te klikken in de laatste kolom.

De klikbaarheid van de rij weghalen vind ik persoonlijk een slechte keuze.
Deels omdat de chevron knop buiten beeld valt als je alle kolommen hebt geselecteerd en je dus regelmatig opzij gaat moeten scrollen om publicaties te kunnen openen

2021-05-07 13:01 UTC, ValenberghsSven commented on app/pods/publications/index/template.hbs
> -      @onClickRow={{this.navigateToPublication}}
moet niet, express eruit gelaten

2021-05-07 13:09 UTC, ValenberghsSven commented
@erikap 
FYI
Oud ticket waar we expliciet hebben gekozen om rijen in een tabel klikbaar te maken
https://kanselarij.atlassian.net/browse/KAS-1060

2021-05-08 13:14 UTC, erikap commented
@ValenberghsSven Mijn opmerking dat de row niet klikbaar mag zijn, komt uit het prototype en [een discussie rond klikbare table rows](https://github.com/mu-semtech/ember-data-table/issues/20) met @Wolfr in de ember-data-table addon. Een hele rij klikbaar maken is niet accessible en wordt niet correct geïnterpreteerd door screen readers.

2021-05-09 08:16 UTC, Wolfr commented
We vinden dit voor de UX wel handig en hebben in laatste prototype een versie geïmplementeerd die wel toegankelijk is. Heb het na die discussie in ember-data-table beter onderzocht, blog post geschreven en Fanny heeft techniek toegepast.

https://johanronsse.be/2021/02/27/accessible-clickable-table-rows/

http://development.kaleidos-prototype.mono.digital/shared/publications/overview.html

Sent from my iPhone

> On 8 May 2021, at 15:14, Erika Pauwels ***@***.***> wrote:
> 
> ﻿
> @ValenberghsSven Mijn opmerking dat de row niet klikbaar mag zijn, komt uit het prototype en een discussie rond klikbare table rows met @Wolfr in de ember-data-table addon. Een hele rij klikbaar maken is niet accessible en wordt niet correct geïnterpreteerd door screen readers.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-10 07:00 UTC, erikap requested changes

2021-05-10 07:00 UTC, erikap commented on app/pods/publications/index/route.js
> +    this.params = params;
Dit lijkt me niet meer nodig nu alles weer in 1 method zit

2021-05-10 07:00 UTC, erikap commented on app/pods/publications/index/controller.js
> +  @tracked size = 10;
Van @MikiDi geleerd dat er een issue is met `@tracked` query params in de Ember versie die we momenteel gebruiken. Voor query params gebruiken we dus nog de oude Ember-manier: geen `@tracked` en wijzigen via `set('page', 5)` uit `@ember/object`

2021-05-10 07:02 UTC, erikap commented
> We vinden dit voor de UX wel handig en hebben in laatste prototype een versie geïmplementeerd die wel toegankelijk is. Heb het na die discussie in ember-data-table beter onderzocht, blog post geschreven en Fanny heeft techniek toegepast. https://johanronsse.be/2021/02/27/accessible-clickable-table-rows/ http://development.kaleidos-prototype.mono.digital/shared/publications/overview.html
> […](#)
> Sent from my iPhone
> On 8 May 2021, at 15:14, Erika Pauwels ***@***.***> wrote: ﻿ @ValenberghsSven Mijn opmerking dat de row niet klikbaar mag zijn, komt uit het prototype en een discussie rond klikbare table rows met @Wolfr in de ember-data-table addon. Een hele rij klikbaar maken is niet accessible en wordt niet correct geïnterpreteerd door screen readers. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Bedankt voor de input @Wolfr  :+1: 

@ValenberghsSven @TaneeG Aangezien het vroeger een expliciete vraag was om die rows clickbaar te maken, stel ik voor het in deze PR te doen zoals voorheen. Dan zet ik een nieuwe story op de backlog om het te corrigeren naar de nieuwe, accessible manier die @Wolfr beschrijft in zijn blogpost.

2021-05-10 10:12 UTC, TaneeG commented
Om even een freeze te maken in de designs voor deze story. Deze screenshot is de gebruikte volgorde
![image](https://user-images.githubusercontent.com/16088932/117643569-d7419480-b188-11eb-90d2-45aa1eb85c5a.png)
Met deze kolommen
![image](https://user-images.githubusercontent.com/16088932/117643722-fcce9e00-b188-11eb-9993-65af3f13026e.png)

2021-05-11 12:05 UTC, ValenberghsSven approved these changes
Deze is goed nu

2021-05-11 12:06 UTC, merged