KAS-2540: always link newsletterInfo-treatment
kanselarij-vlaanderen/frontend-kaleidos pull request #878
Opened 2021-05-11 09:43 UTC by MikiDi

See [KAS-2540](https://kanselarij.atlassian.net/browse/KAS-2540). Please note that there are some things to keep in mind when reviewing this, due to:
- `inverse: null`
- The fact that treatment/decision are currently treated as one object in our implementation

Goes with backend-PR https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/188

2021-05-11 14:08 UTC, ValenberghsSven commented
custom jenkins build
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/45/

2021-05-11 14:14 UTC, ValenberghsSven reviewed
Hier zit ook een `createRecord('agenda-item-treatment'`
https://github.com/kanselarij-vlaanderen/kaleidos-frontend/blob/6461f6972ed8b4c8abe7b2076e7977a065e6425b/app/pods/print-overviews/decisions/agendaitems/controller.js#L65

2021-05-11 14:23 UTC, ValenberghsSven commented
> Hier zit ook een `createRecord('agenda-item-treatment'`
> Die krijgt geen newsletter mee
> 
> https://github.com/kanselarij-vlaanderen/kaleidos-frontend/blob/6461f6972ed8b4c8abe7b2076e7977a065e6425b/app/pods/print-overviews/decisions/agendaitems/controller.js#L65

Hmmm, die beslissingen print-overview, gaan we die blijven onderhouden? daar is wel wat meer stuk aan nu. Editeren kan je hier ook niet meer (gebruikt iemand die view ?)

2021-05-11 15:00 UTC, ValenberghsSven requested changes
Enkel gecheckt in beslissingen tab en kort-bestek tab van agendapunt detail (aanmaken van beslissingen in print-overview werkt niet)

:heavy_check_mark:  Bij aanmaken/verwijderen van extra behandelingen met een bestaande nieuwsbrief zit de link goed. Nieuwsbrief kent meerdere behandelingen, meerdere behandelingen kennen dezelfde nieuwsbrief.

Je TODO is nog een plaats waar fouten uit kunnen komen:
:negative_squared_cross_mark:
Reproduceren:
agendapunt met 1 behandeling en geen nieuwsbrief.
voeg extra behandelingen toe
maak een nieuwsbrief (in data kent deze maar 1 behandeling)
verwijder de 1e behandeling die er al was
nieuwsbrief is weg
maak een nieuwe nieuwsbrief (in data kent die nu 0 behandelingen)
refresh
nieuwsbrief is weg.

:heavy_check_mark: in de kort-bestek zebra view zitten de links ook juist als er meerdere behandelingen bestaan en je maakt in deze view een kort-bestek aan

Ik heb ook verder gecheckt. Er zit in de nieuwsletter-service een stuk code om de data op te te halen. Die gebruikt de relatie tussen treatment en newsletter.
Ik dacht dat die mogelijk raar ging doen met meerdere treatments dat naar 1 newsletter wijzen, maar bij aanmaak van lokale mail campagne lijkt toch alles goed te zitten
https://github.com/kanselarij-vlaanderen/newsletter-service/blob/646ac5de2f7709e99627619d12d4dcf50e2ef31a/repository/index.js#L148

2021-05-11 15:00 UTC, ValenberghsSven commented on app/services/newsletter-service.js
> +      const agendaItemTreatments = await agendaitem.get('treatments');
todo oplossen, links liggen niet goed als je nieuwsbrief toevoegt vlak na toevoegen nieuwe behandeling.

Dit fixt de todo (lokaal even getest)
`const agendaItemTreatments = await agendaitem.hasMany('treatments').reload();`

2021-05-11 15:11 UTC, ValenberghsSven commented on app/services/newsletter-service.js
> +      const agendaItemTreatments = await agendaitem.get('treatments');
Je kan dit hier vermijden door die reload te doen vlak na de creatie van de nieuwe treatment in
app/pods/agenda/agendaitems/agendaitem/decisions/controller.js

Als je het in de service doet, ben je dan zekerder dat je data recent is voor je eraan begint.

Maar wat met concurrency,  wat als gebruiker kanselarij een beslissing toevoegt x minuten voor dat kort-bestek gebruiker een kort-bestek aanmaakt. moeten we ook agendaitem reloaden of eerder de treatments ophalen met een query ipv getter ?

2021-05-12 07:25 UTC, MikiDi commented
> Hmmm, die beslissingen print-overview, gaan we die blijven onderhouden? daar is wel wat meer stuk aan nu. Editeren kan je hier ook niet meer (gebruikt iemand die view ?)

Goeie vraag. Het lijkt me van niet. Ik ben er al meermaals achter proberen komen, maar geen sluitend antwoord ...

2021-05-18 08:42 UTC, MikiDi commented
> Hmmm, die beslissingen print-overview, gaan we die blijven onderhouden? daar is wel wat meer stuk aan nu. Editeren kan je hier ook niet meer (gebruikt iemand die view ?)

Aldus Johan: met oog op later gebruik bij het opmaken van beslissingen in Kaleidos, zal deze view wel weer gebruikt worden. We maken een nieuwe story om deze view in een maintainable state te krijgen.

2021-05-18 09:32 UTC, MikiDi commented
Vervolgstory https://kanselarij.atlassian.net/browse/KAS-2588 . Merging.

2021-05-18 09:38 UTC, merged