Feature/kas 2481 document aan vertaalaanvraag
kanselarij-vlaanderen/frontend-kaleidos pull request #955
Opened 2021-06-15 09:07 UTC by TaneeG

Build : http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/63/
PR:

2021-06-15 17:02 UTC, erikap requested changes
Op de multiple file upload die niet werkt na, is de logica OK.
Meeste changes die gevraagd zijn hebben te maken met layout.

2021-06-15 17:02 UTC, erikap commented on app/pods/publications/publication/translations/requests/controller.js
> +    }
Is deze if-else noodzakelijk. Indien je het resultaat van `yield translationActivity.generatedPieces` aan een variabele assigned, kan je daar dan niet gewoon `pushObject` op doen (want dat is een lege array als er nog geen pieces zijn)

2021-06-15 17:02 UTC, erikap commented on app/pods/publications/publication/translations/requests/template.hbs
> +            </AttachPopover>
Kan je een gewone primary button maken voor het opladen van het translation document ipv een actie-menu? Johan D. merkte op dat we die niet mogen verstoppen in een dropdown omdat gebruikers die vaak gaan nodig hebben.

2021-06-15 17:02 UTC, erikap commented on app/components/publications/publication/translations/translation-upload-modal.hbs
> +                  </div>
In tegenstelling tot wat in de story staat: de vertaallast input-fields zijn niet nodig in de upload-modal om een vertaald document op te laden.

2021-06-15 17:02 UTC, erikap commented on app/pods/publications/publication/translations/requests/template.hbs
> +              {{/each}}
Kan je deze lijst nog een aparte titel 'Ontvangen documenten (DD-MM-YYYY)' geven (analoog aan het titeltje 'Bijlagen') waarbij de datum de einddatum van de vertaling-activiteit is.

2021-06-15 17:02 UTC, erikap commented on app/components/publications/publication/translations/translation-upload-modal.hbs
> +              @multiple={{true}}
Multiple file upload lijkt niet te werken. Er worden wel meerdere files opgeladen, maar daarna kan je maar van 1 file de details bewerken. Volgens mij is het OK als we momenteel maar 1 file tegelijk toelaten. Vraagt misschien nog wat opkuiswerk van de overbodige `this.newPieces` dan.

2021-06-16 13:55 UTC, TaneeG commented
@erikap Ik denk alle issues gecovered te hebben :)

2021-06-17 06:55 UTC, erikap commented
Voornamelijk nog kleine fixes voor edge cases gedaan.

Deze is wel belangrijk: https://github.com/kanselarij-vlaanderen/kaleidos-frontend/pull/955/commits/0bfc1119b7255fa5e2ebbef893003fbe6cc7b243 
In het geval van meerdere aanvragen werd een vertaald document nu altijd gelinkt aan de laatste aanvraag in de lijst omdat de upload-modal mee in de each-loop zat.

Wat we nog moeten toevoegen is dat we de `receipt-date` (datum ontvangst) ook nog capteren voor ieder stuk zodat we die kunnen weergeven in de overzichtstabel van documenten. Dat is nu nog hardcoded op `-`. In de backend kunnen we hiervoor het predicate `fabio:hasDateReceived` gebruiken op het model van `piece`.

2021-06-18 11:55 UTC, TaneeG commented
nieuwe PR: kanselarij-vlaanderen/kaleidos-project#203

2021-06-18 17:23 UTC, ValenberghsSven commented
custom jenkins :green_circle: :heavy_check_mark: 
http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/66/

2021-06-18 18:58 UTC, erikap approved these changes

2021-06-18 19:01 UTC, merged