Feature/kas 2497 config emails
kanselarij-vlaanderen/frontend-kaleidos pull request #977
Opened 2021-06-30 09:08 UTC by TaneeG

Build : http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/71/
PR: kanselarij-vlaanderen/kaleidos-project#201

2021-06-30 10:01 UTC, MikiDi commented on app/pods/settings/emails/template.hbs
> +        <Auk::Input
Kan je proberen de gewone indentatie aan te houden hier (2 spaties)? Graag ook geen padding binnen `{{ }}`. Wanneer we tot de standaard ember linting rules komen zal dit in de toekomst ook meer geautomatiseerd kunnen denk ik.

2021-06-30 10:02 UTC, MikiDi approved these changes

2021-07-01 08:21 UTC, erikap requested changes

2021-07-01 08:21 UTC, erikap commented on app/pods/settings/emails/controller.js
> +    return this.emailToProofRequest === '' || this.emailToProofRequest === '' ;
Hier check je 2x hetzelfde.

Misschien is de [`isBlank` helper](https://api.emberjs.com/ember/3.26/functions/@ember%2Futils/isBlank) hier ook handig.

2021-07-01 08:21 UTC, erikap commented on app/pods/settings/emails/route.js
> +  async model() {
Onnodige `async`

2021-07-01 12:58 UTC, erikap approved these changes

2021-07-02 13:25 UTC, merged