KAS-2246 Added corrector to side panel,table view & model
kanselarij-vlaanderen/frontend-kaleidos pull request #997
Opened 2021-07-08 11:11 UTC by TaneeG

Build : http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/71/
PR: https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/209

2021-07-11 16:45 UTC, erikap requested changes

2021-07-11 16:45 UTC, erikap commented on app/components/publications/publication-sidebar.hbs
> +              {{on "input" (perform this.setProofprintCorrector)}}
Probeer overal dezelfde casing aan te houden voor `proofPrint` (`setProofprintCorrector` vs `proofPrintCorrector`) om fouten te vermijden.

2021-07-11 16:45 UTC, erikap commented on app/pods/publications/index/template.hbs
> +                          <p>{{row.publicationSubcase.proofPrintCorrectorInitials}} </p>
De story description is hier misschien wat verwarrend geschreven. Je hoeft niets speciaal te doen voor de initialen. Je mag in de overzichtstabel gewoon weergeven wat er in de property `proofPrintCorrector` zit (en normaal gaat de gebruiker daar initialen in invullen, maar dat doet er an sich niet toe).

2021-07-12 15:16 UTC, erikap approved these changes

2021-07-13 09:20 UTC, ValenberghsSven requested changes
Niets op te merken aan de huidige code PR, maar de acceptatie criteria zijn niet voldaan

_Weergave van initialen met icon in overzichtstabel_

Als je in de sidebar een volledige naam typt, hoe moeten wij dan de initialen gaan bepalen ?
Als de personen die werken aan de publicatie vaste personen zijn, kunnen we dan hun namen en bijhorende initialen niet in de `constants` steken?
Maar dan moet de naam dat getypt is al gaan matchen met wat wij in constants hebben.  (typefouten....) 
Er is gekozen voor een gewoon inputveld, maar dat botst met de wens voor initialen in het overzicht lijkt mij

Als we opteren om voorlopig geen initialen te tonen dan kan deze PR door mits aanpassingen van de acceptatie criteria

2021-07-13 09:53 UTC, erikap commented
@ValenberghsSven Acceptatie criteria aanpassen is ok. De story description is inderdaad wat verwarrend geschreven. We hoeven voor die initialen niets speciaal te doen. We tonen overal gewoon letterlijk wat ze ingetypt hebben in de property `proofPrintCorrector` (en normaal gaat de gebruiker daar initialen in invullen, maar dat doet er an sich niet toe).

2021-07-13 10:14 UTC, ValenberghsSven approved these changes
acceptatie criteria aangepast

2021-07-13 10:15 UTC, merged